### ISSUE TITLE
All existing devopsdays.org links must be mainitained

### ISSUE THREAD

**Issue by mattstratton** [devopsdays/devopsdays-web#1]

**Comment by mattstratton** [comment]
I think this is actually implied by the work that will be done in #29. Not sure if this needs to stay open?

**Comment by m1keil** [comment]
Just to understand, what is our strategy here:
Do we want to migrate all the old sites to new format? or instead just generate all the old sites once and place them in RO place, and use the new format to the newer DOD sites?

**Comment by mattstratton** [comment]
I think we have to migrate everything to the new format. Hugo could have the capability of whacking anything in the `/public` directory at any time, etc. 

I did a much larger migration from WordPress to Hugo. At least in this case we have text files to work with :)

**Comment by m1keil** [comment]
Oh, wow, I had it entirely different in my mind.

**Comment by mattstratton** [comment]
Since this was a discussion requirement, and there isn't any work to do with this issue specifically (#29 actually is the work item) I am going to close this.
