### ISSUE TITLE
Discuss data-driven sponsor info

### ISSUE THREAD

**Issue by mattstratton** [devopsdays/devopsdays-web#10]
It might be useful to be able to abstract out sponsors for use by multiple events, for example having a `data/sponsors` directory with a `chef.yml`, etc, for anyone who wanted to have Chef as a sponsor (that data file could contain the URL to link to, and the image path, although it would be more ideal just to name them in conjunction with each other).

Downside is if logos change from year to year, but you can still repurpose the instance of that sponsor.

**Comment by m1keil** [comment]
It's an interesting idea. I see two big potential issues:
1. logos might change
2. links to sponsors - some sponsors like to have the links with some tracking information

**Comment by mattstratton** [comment]
Yeah, I think it still makes sense to store re sponsor info as data objects, which *could* be reused optionally by other events but not necessarily required. Putting them into data YAML or TOML files makes there less markup to be done. Also it lets there be common templates, etc.

**Comment by mattstratton** [comment]
But the alternative might be to have `data/EVENTNAME/sponsors` directories, etc, which still allows for the normalization of sponsor data.

**Comment by phrawzty** [comment]
>  1. logos might change

In general, brands prefer that their current imagery be used whenever possible - I've never had a sponsor complain about old logos being replaced by new ones, even on past events.

>  2. links to sponsors - some sponsors like to have the links with some tracking information

Agreed.  @mattstratton, is there a way to, say, locally override an element?  For example, there's a `chef.yml` that contains the standard accoutrements, and in a given event, we override the URL element for Chef.  Is that a thing?

**Comment by mattstratton** [comment]
I think that actually will really complicate the user experience. What I would think you would do is have a `chef.yml` which would have two values; the name of the image/logo and the landing URL. If someone needed to override it, they could make a `chef-chicago-2015.yml` that just copied the existing one, keep the existing logo definition URL, and change the landing URL, and then in their event's data file, list the sponsor as `chef-chicago-2015` instead of `chef`.

Ultimately, what I envision is that the entire event can be driven from the data files, with minimal need to override the templates, which are the things that will consume the data files. 

Actually, I have an idea. You might be able to take the sponsor value and have it have an optional second parameter, which would be the URL. If the URL isn't included, it would use the one from the sponsor data file. If someone really needed a different logo, then it's definitely a custom sponsor and should have its own file.

**Comment by phrawzty** [comment]
> You might be able to take the sponsor value and have it have an optional second parameter, which would be the URL. If the URL isn't included, it would use the one from the sponsor data file.

This sounds like exactly what I was envisioning. :smile:

**Comment by mattstratton** [comment]
I think this was pretty much settled, so I'm going to close this issue. If anyone disagrees, feel free to re-open it :)
