### ISSUE TITLE
Move ghent frontpage image

### ISSUE THREAD

**Issue by mattstratton** [devopsdays/devopsdays-web#102]
Currently the frontpage of ghent2009 references a deeply embedded image in the blog subdirectory `/blog/wp-content/uploads/2010/02/devopsdays-large-transparent.png`

We need to either see if this dang image works TODAY, and if so, recreate it statically.

See PR #101

**Comment by bridgetkromhout** [comment]
Fixed: https://github.com/devopsdays/devopsdays-web/pull/283
