### ISSUE TITLE
Identify "legacy" events that still use the blue footer

### ISSUE THREAD

**Issue by mattstratton** [devopsdays/devopsdays-web#104]
The events in 2009 (and some in 2010, maybe in 2011) have the "blue footer" with lists of other devopsdays in the bottom of their event page. We need someone to make a list of all the legacy events where this occurs, as it will require special handling.

**Comment by cacorriere** [comment]
Ghent 2009 

Sydney 2010
Mountain View 2010
Hamburg 2010
Sao Paulo 2010

Boston 2011
Mountain View 2011
Melbourne 2011
Bangalore 2011
Gotebord 2011
Manila 2011

Austin 2012
Delhi 2012

**Comment by bridgetkromhout** [comment]
Thanks, @cacorriere!
