### ISSUE TITLE
migration for 2016 events

### ISSUE THREAD

**Issue by bridgetkromhout** [devopsdays/devopsdays-web#107]
Comment here if you're committing to doing the initial migration and any updates for a city. Some how-to info is at https://github.com/devopsdays/devopsdays-web/blob/master/README.md#creating-a-new-event.

  - [x] Los Angeles
  - [x] Vancouver - Apr 15 & 16
  - [x] London - Apr 19 & 20
  - [x] Denver - Apr 21 & 22
  - [x] Atlanta - Apr 26 & 27
  - [x] Austin - May 2 & 3
  - [x] Kiel - May 12 & 13
  - [x] Seattle - May 12 & 13 - @kmugrage
  - [x] Toronto - May 26 & 27 - @whatschrisdoing
  - [x] Istanbul - Jun 3 & 4
  - [x] Washington, DC - Jun 8 & 9
  - [x] Salt Lake City - Jun 14 & 15 - @davidasnider
  - [x] Silicon Valley - June 24 & 25 - @pmoosh
  - [x] Amsterdam - Jun 29, 30 & Jul 1 @yvovandoorn
  - [x] Minneapolis - Jul 20 & 21 - @bridgetkromhout 
  - [x] Portland - Aug 9 & 10 - @jyee
  - [x] Boston - Aug 25 & 26 - @masteinhauser  [not started]
  - [x] Chicago - Aug 30 & 31 - @mattstratton
  - [x] Oslo - Sep 5 & 6
  - [x] Dallas - Sep 15 & 16 - @benjohnson77 
  - [x] New York - Sep 23 & 24
  - [x] Boise - Oct 7 & 8 - @tresni 
  - [x] Singapore - Oct 8 & 9 - @ctrabold
  - [x] Detroit - Oct 12 & 13 - @bchess
  - [x] Philadelphia - Oct 26 & 27 - @peterjshan 
  - [x] Ghent
  - [x] Raleigh
  - [x] Kansas City [not started]
  - [x] New Zealand [not started]
  - [x] Ohio - @kjenkins19
  - [x] Nashville
  - [x] Madison
  - [x] Cape Town [not started]

**Comment by tresni** [comment]
I can do Boise

**Comment by bchess** [comment]
We haven't added any content yet to Detroit 2016, but I'd like to. Are we still on track for launching the new website this week?

**Comment by markcornick** [comment]
I'm working on Washington DC 2016.

**Comment by tresni** [comment]
Boise is being prepped under #202

**Comment by bridgetkromhout** [comment]
All of 2016 is now migrated.
