### ISSUE TITLE
/events view doesn't know about the past

### ISSUE THREAD

**Issue by glasnt** [devopsdays/devopsdays-web#10798]
https://github.com/devopsdays/devopsdays-web/blob/main/themes/devopsdays-theme/layouts/partials/past.html#L6

it looks like we're hardcoding the range for "Past" years, and currently there's no 2021 event listing. 

I recall *some* events ran (not many), but they aren't being listed. 

Having to increment a counter each year seems suboptimal, but I'll see what I can work out.

**Comment by glasnt** [comment]
With #10801 merged, the partial partial fix is now in place. 

Things yet to confirm: 

 * how to list events by year without having to increment the max year?
 * are cancelled events sufficiently filtered away from this view?

**Comment by somatorio** [comment]
maybe using https://gohugo.io/functions/dateformat/ to get the year from .Site.LastChange?

**Comment by mattstratton** [comment]
This was fixed in #13686
