### ISSUE TITLE
Sponsor logos are two wide instead of three

### ISSUE THREAD

**Issue by kmugrage** [devopsdays/devopsdays-web#108]
It makes for a pretty long list.

**Comment by bridgetkromhout** [comment]
Agreed that three-wide looks better.

**Comment by bridgetkromhout** [comment]
With the fixed merged, do we want this issue so we revisit it for fix-optimizing later? /cc @mattstratton

**Comment by mattstratton** [comment]
I will tag this for the "future enhancements" milestone and move it out of "ready" state. This will likely get revisited when we redesign the UX anyway.

**Comment by bridgetkromhout** [comment]
This goes away if we switch to a sponsor footer (https://github.com/devopsdays/devopsdays-web/issues/295).
