### ISSUE TITLE
Remove auto capitalization of spaced sur names

### ISSUE THREAD

**Issue by yvovandoorn** [devopsdays/devopsdays-web#11313]
Currently when someone has multiple spaced surnames, e.g. 'van Doorn' or 'van der Voort', there is code in place that this automatically capitalized. Within the Netherlands, this is against the norm where these extra words remain lower case. 

Per @mattstratton, I'm creating an issue on the problem.

**Comment by mattstratton** [comment]
I fixed this, but my update to use dart-sass broke other stuff. I'll do the fix and build on an intel mac this weekend :)
