### ISSUE TITLE
Extra "cd" line in add_speakers.sh breaks the script

### ISSUE THREAD

**Issue by skryukova** [devopsdays/devopsdays-web#11608]
This extra `cd` line breaks the script when using git-bash on Windows.
https://github.com/devopsdays/devopsdays-web/blob/9b50479474ff89c971391112ab8dea7a8b406c4f/utilities/add_speakers.sh#L8

You get error
`./utilities/add_speakers.sh: line 8: cd: ./utilities: No such file or directory
`

**Comment by skryukova** [comment]
I believe that the add_program.sh has a similar issue, but in that script the order of the lines is reversed.

https://github.com/devopsdays/devopsdays-web/blob/9b50479474ff89c971391112ab8dea7a8b406c4f/utilities/add_program.sh#L5-L7

**Comment by mattstratton** [comment]
What directory are you in when running the script?

**Comment by skryukova** [comment]
Root devopsdays-web directory. I run the scripts as "./utilities/add_speaker.sh".

**Comment by bridgetkromhout** [comment]
When I wrote them, I only tested those scripts on a Mac. PRs to improve them for Windows/Linux/etc are very welcome. Thanks!

**Comment by yvovandoorn** [comment]
I think the right order is 
```
cd `dirname ${0}`
source common_code
```

Not:
```
source common_code
cd `dirname ${0}`
``` 
As that would miss `common_code` outside of the `utilities/` directory

```
cd `dirname ${0}`
source common_code
cd `dirname ${0}`
```
As there is no need to do a double `cd`. 

I've submitted #11834 to at least align on a pattern.
