### ISSUE TITLE
Getting weird error while trying to run locally

### ISSUE THREAD

**Issue by gilzellner** [devopsdays/devopsdays-web#1169]
the error:
"theme/event/single.html" is an incomplete template
appears for all events.
this is from a cloned copy of the main site and not my fork.

**Comment by bridgetkromhout** [comment]
This is probably due to having Hugo 0.15 instead of Hugo 0.16 locally.

**Comment by mattstratton** [comment]
Yup. That's totally a Hugo < 0.16 symptom.
