### ISSUE TITLE
Malformed Progress Chef sponsor link

### ISSUE THREAD

**Issue by gallimorej** [devopsdays/devopsdays-web#11750]
It looks like the sponsor link for Progress Chef is malformed wherever it shows up. It checked DevOpsDays DC and DevOpsDays Chicago and the same problem for both. I looked at the progresschef.yml file but nothing was obviously wrong with it.

https://devopsdays.org/events/2022-washington-dc/welcome/www.chef.io
https://devopsdays.org/events/2022-chicago/welcome/www.chef.io

**Comment by MikeRosTX** [comment]
URL formatting fixed this issue.
