### ISSUE TITLE
Clean up event dates

### ISSUE THREAD

**Issue by FloorD** [devopsdays/devopsdays-web#11933]
On the chapter pages you can navigate to previous years for that city. When you do though the order of the years becomes all mangled and confusing. 

![Screenshot_20221004-120920_Chrome (1)](https://user-images.githubusercontent.com/1087213/194006421-87a74160-cce5-4d16-87ec-8cfa18ef7739.jpg)

There's ongoing work to fix this, but we would love to actually fix broken date formats and clean up the repo.

**Dates should be reflected like so:**
Unquoted YYYY-MM-DDTHH:MM:SS+TZ:TZ
For example: `2019-01-04T00:00:00+02:00`, or `2019-01-05T23:59:59+02:00`

Please comment with a chapter you found using the wrong date format, and note whether you'd like to pick up the task of changing it..

**Comment by MiguelAlho** [comment]
The issue isn't poorly formatted dates (at least not in the cases I found) but missing `.startdate` on the events (which is valid, based on how we are using the event yml). The  `range sort` call that is used to order the events fails (silently) when the property it is sorting on is undefined in the event. 

I've found it easier/more readable to precompute the lists and then print the filtered list, than to try to iterate and print, which I've tried to reflect into #11956 , same as what was done in #11923
