### ISSUE TITLE
Hugoserver.sh doesn't stop with Ctrl+C

### ISSUE THREAD

**Issue by stahnma** [devopsdays/devopsdays-web#1233]
I'm not sure if I'm using the script properly, but Ctrl+C doesn't stop it. I have to manually kill the hugoserver proceses or docker stop the container running.

**Comment by mattstratton** [comment]
Yeah, I had the same problem too. It's because it's in the container and being weird. I'm not quite sure how to fix it, but I'll take a look at it at some point because it's annoying me.

**Comment by mattstratton** [comment]
Fixed in #1640
