### ISSUE TITLE
Migrate legacy videos off vimeo

### ISSUE THREAD

**Issue by bridgetkromhout** [devopsdays/devopsdays-web#1268]
We're going to renew the vimeo pro account for another year while planning what to do with the content. 

Using a central account caused resource contention with upload limits and quota even before the global event numbers doubled, so staying on vimeo makes no sense. New videos have been going up on individual events' youtubes.
- Ideally: decentralized and locally controlled
- Realistically: core organizers will need to migrate any content from former events who don't have involved members.

Youtube and archive.org are options.

@KrisBuytaert mentions the possibility of using an API for standardizing the export/import process.

TODO: After a video is moved, update any links/embeds on the previous event pages.

**Comment by KrisBuytaert** [comment]
We might want to consider that Youtube hosted means we can't control ads around the content.  We might get weird situations with sponsors this way.

**Comment by iennae** [comment]
Based on information from vmbrasseur,

* Vimeo doesn't appear to have ready made tools, but their API will allow us to query for data. /users/:id/videos for the metadata, title, description, and video file download. Original file won't be available unless we paid for it before now. Not sure if we've been paying in the past .
* Documentation for the Internet Archive S3 API: https://github.com/vmbrasseur/IAS3API
* Python/command-line interface for the internet archive: https://github.com/jjjake/internetarchive

We can start uploading now to the Archive, and after the "devopsdays" collection is created, add all the videos to the devopsdays collection.

**Comment by bridgetkromhout** [comment]
I've paid for another year of Vimeo to buy us time.

**Comment by phrawzty** [comment]
Dailymotion has traditionally hosted the Paris Devops(days) videos in an advertisement-free context. Maybe they'd be willing to do the same for the Devopsdays series of events world-wide?

**Comment by mattstratton** [comment]
I'm resurrecting this thread because we don't have any documented guidance (that I can find) for organizers about where to put their videos.

**Comment by iennae** [comment]
We need to figure it out before October still.

**Comment by bridgetkromhout** [comment]
Work in progress. I downloaded the files before the deadline.

**Comment by bridgetkromhout** [comment]
Not really website-related so closing this here.
