### ISSUE TITLE
The DevOpsDays privacy policy page is "inactive"

### ISSUE THREAD

**Issue by issyl0** [devopsdays/devopsdays-web#12990]
I was notified of this by a sponsor - oops! We appear to have used a service called Iubenda to host the global DevOpsDays privacy policy, but it's now showing as "inactive" on https://devopsdays.org/privacy/. That's not good.

<img width="1314" alt="Screenshot 2023-07-10 at 16 50 00" src="https://github.com/devopsdays/devopsdays-web/assets/355033/b49eb9d9-ae28-4954-a72c-e62157a6ec52">

https://github.com/devopsdays/devopsdays-web/blob/main/themes/devopsdays-theme/layouts/shortcodes/privacy_policy.html

What would the alternative location/text be, and can we add it?

**Comment by mattstratton** [comment]
I just renewed  this and it should now show
