### ISSUE TITLE
Google maps on location not working properly

### ISSUE THREAD

**Issue by somatorio** [devopsdays/devopsdays-web#13115]
The google maps frame at the location page is failing with "This page can't load Google Maps correctly.", and shows "for development purposes only".

<img width="572" alt="image" src="https://github.com/devopsdays/devopsdays-web/assets/7087238/6add75c6-0440-4861-857a-1fe0f2b14642">

At the browser console there is the following error:
> You must enable Billing on the Google Cloud Project at https://console.cloud.google.com/project/_/billing/enable Learn more at https://developers.google.com/maps/gmp-get-started

I could not find any project at devopsdays.org account on GCP to check further into it :(

**Comment by somatorio** [comment]
Just check and this doesn't happen for all events location page... Worked just fine at Dallas and Chicago, but not for Montreal and Rio de Janeiro

**Comment by mattstratton** [comment]
Honestly this is an old tech debt issue - we missed retiring some shortcode I guess. We killed the google maps stuff when we removed it from the home page (partially for the issue that we needed to have an account and api key, etc)

**Comment by chriscoffee** [comment]
Are you still planning on entirely removing the shortcode for maps or rotate it an obfuscate/lock it down? 

> Looks like in #10313 I was going to adjust the API key for this and maybe....never did?

**Comment by mattstratton** [comment]
I’m not *planning* to do anything, myself, but I would think we need to do one or the other. 

Mostly was sharing that the other issue existed and I never fixed it :)

**Comment by chriscoffee** [comment]
> I’m not _planning_ to do anything, myself, but I would think we need to do one or the other.
> 
> Mostly was sharing that the other issue existed and I never fixed it :)

Didn't communicate properly sorry. More trying to get some direction or thoughts 😂

**Comment by mattstratton** [comment]
I think the biggest issue was totally removing the short code is that it will break a bunch of old pages, but maybe that’s not a huge deal since … who needs the map of a venue from a past event?

it does seem prudent to remove vs fix because of the issue of maintaining a Google account just for the map api.
