### ISSUE TITLE
Refactor data directory

### ISSUE THREAD

**Issue by mattstratton** [devopsdays/devopsdays-web#133]
The model for the data directory should change to look like this:

```
/data
├── events
│   └── 2016
│       └── ponyville
│           ├── meta.yml
│           └── speakers
│               ├── apple-jack.yml
│               ├── rainbow-dash.yml
│               └── twilight-sparkle.yml
└── sponsors
    └── 2016
        ├── bluthcompany.yml
        └── sitwell.yml

```

The `meta.yml` file will contain what is in the current `yyyy-city.yml` file. Speaker bios go in the "speakers" folder. This way you can have different bios for each year, as they will likely change.

Sponsors directory is also changed YOY as URL's may differ. We will likely also make a change to the `/static` directory as such:

```
/static

├── events
│   └── 2016
│       └── ponyville
│           ├── logo.png
│           └── prospectus.pdf
└── sponsors
    └── 2016
        ├── bluthcompany.png
        └── sitwell.png

```

So each event gets it's own static folder in the appropriate year, as well as each sponsor. The url for the 2016 Ponyville event would be `devopsdays.org/events/2016/ponyville/logo.png`

Discuss.

**Comment by mattstratton** [comment]
The range listed below is going to be a key element for when we refactor the data directory. Notice how you pass the variables, etc. So the new code would probably be something like this:

   `.Site.Data.events $e.year "speakers" (printf "%s" (lower $e.city))`

and to get at the meta.yml for the city it will be

`.Site.Data.events $e.year (printf "%s" (lower $e.city))`

**Comment by bridgetkromhout** [comment]
I'd like for us to fix all the 2016 events as they come in, with redirects to the deprecated /proposals/ as needed. Reminded by https://github.com/devopsdays/devopsdays-web/pull/143.

**Comment by mattstratton** [comment]
@bridgetkromhout - when you say fix them, you mean move them to the new structure? I'm not sure it will be backwards compatible, so when I change to support this structure I'll probably just switch the existing events.

**Comment by bridgetkromhout** [comment]
Excellent; we're thinking along the same lines. I meant "change old programs that people create the old way to all be the new way". Switching the existing events is exactly perfect. (We'll just need a few redirects since people might be linking to their own talk page.)

**Comment by mattstratton** [comment]
For now, we will put this into "Future Enhancements" as it's a bigger thing to bite off than I thought.

**Comment by mattstratton** [comment]
Closing this in favor of https://github.com/devopsdays/devopsdays-theme/issues/229
