### ISSUE TITLE
Put Bangalore and Bengaluru into the same event group

### ISSUE THREAD

**Issue by jyee** [devopsdays/devopsdays-web#13367]
Bangalore and Bengaluru are the same city. They switched from the anglicized name to the local name in 2018 and currently it appears as 2 different cities. Bridget has suggested that we group the two using the `event_group` setting in the event yaml.

**Comment by prafull904434** [comment]
sir,may i work with this issue,can you assign to me

**Comment by devyani277** [comment]
Can you please assign this issue to me?
