### ISSUE TITLE
correct the dates on the map

### ISSUE THREAD

**Issue by mattstratton** [devopsdays/devopsdays-web#137]
As mentioned in #55:

```
 dates are showing as "YYYY-MM-DD" vs. the existing site showing "mmm DD"
```

If someone wants to take this on, that's cool. I don't think it's a showstopper right now.

**Comment by davidasnider** [comment]
PR #155 submitted for date formatting

**Comment by bridgetkromhout** [comment]
This was somewhat fixed but only has start dates now. Could use end dates.

**Comment by bridgetkromhout** [comment]
Related to https://github.com/devopsdays/devopsdays-web/issues/882 - needs startdate math as well as end dates.

**Comment by bridgetkromhout** [comment]
Let's say Scenario 1 is to leave this as-is, which looks like this:

![screen shot 2016-11-19 at 10 33 27 pm](https://cloud.githubusercontent.com/assets/2104453/20460445/10fbb360-aea8-11e6-9b41-8f79fa45541d.png)

We've been living without both start and end dates on the map, but the problem with not showing the end date is it assumes people know these are two-day events (which maybe we should not assume).

If we want to change it, it's trivial to fix https://github.com/devopsdays/devopsdays-web/blob/master/themes/devopsdays-responsive/layouts/partials/map.html#L26:

```
-          ['{{ .city}}', {{ .coordinates | safeJS }}, '{{ dateFormat "Jan 2" .startdate }}', '/events/{{ .name }}'],
+          ['{{ .city}}', {{ .coordinates | safeJS }}, '{{ dateFormat "Jan 2" .startdate }}-{{ dateFormat "2" .enddate }}', '/events/{{ .name }}'],
```

But this is assuming we want it to look somewhat more like it did in the webby days. The down side is that single-day events (like Moscow) and events that span a month barrier (Minneapolis in this test) would look strange; let's call this Scenario 2:

![screen shot 2016-11-19 at 10 29 18 pm](https://cloud.githubusercontent.com/assets/2104453/20460437/dda83a88-aea7-11e6-8a69-130516674bb3.png)

Alternatively, if we keep the full month formatting, it would look like Scenario 3 here:

![screen shot 2016-11-19 at 10 24 42 pm](https://cloud.githubusercontent.com/assets/2104453/20460441/f0e2f502-aea7-11e6-825a-724e4720b5af.png)

@mattstratton, do you have a preference?

**Comment by mattstratton** [comment]
I would go for scenario 4, which is:

1) if one day event, show only the one date
2) if spans a month barrier, show both months
3) if neither 1 or 2, show month only once. 

Since this is all being opened up in the redesign, I think it's fine to tackle the right way.

**Comment by mattstratton** [comment]
The reason I say this, is in the redesign the dates of the events are displayed on the front page not only on the map element; so we need to solve for this anyway.

**Comment by bridgetkromhout** [comment]
Okay, here's what Scenario 4 looks like (with fake dates for Warsaw, as a demonstration). PR in flight - merge if this is what you wanted.

![screen shot 2016-11-20 at 6 08 54 pm](https://cloud.githubusercontent.com/assets/2104453/20467516/e489a38a-af4e-11e6-9a1a-4606b26afdab.png)
