### ISSUE TITLE
Make specific pages for individual organizers

### ISSUE THREAD

**Issue by mattstratton** [devopsdays/devopsdays-web#13757]
This had been part of the refactor, but this is to move the organizer information out of the data file, and instead use pages for it

**Comment by mattstratton** [comment]
If we are to do this, i think that we need to keep in mind the following:

1. **ensure backwards compatibility** - this is actually pretty easy. the current way organizers are shown is using the shortcode `list_organizers`, which is just put in the example file for `contact.md`.  So once there is a capability for this breakdown, you would "opt in" to using it by making your `contact.md` of the type "contact", which would use a different template (and make sure your `contact.md` doesn't have the shortcode.
2. I guess i really only was thinking about the first thing, so there isn't a number 2

**Comment by mattstratton** [comment]
for more info on above, consider this:

the current content of `/utilities/examples/events/yyyy-city/contact.md` is:
```
+++
Title = "Contact"
Type = "event"
Description = "Contact information for devopsdays CITY YYYY"
+++

If you'd like to contact us by email: {{< email_organizers >}}

**Our local team**

{{< list_organizers >}}


{{< list_core >}}
```

This change be implemented by creating (in the theme directory) `layouts/organizer/single.md` and `layouts/contact/single.md`. (the first is the layout for a single organizer, the second is the layout for the contact page)

The example file referenced above would be changed to something like:

```
+++
Title = "Contact"
Type = "contact"
Description = "Contact information for devopsdays CITY YYYY"
+++

```
We also need to update `utilities/add_organizers.sh` to create each organizer file (likely path is `/content/events/yyyy-city/organizers/` instead of manipulating the data file.

**Comment by mattstratton** [comment]
I started to spike on this and I'm starting to wonder if it's worth it - it also will add a lot more pages to generate at build time. Hmm.

**Comment by phrawzty** [comment]
I'm not personally convinced that the additional complexity & build time is
worth it. 🤷

**Comment by mattstratton** [comment]
I wish I could remember why I wanted to implement this. 

It might have just been part of the “everything is a page” model of the theme refactor that I’ve kind of given up on at this point 😂

**Comment by toshywoshy** [comment]
The only reason this could be interesting, is if you want to link organisers to multiple events and then have them listed on a page, so an individual organiser's page would state the other events they would be helping out with
But I think the overhead is too much and most probabily not worth the effort
