### ISSUE TITLE
Revisit the /sponsor page at the root

### ISSUE THREAD

**Issue by mattstratton** [devopsdays/devopsdays-web#138]
On the current site, if you go to http://www.devopsdays.org/sponsor/, there is a lot of outdated information. I don't think it's linked anywhere internally, but it's what someone might guess in terms of figuring out how to sponsor the event. 

I am not planning to migrate this existing, incorrect content, but the "sponsor guidelines" mentioned by @bridgetkromhout in #85 would solve this.

This issue is marked primarily as "wontfix" for migration purposes - we will NOT migrate the out of date information unless @jedi4ever or @bridgetkromhout disagrees.

**Comment by bridgetkromhout** [comment]
:thumbsup:

**Comment by bridgetkromhout** [comment]
Agreed. I replaced the outdated info with https://github.com/devopsdays/devopsdays-web/issues/201.
