### ISSUE TITLE
Issue adding speakers with script

### ISSUE THREAD

**Issue by jerdog** [devopsdays/devopsdays-web#13876]
I'm trying to add our speakers, and getting the following error:

```bash
utilities git:(jerdog/kc2024-AddProgram) ✗ ./add_speakers.sh                                 
Enter your event year (default: 2024): 2024
Enter your city name: Kansas City
sed: 1: "../content/events/2024- ...": invalid command code .
```

Anyone else seeing this? It will create the folder `speakers` but errors out I'm guessing here  since it doesn't create the file

https://github.com/devopsdays/devopsdays-web/blob/9cc902eb15c1cdf8e607fa6f45f9fc951242e525/utilities/add_speakers.sh#L35

**Comment by yvovandoorn** [comment]
Putting in my comments from Slack in here:

It looks like its coming out of `sed` .. specifically the BSD shipped version on macOS. 

Specifically here:
```bash
+ escaped_rhs='Kansas City'
+ file=../content/events/2024-kansas-city/speakers.md
+ [[ -w ../content/events/2024-kansas-city/speakers.md ]]
+ sed -i 's/CITY/Kansas City/' ../content/events/2024-kansas-city/speakers.md
sed: 1: "../content/events/2024- ...": invalid command code .
```

The script calls function `string_replace` which is being set in 
https://github.com/devopsdays/devopsdays-web/blob/07eb28b9f73b1f3400ec889eb9380f6dc0fd6f8f/utilities/common_code#L22-L41. 

The same file has some sed detection logic which is going unused.  
https://github.com/devopsdays/devopsdays-web/blob/07eb28b9f73b1f3400ec889eb9380f6dc0fd6f8f/utilities/common_code#L7-L18

Using the `sedcmd` function to execute the command makes the script function. 

```diff
diff --git a/utilities/common_code b/utilities/common_code
index 3903c0b46c..c8592c0b1d 100644
--- a/utilities/common_code
+++ b/utilities/common_code
@@ -33,7 +33,8 @@ string_replace() {

   if [[ -w "${file}" ]] ; then
     # sed -i'' should work for macos and linux equally.
-    sed -i'' "s/${escaped_lhs}/${escaped_rhs}/" "${file}"
+    # sed -i'' "s/${escaped_lhs}/${escaped_rhs}/" "${file}"
+    sedcmd "s/${escaped_lhs}/${escaped_rhs}/" "${file}"
   else
     echo "WARNING: ${file} not writeable"
     return 1
```

Output:

```bash
+ escaped_rhs='Kansas City'
+ file=../content/events/2024-kansas-city/speakers.md
+ [[ -w ../content/events/2024-kansas-city/speakers.md ]]
+ sedcmd 's/CITY/Kansas City/' ../content/events/2024-kansas-city/speakers.md
uname
++ uname
+ local osname=Darwin
which sed
++ which sed
+ local gnused=/usr/bin/sed
+ [[ Darwin == \L\i\n\u\x ]]
+ [[ Darwin == \D\a\r\w\i\n ]]
+ [[ /usr/bin/sed == \/\u\s\r\/\l\o\c\a\l\/\b\i\n\/\s\e\d ]]
+ sed -i '' 's/CITY/Kansas City/' ../content/events/2024-kansas-city/speakers.md

# Prompt for inputting speakers
while [ 1 ]
do
echo "Entering speakers; use CTRL+C to stop..."
```

Before I submit a PR, would be good to get context from @mattstratton and @rexroof, as this change was introduced in https://github.com/devopsdays/devopsdays-web/commit/3d92859b597aca91c1caeedd97636cd781a0e0d9.

**Comment by mattstratton** [comment]
I don't know what the change was for, so I can't weigh in, but probably safe to revert it?

**Comment by rexroof** [comment]
I added this general solution so that the script could support replacement strings that contained numerous special characters.  

it is possible it was only tested on linux.

**Comment by jerdog** [comment]
Yeah I am on MacOS so that could explain it @rexroof
