### ISSUE TITLE
Add field for CFP link to event data file format

### ISSUE THREAD

**Issue by mattstratton** [devopsdays/devopsdays-web#14]
Not sure if this should be data driven, or if events will just write this out in their "submit a CFP" page by hand

**Comment by mattstratton** [comment]
The advantage of this being data-driven is if an event wants to link this directly offsite, it can be handled in the data.

**Comment by mattstratton** [comment]
I'm moving this to Future Enhancements, since people do it by hand today anyway :)

**Comment by bridgetkromhout** [comment]
Since it's possible to override the "propose" link in the navbar with an offsite link to a cfp-management tool, I think this issue is probably resolved?

**Comment by mattstratton** [comment]
This was handled as @bridgetkromhout mentioned above.
