### ISSUE TITLE
codespaces wrong url in page preview

### ISSUE THREAD

**Issue by mihai-satmarean** [devopsdays/devopsdays-web#14049]
Hi, when trying to use codespaces for developing, any subpage we select from the rendered page, links to localhost:1313 instead of the unique generated url.

![image](https://github.com/devopsdays/devopsdays-web/assets/4729542/228f9921-e4a7-4b67-8429-27d85c86e858)

**Comment by mattstratton** [comment]
I noticed that today too! it's because of how the build command works; I need to see if there's a way to make a slightly different build in codespaces

**Comment by mattstratton** [comment]
okay so it really only happens when you click on a "city" page and i think it's because of the redirect (ie, /events/2024-chicago/ redirects to /events/2024-chicago/welcome and it is trying to shove the url in front of it)

i have a suspicion on something in the build to help this maybe?
