### ISSUE TITLE
Create offsite redirects for legacy presentation files

### ISSUE THREAD

**Issue by mattstratton** [devopsdays/devopsdays-web#142]
There are large PDF's and other large files that shouldn't be in the repo. We should get them hosted elsewhere and write some redirect logic in hugo for these legacy URL's.

https://github.com/jedi4ever/devopsdays-webby/tree/master/site/content/presentations

**Comment by bridgetkromhout** [comment]
Ugh, more of this just happened: https://github.com/jedi4ever/devopsdays-webby/pull/2733

Since those links are already there, we'll have to deal with it now. Let's not merge any more of this if we can help it, though.

**Comment by mattstratton** [comment]
I don't see why we need to bring them over. Its a new enough change that the original can be adjusted.

**Comment by mattstratton** [comment]
I'm leaving this issue open to that we can discuss and figure out a good going-forward suggestion/solution for files like prospectus, etc, that events need, but we can't keep in the code repo.

I invite any and all suggestions for solution :)

**Comment by mattstratton** [comment]
Closing this issue, since nothing was discussed. I think that the going-forward suggestion is for events to post their prospectus, etc, in a location such as Google Drive, etc.
