### ISSUE TITLE
[Dev] Add a way to differentiate builds to netlify

### ISSUE THREAD

**Issue by nimbinatus** [devopsdays/devopsdays-web#14246]
Since all previews look the same, it would be helpful to have a banner or something on the dev previews to identify which PR a Netlify preview is attached to.

**Comment by mattstratton** [comment]
besides it being in the url in the address bar?

what comes to mind as the "easiest" way is that you get the hostname and split it (the PR number will always be in the same place) and you could add something to the template which says like "if the hostname has xyz in it, show this thing" and you could make the thing include the PR number (which you can get from the hosname)and even string interpolate it to make the link to the PR

what you wouldn't be able to do is something like "show the title of this PR" but honestly this is the first time this has come up in many years of using deploy previews so I would be cautious about investing too much into this :)

(netlify has features to make this easier, but they all require being logged into netlify when you're in the preview and being a user who has rights to the netlify org, which has a cost)

**Comment by mattstratton** [comment]
i.e., these features are super helpful but it requires being a netlify user in the org 
https://docs.netlify.com/site-deploys/collaborate-on-deploys/

**Comment by mattstratton** [comment]
ah this is interesting:


> As a Team Owner, you can invite an unlimited number of people to give feedback on your site deploys in the official Reviewer Netlify role for free.

that said, it requires actually granted access to a person, so I think we wouldn't set thisup for everyone in devopsdays, but we could def give it to all the folks who have merge rights

**Comment by mattstratton** [comment]
looks like this:
<img width="880" alt="image" src="https://github.com/devopsdays/devopsdays-web/assets/1280666/7e2efc8d-fcd5-43de-8c8e-ed2e7d46d044">

**Comment by mattstratton** [comment]
I’ve enabled the Netlify Drawer for us which I think resolves this issue?
