### ISSUE TITLE
Dynamic Sponsor Category Display for DevOpsDays Website

### ISSUE THREAD

**Issue by SeifElbayomi** [devopsdays/devopsdays-web#14322]
**Problem:**
The current display of all sponsor categories on the DevOpsDays website, including those without sponsors, may deter potential sponsors due to perceived lack of participation.
Example:
![image](https://github.com/devopsdays/devopsdays-web/assets/59777501/9d6d148b-85fb-4dfa-aa88-0b9bfa2d5a19)

**Suggested Enhancement:**
Implement a backend feature that allows event organizers to choose whether to display empty sponsor categories. This will enable organizers to manage the visibility of sponsor categories dynamically based on their preference instead of commenting it out.
Example:
![image](https://github.com/devopsdays/devopsdays-web/assets/59777501/0b648fb0-8676-4cd0-81c5-dc38df1a00ed)

**Comment by SeifElbayomi** [comment]
Could a maintainer please add the `enhancement` label to this issue?

**Comment by mattstratton** [comment]
Fixed in #14323
