### ISSUE TITLE
Add sponsors to progam page

### ISSUE THREAD

**Issue by toshywoshy** [devopsdays/devopsdays-web#14359]
In another issue #14352 @mattstratton mentioned that not having the sponsors on the program page is a bug.
I think this is a feature, so I would like to get a discussion on this topic.
While adding the sponsors to the program page should be trivial, and I could implement it and create a PR.
I feel the current state of not having the sponsors and the discussion in issue #14352  iterate reasons why this bug should now be a feature.

**Comment by jyee** [comment]
Given that #14352 was closed and we will not be adding speakers' employer logos to the site, including the program page, I don't quite see how keeping regular sponsors off the program page would be a feature or provide any benefit. Can you explain what you see as the benefits of keeping sponsors off of the program page?

**Comment by toshywoshy** [comment]
Yes, so here are several reasons why I think the current state should become the default.
- Sponsors have not created a fuss about this till date that any of us have had to patch this sooner
- Until @mattstratton had brought this up as a bug, I thought this was intentional
- Not having any company logos on a community event seems more in line with our ethos and ethics
- Issue #14352 clearly states that we have never wanted and never want `sponsored` or commercial talks, therefor not having any sponsors or logos makes it obvious
- On several screen sizes, larger tablets and bigger, the program page would not have scroll bars
- The program page remains clean and consise

**Comment by mattstratton** [comment]
> Not having any company logos on a community event seems more in line with our ethos and ethics

Uh, it’s on every other single page in the site. 

I’ve also had sponsors ask me (for Chicago event) why they were not on that page. 

It’s clearly an oversight.
