### ISSUE TITLE
Update make_new_event.sh with new parameters for devopsdays-theme

### ISSUE THREAD

**Issue by mattstratton** [devopsdays/devopsdays-web#1495]
See https://github.com/devopsdays/devopsdays-theme/issues/49 for more details.

**Comment by mattstratton** [comment]
TODO: Matt needs to list what these parameters are.

**Comment by bridgetkromhout** [comment]
I updated this in the utilities dir over in the theme repo, and updating the utilities dir in this repo is on the release checklist.
