### ISSUE TITLE
Update sample-event with the proper starting files for devopsdays-theme

### ISSUE THREAD

**Issue by mattstratton** [devopsdays/devopsdays-web#1496]
See https://github.com/devopsdays/devopsdays-theme/issues/49 for details.

**Comment by mattstratton** [comment]
@mattstratton will confirm these files.

**Comment by mattstratton** [comment]
We no longer create a `welcome.md`; this file is replaced with `index.md` at the root of the event filesystem.

It does not require an alias.

Frontmatter should look like:
```
+++
Description = ""
Title = ""
Type = "welcome"
+++
```

An archetype has been created in the theme for this format.

**Comment by bridgetkromhout** [comment]
I updated this in the utilities dir over in the theme repo, and updating the utilities dir in this repo is on the release checklist.
