### ISSUE TITLE
Update the files in examples/speakers with any new fields for devopsdays-theme

### ISSUE THREAD

**Issue by mattstratton** [devopsdays/devopsdays-web#1497]
See https://github.com/devopsdays/devopsdays-theme/issues/49 for details

**Comment by mattstratton** [comment]
Depends on https://github.com/devopsdays/devopsdays-theme/issues/4

**Comment by bridgetkromhout** [comment]
I updated this in the utilities dir over in the theme repo, and updating the utilities dir in this repo is on the release checklist.
