### ISSUE TITLE
Update sample city file for devopsdays-theme

### ISSUE THREAD

**Issue by mattstratton** [devopsdays/devopsdays-web#1498]
Update `yyyy-city.yml` with any new fields, and remove any that are no longer needed

List of fields to add (this will be a work in progress)

- [ ] `event_logo_square: 'logo-square.jpg'`
- [ ] `event_logo: 'logo.jpg'`
- [ ] `event_twitter: 'devopsdays` (without the @ sign)
- [ ] `registration_open: 'false'`
- [ ] `registration_link: ""` (this is an optional link if they want off-site registration)
- [ ] `cfp_open: "false"`
- [ ] `cfp_link: ""`

**Comment by mattstratton** [comment]
@mattstratton will provide a list in this ticket of fields to change.

**Comment by mattstratton** [comment]
List of fields to add (this will be a work in progress)

- [ ] `homepage_image: 'logo-square.jpg'`

**Comment by bridgetkromhout** [comment]
I already removed fields like `friendly: ` that aren't used anymore. I added these ones in the utilities dir over in the theme repo, and updating the utilities dir in this repo is on the release checklist.
