### ISSUE TITLE
Add homepage logos for any upcoming events (for devopsdays-theme release)

### ISSUE THREAD

**Issue by mattstratton** [devopsdays/devopsdays-web#1499]
See https://github.com/devopsdays/devopsdays-theme/issues/49 for details

**Comment by mattstratton** [comment]
Actually, see https://github.com/devopsdays/devopsdays-theme/issues/81 for details.

**Comment by mattstratton** [comment]
Long story short - if they have a logo, crop it to 500px square and dump it into `static/events/YYYY-CITY/logo-square.png`

If they don't, grab it from twitter.

**Comment by bridgetkromhout** [comment]
* I've got reasonable-ish logos for almost all of them (Los Angeles doesn't have a twitter account or a logo). 
* I didn't try to make them all exactly 500px - does that matter?
* I _did_ change all of them to jpgs as discussed in https://github.com/devopsdays/devopsdays-theme/issues/150.
* Are we actually going to need to name the file in every event's yaml? Wouldn't a default with an override-if-desired make sense?

**Comment by bridgetkromhout** [comment]
@mattstratton Thanks for approving the merge - I forgot to name you in the questions above.

**Comment by mattstratton** [comment]
The file check is actually pretty annoying, code-wise, and I like people having the flexibility to name it whatever they want. I think if it's the default option in the generator, it's not that big of a deal.

**Comment by mattstratton** [comment]
I might start resizing smaller than 500 px square because that might be a little too big. But it should probably be fine.

**Comment by bridgetkromhout** [comment]
> The file check is actually pretty annoying, code-wise, and I like people having the flexibility to name it whatever they want. I think if it's the default option in the generator, it's not that big of a deal.

Okay. Then I think a to-do before this is :shipit: is for me to add the relevant line to every 2017 event's yaml.
