### ISSUE TITLE
Update blog posts with dates and summaries for devopsdays-theme

### ISSUE THREAD

**Issue by mattstratton** [devopsdays/devopsdays-web#1500]
See https://github.com/devopsdays/devopsdays-theme/issues/49 for details

**Comment by mattstratton** [comment]
Depends on https://github.com/devopsdays/devopsdays-theme/issues/54

**Comment by bridgetkromhout** [comment]
Is this a blocker for the v1.0 release?

**Comment by mattstratton** [comment]
Probably not, but if we don't do it now....

**Comment by bridgetkromhout** [comment]
...then the issue will remain and nag us? :)

**Comment by mattstratton** [comment]
Actually, now that i see this is a content related issue, it can stay here, but yes, I don't believe it is a blocker for 1.0. We'll find out through regression testing I guess.

**Comment by bridgetkromhout** [comment]
I'm taking these items off the checklist:
 Add PublishDate to frontmatter of all blog post files (should match to what is in Date right now) (note - this doesn't quite work properly; will need to do some more research)
 Add Description to frontmatter of all blog post files (the summary of the post)

**Comment by mattstratton** [comment]
I think the main reason to add `Description` was for social sharing, etc, and that's not likely to be an issue for the older posts. Summaries are looking fine. I'm going to close this one.
