### ISSUE TITLE
investigate different future-event sort order on local vs server

### ISSUE THREAD

**Issue by bridgetkromhout** [devopsdays/devopsdays-web#1546]
Both on 0.16 and then when I upgraded to 0.18 locally, the future-event sort order is correct - while on devopsdays.org it's seemingly arbitrary.

![screen shot 2016-12-23 at 8 16 57 pm](https://cloud.githubusercontent.com/assets/2104453/21464739/eb70edf8-c94c-11e6-8f55-8df90032b95a.png)

**Comment by mattstratton** [comment]
FWIW, this doesn't seem to occur on the v3.0 theme, so it might not be something we need to deal with.

**Comment by bridgetkromhout** [comment]
I think this is related to weirdness with maps (and thus doesn't happen all the time). Because I haven't seen it on the new theme, I'm fine with resolving it for now.
