### ISSUE TITLE
Update docs with info about allowed files 

### ISSUE THREAD

**Issue by mattstratton** [devopsdays/devopsdays-web#158]

**Comment by phrawzty** [comment]
Allowed files such as? (Conversely, *verboten* files such as?)

**Comment by phrawzty** [comment]
Seriously though, what sort of general statements can we make here?

* File size limit?
* List of acceptable file types?
* "Common sense" guidelines?

**Comment by mattstratton** [comment]
I would say we should set something like this:

- Do not upload presentations, artifacts from your event, etc. Either link to the preso on Speakerdeck/Slideshare from the presenter, or even better, create a Speakerdeck account for your event and put the presos there.
- Small, web images are fine (logos, etc). If you have high-resolution versions of your logo to share with others, please do not host them on the devopsdays-web repo.
- It is acceptable to add in a single PDF for your sponsor prospectus if you desire (in `/static/events/YYYY-city`), but please keep this file under 3 MB. It is better to host it on Google Drive or something similar, and then link to it from your site.
