### ISSUE TITLE
Reuse sponsor's generator

### ISSUE THREAD

**Issue by VitMosin** [devopsdays/devopsdays-web#1610]
I need to place on sponsors page the same layout as sponsors in the right part.
I find file devopsdays-web\themes\devopsdays-responsive\layouts\partials\sponsors.html that generate markup.
And i find use of it as {{ partial "sponsors.html" . }}
How could i reuse the same markup in sponsors.md file?

**Comment by mattstratton** [comment]
You cannot use partials in the markdown files. Generally speaking, most of this is going to change dramatically in the redesign, so I'm going to close this one as wontfix.
