### ISSUE TITLE
[minor] numbered lists in markdown docs

### ISSUE THREAD

**Issue by phrawzty** [devopsdays/devopsdays-web#165]
Right now the `README.md` has a numbered list which renders properly when viewed in GitHub, but when viewed as text contains a series of non-sequential numbers.  This drives me nuts.

Options:

1. Using *just* the number 1 over and over, and relying on GitHub to render it properly.
  1. Confusing if it's not rendered properly (or viewed as text).
1. "Enforcing" manual ordering as a pre-requisite to merging.
  1. Definitely works but is irritating to maintain.
1. Using bullet lists.
  1. Easy to maintain, consistent behaviour - but it's not numbers.

**Comment by mattstratton** [comment]
I vote for option one as it is "correct" Markdown.

**Comment by bridgetkromhout** [comment]
I'm addressing this in https://github.com/devopsdays/devopsdays-web/pull/175.

**Comment by phrawzty** [comment]
Alright, so, number one number one number one it is!
