### ISSUE TITLE
investigate the "name" key for possible combination with "friendly"

### ISSUE THREAD

**Issue by bridgetkromhout** [devopsdays/devopsdays-web#169]
In https://github.com/devopsdays/devopsdays-web/blob/master/yyyy-city.yml#L1-L4, `name` and `friendly` are the same except `friendly` has a hyphen. Can we just have a `name` key with a hyphen, since that's what we call the event? Or do we use `name` in some other essential way that precludes a hyphen? sometimes double quotes help with hugo's hyphen-hate.

**Comment by mattstratton** [comment]
I just tried changing the "name" field in chicago to 2016-chicago, and it seemed to work. I think we can fix that. I believe this backdates from a previous version of hugo when the hypens didn't work.

**Comment by bridgetkromhout** [comment]
I don't think finishing this is a blocker for the migration.

**Comment by mattstratton** [comment]
I am pretty sure I caught everything that uses the `friendly` parameter; all that remains is for @bridgetkromhout to update the sample data file to remove it and also the new event script to remove it.

**Comment by mattstratton** [comment]
Assigning @bridgetkromhout because I really want to close this out, and she has two small items to complete as mentioned above.

or just tell me to do it my darn self.

**Comment by bridgetkromhout** [comment]
Ah sorry, didn't notice you'd updated this when I was super in the middle of confs. I'm in the middle of a work trip right now. Will have to wait until end of week.

**Comment by mattstratton** [comment]
Depends on #860

**Comment by bridgetkromhout** [comment]
Fixed in https://github.com/devopsdays/devopsdays-web/pull/912.
