### ISSUE TITLE
Determine what to do with the old blog posts

### ISSUE THREAD

**Issue by mattstratton** [devopsdays/devopsdays-web#17]

**Comment by m1keil** [comment]
since we don't have too many blog posts, I assumed we just going to adjust these to frontmatter and that's it.

**Comment by mattstratton** [comment]
Well my question was more is there a need for all the structure around them (rss feed when there hasn't been a new blog in 2 years)? But the level of effort should me super minor.

**Comment by mattstratton** [comment]
I think that there is no reason to not keep the blog stuff around, and maybe with it being easier to create content, there will be more posts :) Since I created #49 and #50, I am going to close this issue.
