### ISSUE TITLE
Add speaker images

### ISSUE THREAD

**Issue by Roderick-Jonsson** [devopsdays/devopsdays-web#1741]
When using the add_speakers.sh I don't get asked for the speaker image. Can someone help add the speaker images to the zurich 2017 page #1740

**Comment by bridgetkromhout** [comment]
Hi, @Roderick-Jonsson - when I wrote that script I didn't handle asking for the image. That's a good feature to add, but for now what you need to do is replace the default one-pixel image it creates. Let me know if you need help with that? You can see the default image in your pull request (https://github.com/devopsdays/devopsdays-web/pull/1742/files), so you can hopefully see what the path is where you need to put your images.

**Comment by Roderick-Jonsson** [comment]
@bridgetkromhout Tried this and it didn't work. But I realised now that safari was caching. Had to use private mode, this made safari also load the images. Will push the changes.

**Comment by bridgetkromhout** [comment]
Hi, @Roderick-Jonsson - since you've successfully added your images, I'm going to resolve this issue. Thanks!
