### ISSUE TITLE
Add new config.toml parameters for new theme

### ISSUE THREAD

**Issue by mattstratton** [devopsdays/devopsdays-web#1780]
So far, the only one I know of is the 'weburl'.

It should be set to:

```
weburl = "https://www.devopsdays.org"
```
This will NOT affect local builds; this is used only for creating outside metadata.

Also, this needs to be changed to be all lowercase, as such:

`  pathseperator = "/"`

**Comment by mattstratton** [comment]
Note that `weburl` needs to be set under params

**Comment by bridgetkromhout** [comment]
I was focused on the typo in `pathseperator` (the spelling is `separator`) but now I see what you're saying about all-lowercase; https://github.com/devopsdays/devopsdays-web/pull/1790 is wrong but I'm not positive what's right (and unsure how best to test).

**Comment by mattstratton** [comment]
TBH it seems to work without it. I'm really not sure. It might have been fixed in go/Hugo?

**Comment by bridgetkromhout** [comment]
Okay, I'm marking this as something to check after the cutover.

**Comment by bridgetkromhout** [comment]
> It needs to be in all lower case with the incorrect spelling as that is called in a LOT of partials.

Is the typo in Hugo itself, or is it all us? If it's us, `sed` is my friend. ;)

**Comment by mattstratton** [comment]
it's all us. Feel free to fix it.

What I discovered is that when I did it with mixed-case (the way it exists in the current `config.toml` it didn't work in the new theme. But let me prove that out.

**Comment by bridgetkromhout** [comment]
K, I'll let you determine if we need it at all. Thanks!

**Comment by mattstratton** [comment]
I've noticed a couple other small things - the menu needs to be added (since it's driven by `config.toml` and we also gitignore the config file (probably wise), so I'll need to make these changes in a different manner, but nbd.
