### ISSUE TITLE
contacts all squashed together in IE11 on new theme

### ISSUE THREAD

**Issue by MikeRosTX** [devopsdays/devopsdays-web#1809]
List of contacts are all squashed together in IE 11, but look just fine in Chrome.  Have not yet tested newer versions of IE. See attachment
![squashed_contacts](https://cloud.githubusercontent.com/assets/11631454/23233284/09b88130-f914-11e6-8224-390b48de4a52.jpg)
.

**Comment by mattstratton** [comment]
Actually, can you make the issues with the new theme at https://github.com/devopsdays/devopsdays-theme?

**Comment by MikeRosTX** [comment]
Closing. Moved to https://github.com/devopsdays/devopsdays-theme/issues/300
