### ISSUE TITLE
remove unneeded welcome link from datafiles

### ISSUE THREAD

**Issue by bridgetkromhout** [devopsdays/devopsdays-web#1829]
We're going to need to remove "welcome" as a menu item from all events (because otherwise we have a home icon linking to the event name, and then another icon linking to the /welcome page). This is what the problem looks like - note the `+` which I'm hovering over to see the Welcome page:

![screen shot 2017-02-25 at 3 25 27 pm](https://cloud.githubusercontent.com/assets/2104453/23334913/b28c5668-fb6e-11e6-829c-33be825582e9.png)

I don't want to leave a PR unmerged for two weeks, so here's a reminder to me how to generate such a change:

_Bridgets-MacBook-Air:devopsdays-web bridget$ for foo in $(ls -1 data/events/); do sed -i '' -e ':a' -e 'N' -e '$!ba' -e 's/  - name: welcome\n//' data/events/$foo;done_

This removes the `  - name: welcome` field from any line where it exists, without leaving a tell-tale blank line.

I'm putting this on the "do after cutover" checklist in https://github.com/devopsdays/devopsdays-theme/issues/49.

This will resolve the issue I noticed and mentioned when working on https://github.com/devopsdays/devopsdays-web/issues/1819.

**Comment by mattstratton** [comment]
Ouch. This didn't work - it ends up with an extra indent on the following element, which breaks everything. Example:

```
nav_elements: # List of pages you want to show up in the navigation of your page.
   - name: program
  - name: location
  - name: contact
```

**Comment by mattstratton** [comment]
and just for fun, I made sure to run that in bash and not zsh, and it causes the same issue.

**Comment by bridgetkromhout** [comment]
I'm vexed that I didn't prepare a PR at the time when I'm positive this worked as expected. Ah, well. I went with the less-elegant-but-still-works solution produced by:

_Bridgets-MacBook-Air:devopsdays-web bridget$ for foo in $(ls -1 data/events/); do sed -i '' -e ':a' -e 'N' -e '$!ba' -e 's/ - name: welcome//' data/events/$foo;done_
