### ISSUE TITLE
Past events overlapping Future Dates

### ISSUE THREAD

**Issue by nathenharvey** [devopsdays/devopsdays-web#1833]
The formatting on /events is such that you cannot click on all of the future events.  In the attached screen shot, Ohio is the last future event you can click on.  Neither St. Louis nor Sao Paulo are clickable.  The "Past" events seem to be overlapping the Future Dates.

![devopsdays_events](https://cloud.githubusercontent.com/assets/16093/23346663/39579e22-fc6a-11e6-9670-fafc82290af0.png)

**Comment by bridgetkromhout** [comment]
Thanks. As you probably saw https://dev.devopsdays.org/events is very different, but solving this in the short term before the cutover is of course worthwhile!
