### ISSUE TITLE
Move speaking page to subdirectory

### ISSUE THREAD

**Issue by mattstratton** [devopsdays/devopsdays-web#1847]
Two small changes need to be made to the `content/pages/speaking.md` file.

It needs to be moved to `content/speaking/speaking.md`

Also, we need to add this to the permalinks section of  `config.toml`:

`  speaking = "/:filename/"`

**Comment by bridgetkromhout** [comment]
> It needs to be moved to `content/speaking/speaking.md`

Two questions:
1. Can/should it be `content/speaking/index.md`?
2. Is the URL going to change?

**Comment by mattstratton** [comment]
The URL doesn't change because of that permalink change in the `config.toml`

We don't want to change the name of the file because of how the permalink is constructed; notice that it uses the `:filename`

**Comment by mattstratton** [comment]
This change was already made in `devopsdays-theme` so you can see how it works there :)

**Comment by mattstratton** [comment]
I think that I can make this change in advance without any badness happening. I'll try it out.
