### ISSUE TITLE
[ZRH-2017] Working on final program ~do-not-merge

### ISSUE THREAD

**Issue by drbokko** [devopsdays/devopsdays-web#1902]
This issue act as a collector for all the modifications related tothe Zurich even program and speaker list.

**Comment by drbokko** [comment]
Rod fixing typos #1901

**Comment by Roderick-Jonsson** [comment]
@drbokko How do I assign the pull request to this issue? #1927

**Comment by Roderick-Jonsson** [comment]
@drbokko Ok saw you message. Should have done it over the commit message

**Comment by drbokko** [comment]
yes :D

**Comment by drbokko** [comment]
by adding hash and the issue number (#1902) in the commit
