### ISSUE TITLE
update events and speaking page types/filesystem layout

### ISSUE THREAD

**Issue by mattstratton** [devopsdays/devopsdays-web#1947]
In the old theme, the page type was called `cfp`. In the new theme, it is called `speaking`. This page needs to be modified when we release the new theme.

**Comment by bridgetkromhout** [comment]
Bridgets-MacBook-Air:content bridget$ git diff
diff --git a/content/page/events.md b/content/page/events.md
index dbb3ad2..5f28f8d 100644
--- a/content/page/events.md
+++ b/content/page/events.md
@@ -1,8 +1,8 @@
 +++
 date = "2015-11-29T00:00:00-06:00"
 title = "devopsdays events"
-type = "events-list"
-aliases = ["/calendar", "/events/calendar", "/devops-calendar", "/presentations"]
+type = "events"
+aliases = ["/calendar", "/events/calendar", "/devops-calendar", "/presentations", "/past"]
 
 +++
 
diff --git a/content/speaking/speaking.md b/content/speaking/speaking.md
index 8041234..7f0a600 100644
--- a/content/speaking/speaking.md
+++ b/content/speaking/speaking.md
@@ -4,7 +4,7 @@ Description = ""
 Tags = []
 Date = "2017-01-31T13:04:25-05:00"
 Title = "Speaking at devopsdays"
-type = "cfp"
+type = "speaking"
 
 +++
 
Bridgets-MacBook-Air:content bridget$
