### ISSUE TITLE
Event no longer listed on home page

### ISSUE THREAD

**Issue by nathenharvey** [devopsdays/devopsdays-web#1949]
The end date is set to today but the event is no longer listed on the home page.

```
name: "2017-baltimore"
year: "2017"
city: "Baltimore"
event_twitter: "devopsdaysbmore"
friendly: "2017-baltimore"

startdate:  2017-03-07
enddate:  2017-03-08
```

**Comment by nathenharvey** [comment]
Seems that if the start data has passed, the event no longer appears on the home page.  I fixed this today for Baltimore by setting the startdate to today.

**Comment by mattstratton** [comment]
@nathenharvey can we close this issue then?

**Comment by bridgetkromhout** [comment]
Given my comment in https://github.com/devopsdays/devopsdays-web/issues/1951#issuecomment-285082997 I'm pretty sure we can close this now that we're on the new theme.
