### ISSUE TITLE
Add ability to disable sponsor sidebar

### ISSUE THREAD

**Issue by mattstratton** [devopsdays/devopsdays-web#195]
Some pages don't need the sidebar, and some events might not want it at all.

There are two ways we can handle this:

1) Make a parameter in the event that says "sponsors: false" and then have the sidebar look for that status, defaulting to `true`

2) Add a frontmatter parameter (optional), with `sidebar: false` which will then suppress the sidebar (this is how it works with webby right now)

Thoughts?

**Comment by bridgetkromhout** [comment]
I think making the sidebar frontmatter-specific and therefore configurable per-page would be more flexible than making it an event-wide toggle. Reason: sometimes an event will embed a wide element like a cfp page or a registration page, so for example in Minneapolis we turn the sponsor page off for registration but nothing else.

**Comment by bridgetkromhout** [comment]
If we change the sponsor sidebar to a sponsor footer, i think it would make sense still to implement this as a per-page frontmatter exclude. It will default to off, and so by default the sponsor footer will appear. See https://github.com/devopsdays/devopsdays-web/issues/295.

**Comment by mattstratton** [comment]
I don't think that this should go in the Responsive Design milestone as it's not a blocker for that. I'll change that..

**Comment by bridgetkromhout** [comment]
Right now if an event doesn't want the sponsor sidebar, they simply add nothing about sponsors to their yaml datafile. See https://github.com/devopsdays/devopsdays-web/pull/926/commits/783d314affaab26a3d43ab5b9ede5b7ef17d0e45 to see it in action.

The event-wide toggle seems fine at this point given that we now have a responsive site that moves the sidebar to the bottom if the viewport side dictates such.

I don't think this issue needs to stay open. The only remaining part might be the part where the column that _had_ sponsors is now empty. That's an overall layout thing ("handle the case of no sponsor sidebar responsively") and I don't know if it needs its own issue or needs to be on a checklist somewhere.

**Comment by mattstratton** [comment]
I think this can be closed for the current site.
