### ISSUE TITLE
Make sponsor border links optional

### ISSUE THREAD

**Issue by bchess** [devopsdays/devopsdays-web#197]
Issue #88 has a lot of back and forth about whether there should be borders around sponsor logos. The default of "yes, border" is fine, though I'd propose that we make it optionally hidden.

**Comment by mattstratton** [comment]
Do you propose that this be done on a per-sponsor basis or a per-event basis?

Either way it's quite doable; just depends on where the toggle is set.

The problem I see with a "per sponsor" basis is that it will look super weird for some to have it and some to not.

WRT to the per-event, what is the use case for having it look different? Just want to understand it so I can come up with the right solution.

**Comment by bchess** [comment]
Per event IMHO. I agree I think it'd look weird if it was per sponsor.

I don't know that I can point to a particular "use case" for it being
borderless. Just my personal opinion that the page looks a bit nicer
without them :)

**Comment by bridgetkromhout** [comment]
I dislike the borders in general but think they are needed in the column display to make it not look too cluttered. This goes away if we switch to a sponsor footer (https://github.com/devopsdays/devopsdays-web/issues/295).

**Comment by bridgetkromhout** [comment]
I'm back with some bikeshedding!

Assertion: with the new responsive redesign live and in production, the borders are unneeded and kinda hideous, and we could turn them off by default and have it look nicer. And sure, if someone loves them, allow an event to opt back in.

Pros? Cons?

**Comment by mattstratton** [comment]
We're no longer using borders in the new theme. See for ongoing work on how it's being handled.

https://github.com/devopsdays/devopsdays-theme/issues/137
