### ISSUE TITLE
Old sponsor logos which were not 200x200

### ISSUE THREAD

**Issue by markcornick** [devopsdays/devopsdays-web#203]
How strict is the requirement to have 200x200 logos? DC has several, including many new sponsors for 2016, that are 100x100. Not anticipating we'd need to reformat these, I haven't kept the originals which we scaled down to 100x100. Suggestions?

**Comment by mattstratton** [comment]
I wouldn't bother changing any - they'll work fine at 100x100, they just won't have retina-fancy.

**Comment by markcornick** [comment]
Fair nuff - thanks!
