### ISSUE TITLE
Regression on ability to control sponsor ship links

### ISSUE THREAD

**Issue by yvovandoorn** [devopsdays/devopsdays-web#2034]
It looks like the new layout has regressed the fix in #93. 

New behavior is that it always shows to become a sponsor, regardless of max set. Example is on https://www.devopsdays.org/events/2017-amsterdam where we have a max of 1 set for the evening slot (which under the old layout didn't show "Become a sponsor") but now does.

**Comment by mattstratton** [comment]
Gotcha. I'll close this ticket and redirect it to https://github.com/devopsdays/devopsdays-theme/issues/387
