### ISSUE TITLE
allow multiple sponsors to use the same logo

### ISSUE THREAD

**Issue by phrawzty** [devopsdays/devopsdays-web#2063]
There are cases where sponsors want to have different URLs for each event they're sponsoring (see OpsGenie). Currently, this means that the same logo file has to exist over and over for each instance. It would be handy if there were a way to specify a logo file in the sponsor profile.

I'm not sure if this is a theme thing or not. Sorry if this is in the wrong repo!

**Comment by mattstratton** [comment]
I think this actually probably relates to the "allow url override per sponsor"? We are tracking this in prodpad and it's on the roadmap.

It's summarized as this:

```
URL override to to sponsors in city data file

This would give the opportunity to override the URL in the city data file for a sponsor, to allow an event-specific URL for that sponsor.

IDEA 055 - Add URL override for sponsors in city data file
```

Does this sound about right?

**Comment by phrawzty** [comment]
Yes, that sounds like it'd fit the bill. Guess we can close this issue.

Sorry, I'm not clear at all on which issues go where and why. :/

**Comment by mattstratton** [comment]
Here's the issue where I'm tracking it:

https://github.com/devopsdays/devopsdays-theme/issues/398

Basically, no issues should be opened in this repo, unless they are directly related to content :)
