### ISSUE TITLE
Should we change the default layout of the event homepage?

### ISSUE THREAD

**Issue by mattstratton** [devopsdays/devopsdays-web#2134]
Currently, the example file for the default page of a site looks a little like this:

![Old Chicago](https://i.imgur.com/KzDigL2.png)

I've changed Chicago to look like this:

![New Chicago](https://i.imgur.com/CjCPsIf.png)

We could easily change the generated example `index.md` file to have the logo offset to the right like that (btw, in mobile, it pushes the logo above the details). Thoughts?

**Comment by MikeRosTX** [comment]
IMO having a smaller logo to the left like Seattle's view to me is more appeasing to the eye.

![seattle](https://cloud.githubusercontent.com/assets/11631454/24363805/7e8f1448-12d6-11e7-8f40-f8fb8c8d15e8.jpg)

**Comment by mattstratton** [comment]
Well, they added content that isn't part of our default content, which is what makes it a more opinionated design. Now, if the event is making use of either the "Description" frontmatter or the "description" field in the datafile, we can generate using that stuff.

**Comment by kmugrage** [comment]
We did it that way for Seattle for a couple reasons.... 
- The custom content was created before the new theme
- I'm not a big fan of content in a section that looks like a header. I didn't notice the description was there until I read this rfc. 

All of that said, the lower amount of whitespace vs the Chicago example can also be attributed to the horizontal layout of the Seattle logo.

**Comment by MikeRosTX** [comment]
Still like the logo to the side.  ;)
We did it that way for Dallas.

**Comment by bridgetkromhout** [comment]
I like the logo to the left (like Seattle's) a bit better but don't really have a strong opinion.

**Comment by mattstratton** [comment]
This issue really doesn't need to exist. I'm closing it. If you disagree, feel free to let me know :)
