### ISSUE TITLE
consider supporting sponsor links with no image

### ISSUE THREAD

**Issue by bridgetkromhout** [devopsdays/devopsdays-web#216]
This used to work:

![screen shot 2016-05-05 at 6 22 47 am](https://cloud.githubusercontent.com/assets/2104453/15042471/d1175912-1289-11e6-95a1-5bc6a6a0fb18.png)

This is what happens now:

![screen shot 2016-05-05 at 6 23 12 am](https://cloud.githubusercontent.com/assets/2104453/15042477/dec2b340-1289-11e6-9f08-4e114db82337.png)

If we decide this is a use case we support, this needs correcting.

**Comment by mattstratton** [comment]
I think it's totally doable with some additional data (maybe an optional value in the sponsor.yml file to set `noimage`.

**Comment by mattstratton** [comment]
@bridgetkromhout - I think we have gone quite some time without a request for this, so the feature request can go away?

**Comment by bridgetkromhout** [comment]
Yeah, I don't think this is even desirable at this point.
