### ISSUE TITLE
consider allowing different sizes of sponsor images

### ISSUE THREAD

**Issue by bridgetkromhout** [devopsdays/devopsdays-web#227]
![screen shot 2016-05-05 at 2 10 21 pm](https://cloud.githubusercontent.com/assets/2104453/15054062/42023386-12cb-11e6-883d-164ea9add164.png)

Noticed this when migrating London. Do we want to have different sizes of sponsor images on the website as a feature? (if not, we should be explicit that that shouldn't be in a prospectus).

**Comment by mattstratton** [comment]
This really should go into the whole redesign approach - in the current sidebar it seems challenging. I think that the look and feel of the soonsor display definitely needs a revamp in the new UX.

**Comment by phrawzty** [comment]
Agree entirely with @mattstratton above; the current "legacy" layout makes this ugly, but from a user story perspective it's not an unreasonable scenario.

**Comment by bridgetkromhout** [comment]
Most conferences put the sponsors in a footer at the bottom of the page. If we were to do that, we'd avoid a lot of the logistical problems with the sidebar, so I'd imagine that should be on the table as a choice.

**Comment by bridgetkromhout** [comment]
Note for @nathenharvey - this current limitation is making the icon chosen for your venue sponsor look not-so-great. Might make sense to take the one from their twitter account instead?

**Comment by mattstratton** [comment]
Closing this in favor of https://github.com/devopsdays/devopsdays-theme/issues/137
