### ISSUE TITLE
Refactor Future sidebar

### ISSUE THREAD

**Issue by christianherro** [devopsdays/devopsdays-web#233]
The Upcoming Events box above the map and the Future Events sidebar do not line up for events that do not have dates attached to them yet.

For example:  http://devopsdays.github.io/events/2016-madison/ does not have dates attached, and shows up in the grey box above the map, but not in the Future Events sidebar.

![image](https://cloud.githubusercontent.com/assets/10146948/15058516/4e015b0a-12e2-11e6-9025-91908fb18177.png)
vs. 
![image](https://cloud.githubusercontent.com/assets/10146948/15058524/578b0806-12e2-11e6-9ae4-1e7115a2c1f6.png)

**Comment by mattstratton** [comment]
@bridgetkromhout - I assume that events without dates should NOT show up in the grey bar? But we do need to add the "TBD" events to the blue footer.

**Comment by bridgetkromhout** [comment]
> I assume that events without dates should NOT show up in the grey bar?

Correct.

**Comment by bridgetkromhout** [comment]
Thanks, @mattstratton! Now _one_ event with a blank start date will appear in the Future section, but not two. To reproduce:

$ grep "^startdate: #" data/events/*
data/events/2016-madison.yml:startdate: # The start date of your event. Leave blank if you don't have a venue reserved yet.
data/events/2016-ohio.yml:startdate: # The start date of your event, in YYYY-MM-DD format. Leave blank if you don't have a date yet.
Bridgets-MacBook-Air:devopsdays-web bridget$ 


![screen shot 2016-05-06 at 12 25 14 pm](https://cloud.githubusercontent.com/assets/2104453/15080855/9b643a5e-1385-11e6-9751-725113c4cdb2.png)

Then remove Ohio, and Madison shows up:

Bridgets-MacBook-Air:devopsdays-web bridget$ rm data/events/2016-ohio.yml 
Bridgets-MacBook-Air:devopsdays-web bridget$ 

![screen shot 2016-05-06 at 12 25 53 pm](https://cloud.githubusercontent.com/assets/2104453/15080873/b32f7fb8-1385-11e6-8023-51feeb269c9a.png)

**Comment by bridgetkromhout** [comment]
Even with Kiel's year corrected, this also affects Kiel/Seattle. So, more broadly, it's the "same dates can't both show up" issue (now appearing in Future).

**Comment by mattstratton** [comment]
Gah. I might have to refactor that entire code - future is a little easier to handle for it because it's built to account for multi-year but we don't need that just yet. 

The problem is that I didn't write the code for that initially and I don't completely understand it. I don't know if @m1keil has any ideas?

**Comment by mattstratton** [comment]
I'm assuming this is still open for "tech debt" reasons?

**Comment by mattstratton** [comment]
Never mind. I see the comments in the PR. Yeah, it's super sloppy but it will do for the moment.

**Comment by mattstratton** [comment]
This is probably being handled with #405, which makes everything cleaner.
