### ISSUE TITLE
investigate/fix in-page anchors

### ISSUE THREAD

**Issue by bridgetkromhout** [devopsdays/devopsdays-web#237]
The Kiel program relies on anchors:

![screen shot 2016-05-05 at 9 44 16 pm](https://cloud.githubusercontent.com/assets/2104453/15062881/8a202e22-130a-11e6-8663-cc88a9072c30.png)

They lead to the front page, not the id-ed location in the same page.

If we cut over as-is, we break their program.

**Comment by bridgetkromhout** [comment]
Hi,  @connor21 -

If you need those anchors, we will fix it before migration. You may not need them if you're okay with a data-driven program like the one Minneapolis is using - see http://devopsdays.github.io/events/2016-minneapolis/program/. Please let me know if you're okay with switching so your speaker and talk info is data-driven. We could still display it like it is now; it would just be stored differently.

**Comment by connor21** [comment]
Hi @bridgetkromhout;
certainly I would be ok with the Minneapolis approach but...
When I was looking around how to add the abstracts to the program I found
http://www.devopsdays.org/events/2015-siliconvalley/program/
and coppied what they did. 
If I change it now, I suppose all the links in social media pointing to the program details we be invalidated.
Any idea?
Cheers,
Maik

**Comment by mattstratton** [comment]
The pages in Hugo can have frontmatter added to specify the URL they should also reply to (see how your `welcome.md` is configured) so you could move to the new setup but have the pages still answer on the old URLs. 

It's also probably easier to just fix the anchors and i think I can do that pretty easily.
