### ISSUE TITLE
Migrate 2015 and 2016 events to legacy.devopsdays.org

### ISSUE THREAD

**Issue by mattstratton** [devopsdays/devopsdays-web#2402]
This will shrink down the number of files that need to be processed by the build and other items, which should make everything better.

**Comment by mattstratton** [comment]
This does merit some discussion before just "doing" it.

**Comment by bridgetkromhout** [comment]
Right now, files served by `legacy` have their URLs rewritten. I don't like the idea of doing that any more than we _must_. So based on my current understanding (which may be wrong) I am fairly opposed to this idea.

**Comment by mattstratton** [comment]
The URL's are rewritten, but the canonical URL in the header remains WWW, which is what google looks at for search juice. There is not an SEO impact to making this change. Unless you are speaking from a cosmetic perspective, in which case we could always make it ww2.devopsdays.org insetead of "legacy" :)

**Comment by mattstratton** [comment]
Thinking on this some more, here are a couple thoughts:

1) We can move older events "generated" files into the `static/events/2016-chicago/` (for example) directory. Hugo doesn't process files in static, they are just copied. That will help with some portions.

2) Doing the above has the negative impact of making it hard to add stuff to an older event (like slides, etc).

3) If we did something like this, we would have to figure out how to get gulp to not try to process those generated files in some way so it doesn't try to re-minify them, etc.

**Comment by bridgetkromhout** [comment]
> We can move older events "generated" files into the static/events/2016-chicago/ (for example) directory. Hugo doesn't process files in static, they are just copied. That will help with some portions.

This would be acceptable to me from a cosmetic/confusion POV if we did it for 2015 and/or "anything over a year old" - as I doubt we'd be adding many slides, etc, after that amount of time.

**Comment by mattstratton** [comment]
I am pretty sure we can move the output of the old files into the `static` directory, and then rewrite some of the gulp tasks to ignore that directory for processing. This will definitely help on build times.

**Comment by mattstratton** [comment]
Further investigation is telling me that we won't be able to do the exclusions, since the paths to the static directories are going to be somewhat matching; I might be able to be figure out how to right a proper glob to tell it to ignore stuff that is 2015, etc. This will be tricky.

**Comment by mattstratton** [comment]
This was fixed in #2747 

We didn't move them to legacy; they've just been migrated to the static directory.
