### ISSUE TITLE
thoughtworks for SLC - products? services?

### ISSUE THREAD

**Issue by bridgetkromhout** [devopsdays/devopsdays-web#241]
Hi, @kmugrage @davidasnider - The SLC webby site is using a thoughtworks logo nobody else is:

![image](https://cloud.githubusercontent.com/assets/2104453/15071984/5cbe175a-1355-11e6-8e33-6a8097ea41bd.png)

Is that one supposed to be Thoughtworks Products or Thoughtworks Services? Currently the image looks like the CD products but the link goes to the main thoughtworks site.

For now I've guessed and set to the thoughtworks products. Here's where to change it if desired:
https://github.com/devopsdays/devopsdays-web/blob/master/data/events/2016-saltlakecity.yml#L61

Change to thoughtworks-services if that's what you wanted.

(If this is a third, different thoughtworks division sponsoring and that colorful logo is correct, please advise.)

**Comment by kmugrage** [comment]
You've guessed correctly. It's supposed to be ThoughtWorks Products and that is an old logo. 

Thanks!

**Comment by bridgetkromhout** [comment]
Thanks!

**Comment by davidasnider** [comment]
So, do I need to do anything?  Also, is the thought works logo on the hugo site correct?  I used an existing one.  Sorry for the mistake. :(

**Comment by kmugrage** [comment]
Nope, nothing to be done.

On Fri, May 6, 2016 at 8:00 AM, David Snider <notifications@github.com>
wrote:

> So, do I need to do anything? Also, is the thought works logo on the hugo
> site correct? I used an existing one. Sorry for the mistake. :(
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/devopsdays/devopsdays-web/issues/241#issuecomment-217466373>
>



-- 
Ken Mugrage - ThoughtWorkskmugrage@thoughtworks.com+1(425) 835-3056@kmugrage

**Comment by davidasnider** [comment]
Yay!  My favorite kind of issue.
