### ISSUE TITLE
past events with conflicting dates don't all display on events page

### ISSUE THREAD

**Issue by mattstratton** [devopsdays/devopsdays-web#246]

**Comment by bridgetkromhout** [comment]
This bug still exists with the current http://www.devopsdays.org/events/ page.

**Comment by mattstratton** [comment]
Do we have a way to repro this?

**Comment by bridgetkromhout** [comment]
To test if the problem still exists: undo this: https://github.com/devopsdays/devopsdays-web/commit/d80dfdac79a505423a809c22e924ed94ecd954f6

**Comment by mattstratton** [comment]
Yup. Still happens.

**Comment by bridgetkromhout** [comment]
(In my local test, this change makes Kiel disappear from the page.)

**Comment by bridgetkromhout** [comment]
Closing this in favor of the similar issue in new theme.
