### ISSUE TITLE
Broken links on CFP RSS feed

### ISSUE THREAD

**Issue by xaprb** [devopsdays/devopsdays-web#2460]
I subscribe to the CFPs RSS feed and I've been noticing broken links, viz:

    https://www.devopsdays.org/speaking/events/%!(EXTRA%20string=2017-ohio)

Even if I "fix" that, I'm getting

    https://www.devopsdays.org/speaking/events/2017-ohio

But I need

    https://www.devopsdays.org/events/2017-ohio/propose/

**Comment by bridgetkromhout** [comment]
Hi, Baron -

Thanks so much for letting us know!

The difficulty with being opinionated about a "propose" link is that some cities eschew that link entirely in favor of an offsite link to a CFP-management site. So we'll look into this issue with the RSS feed (can you give us the specific link you're using for the RSS feed, in case we have an issue there?), but the links you see on https://www.devopsdays.org/speaking/ (to the city's landing page, not the propose page if they have one) are probably what we're going to be able to offer until we build further logic.

**Comment by mattstratton** [comment]
This is somewhat solveable; I'd like to see an issue on devopsdays-web repo so i can track/test there.

**Comment by xaprb** [comment]
I'll follow up in that issue.
