### ISSUE TITLE
different behavior of "year" key for future and past events on events page

### ISSUE THREAD

**Issue by mattstratton** [devopsdays/devopsdays-web#247]
If the event is "past" then it needs to be in quotes, if it's "current" it needs to not be in quotes. This is a problem :)

**Comment by bridgetkromhout** [comment]
I thought this bug applied to the actual year:

`year: "YYYY"` has to be in quotes for current. 
`year: YYYY` can't be in quotes for past.

not to the status:

`status: "current"` or `status "past"` both work.

**Comment by mattstratton** [comment]
oh, whoops.

**Comment by bridgetkromhout** [comment]
This bug still exists with the current http://www.devopsdays.org/events/ page.

**Comment by mattstratton** [comment]
This is fixed by #885 

The year field isn't used by the events page anymore.
