### ISSUE TITLE
Date in speaker files needs to be wrapped in quotes

### ISSUE THREAD

**Issue by mattstratton** [devopsdays/devopsdays-web#2559]
The script needs to be updated - the latest hugo is picky about the dates being wrapped in quotes for frontmatter.

**Comment by bridgetkromhout** [comment]
Looks like the script has a vestigial datestamp that the template no longer uses. I've submitted a correction. Please let me know if this doesn't clear things up from your POV, and if so, what else you'd like to see.

**Comment by mattstratton** [comment]
Apparently in the latest version they changed the TOML parser, so it's more strict on a few things...it only seems to have affected Zurich's speakers.

**Comment by bridgetkromhout** [comment]
Okay, I _think_ we are good here - I'll leave this up to you as to whether it's resolved.

**Comment by mattstratton** [comment]
Seems okay to me, so I'll close it.
