### ISSUE TITLE
add an enhancement to show "become the FIRST x sponsor" 

### ISSUE THREAD

**Issue by mattstratton** [devopsdays/devopsdays-web#26]
Currently, the code will display nothing for a sponsor type if there are no sponsors of that type. On many existing sites, if there is a "Gold" level, for example, with no gold sponsors, a link will be displayed that says "become the first Gold sponsor"

I think this can be handled by slightly changing the formatting of the sponsor data in the event data file, but it might require a little more cleverness in the parsing on the event template to determine which things to show.

**Comment by mattstratton** [comment]
Based on PR #38, this will now show "become an X sponsor" under every sponsor type, It also assumes a /sponsor link under the event page for this link to work. This is not perfect yet, but it's getting there.

**Comment by m1keil** [comment]
I think it's the way to go. 
If you have unused sponsor_level, show it with a link to sponsors page.
We can do even an extra step and create some nice attributes under sponsor_level:
`link_text` - store the string that will be showed if no sponsors exists
`show_link` - boolean value to turn link on/off (if off, sponsor won't be showed)

**Comment by mattstratton** [comment]
I think that for now, this is fixed. We should add an enhancement to show "become the FIRST x sponsor" when the sponsor is empty, but I'm going to change this to an enhancement as it's not on the critical path.

**Comment by bridgetkromhout** [comment]
Related to https://github.com/devopsdays/devopsdays-web/issues/93.

**Comment by bridgetkromhout** [comment]
Having it say "first" (when, duh, none is listed) seems entirely unnecessary to me. It's also sorta deceptive/possibly inaccurate because just because no sponsor of type X is on the site yet doesn't mean one isn't in talks.

**Comment by mattstratton** [comment]
Yeah, "become the FIRST" whatever thing is a holdover from webby. 

Nobody seems to have been made super sad about not having this, so I question the need for it.

**Comment by bridgetkromhout** [comment]
I'm gonna say "doesn't matter" and close this.
