### ISSUE TITLE
Migrate events from 2015 and before

### ISSUE THREAD

**Issue by mattstratton** [devopsdays/devopsdays-web#29]
Migrate data from all past events (2015 and before) to new system. 

Here is an attempt of a list of all the events needed to migrate, so we can track. 

- [x] 2009
 - [x] Ghent 2009
- [x] 2010
 - [x] Sydney 2010
 - [x] Mountain View 2010
 - [x] Hamburg 2010
 - [x] Sao Paulo 2010
- [x] 2011
 - [x] Boston 2011
 - [x] Mountain View 2011
 - [x] Melbourne 2011
 - [x] Bangalore 2011
 - [x] Göteborg 2011
 - [x] Manila 2011
- [x] 2012
 - [x] Austin 2012
 - [x] Tokyo 2012
 - [x] Delhi 2012
 - [x] Mountain View 2012
 - [x] Rome 2012
 - [x] New York 2012
- [ ] 2013
 - [ ] New Zealand 2013
 - [ ] London 2013
 - [ ] Paris 2013
 - [ ] Austin 2013
 - [ ] Berlin 2013
 - [x] Amsterdam 2013
 - [ ] Silicon Valley 2013
 - [ ] Downunder 2013
 - [x] Bangalore 2013
 - [ ] London Autumn 2013
 - [ ] Barcelona 2013
 - [ ] Vancouver 2013
 - [ ] Portland 2013
 - [ ] New York 2013
 - [ ] Atlanta 2013
 - [ ] Tel Aviv 2013
 - [ ] Tokyo 2013
- [ ] 2014
 - [x] Nairobi 2014
 - [ ] Ljubljana 2014
 - [ ] Austin 2014
 - [ ] Pittsburgh 2014
 - [ ] Amsterdam 2014
 - [ ] Silicon Valley 2014
 - [x] Minneapolis 2014
 - [ ] Brisbane 2014
 - [ ] Boston 2014
 - [ ] Toronto 2014
 - [ ] New York 2014
 - [ ] Warsaw 2014
 - [ ] Chicago 2014
 - [ ] Berlin 2014
 - [ ] Belgium 2014
 - [ ] Helsinki 2014
 - [ ] Vancouver 2014
 - [ ] Tel Aviv 2014
 - [ ] Bangalore 2014
- [ ] 2015
 - [ ] Ljubljana 2015
 - [ ] Paris 2015
 - [ ] Denver 2015
 - [ ] New York 2015
 - [x] Austin 2015
 - [ ] Toronto 2015
 - [ ] Washington, DC 2015
 - [x] Amsterdam 2015
 - [x] Minneapolis 2015
 - [ ] Melbourne 2015
 - [ ] Pittsburgh 2015
 - [ ] Chicago 2015
 - [x] Bangalore 2015
 - [x] Boston 2015
 - [ ] Tel Aviv 2015
 - [ ] Singapore 2015
 - [x] Berlin 2015
 - [ ] Charlotte 2015
 - [ ] Silicon Valley 2015
 - [ ] Detroit 2015
 - [x] Ohio 2015
 - [ ] Warsaw 2015

**Comment by mattstratton** [comment]
@jedi4ever if you could offer some insight into the traffic that the older sites get, it will help me make a design decision on how the migration occurs.

Right now, there are a couple different ways to handle it:

1. Create new events (in the new structure) for all the old events. This involves creating a data file for each event, mapping sponsors to the sponsor structure, and updating every file in each "old" event folder to use the new templating language. I would estimate the level of effort _per event_ to be 1-2 hours of VERY boring work.
2. Copy the existing generated HTML files from webby for each event to the corresponding file patths in hugo. Hugo will ignore any .html files, so they would not be evaluated. This is by far the easiest way to do it (the whole thing will probably take an hour or two, as opposed to 1-2 hours per event). The downside is that the legacy/old events become truly static. If/when we change the site design, these old URL's (which will always still work, with the same URL's as today) will just always have the "classic" DevOpsDays look to them. 

The larger issue with the second option that I thought of (and just now realized doesn't apply) is the footer that lists all the events. That footer only exists on the homepage as it it is; the single event pages do not use it.

That being said, I see no reason to not go with option 1. Thoughts?

**Comment by jedi4ever** [comment]
@mattstratton I'm good with option 1 - as long as the URLs stay the same we're good.
On a side note we are currently using disquss for feedback - do you include that? or we don't bother

**Comment by bridgetkromhout** [comment]
> On a side note we are currently using disquss for feedback - do you include that? or we don't bother

We're going to leave off the whole "upload your proposals ahead of time" thing. It's under-used and most places are using an external CFP processing site now.

**Comment by mattstratton** [comment]
Two notes -

1) My comment was incorrect. Option 2 is the proper option. There is no reason to do all the extra heavy lifting.

2) Disqus can easily be accommodated if needed (it's baked into hugo) but as @bridgetkromhout said, it's not heavily used so we aren't going to bring it along for the ride. It would be easy to add in the future if need be.

**Comment by jedi4ever** [comment]
@mattstratton me too,  I meant indeed option2 is ok

**Comment by bridgetkromhout** [comment]
As I understand it, after Saturday April 16th @mattstratton will migrate whatever's in the old repo, with consideration for https://github.com/devopsdays/devopsdays-web/issues/104, https://github.com/devopsdays/devopsdays-web/issues/102, and _maybe_ https://github.com/devopsdays/devopsdays-web/issues/142?

At that point we'll stop merging PRs on the old site for anything 2015 and before.

**Comment by bridgetkromhout** [comment]
This continues to be in progress.

**Comment by bridgetkromhout** [comment]
@mattstratton, please look over https://github.com/devopsdays/devopsdays-web/issues/292 and determine if this issue can now be closed - thanks!

**Comment by mattstratton** [comment]
I think we can close this one.
