### ISSUE TITLE
improve the presentation of legacy events

### ISSUE THREAD

**Issue by bridgetkromhout** [devopsdays/devopsdays-web#292]
I went with a fast-and-hackish way of getting ~51 event migrations finished in an afternoon; I imported the old index.html pages into welcome.md via the files I added in https://github.com/devopsdays/devopsdays-web/pull/290 used thusly:
```
for foo in $(cat events-to-migrate);do echo $foo | ./migrate-events.sh;done
```

I deleted the files for the ones that didn't happen: https://github.com/devopsdays/devopsdays-web/commit/e40512c963a1e60d98963cb11c36041753f3d140

I then viewed the start dates from the webby directory:
```
$ pwd
/Users/bridget/github/devopsdays-webby/site/content/events
Bridgets-MacBook-Air:events bridget$ more */_event_date_start.txt 
```

and manually edited the start and end dates into the yaml:
```
for foo in $(cat events-to-migrate);do vi data/events/$foo.yml ;done
```

Yes, that kinda sucked. No, there was no reasonable way to get that data from the inconsistently-set-up date files.

. Known side effects:

* Lots of broken images (their paths are mostly relative and need to be absolute)
* without the "OLD" (or equivalent text), the imported text showed as blank. (That could be `sed`ded out to something less visible.)
* Currently a bunch of cruft shows:

![screen shot 2016-05-07 at 10 22 07 pm](https://cloud.githubusercontent.com/assets/2104453/15095849/2dccacf6-14a2-11e6-93bc-532eaf60109f.png)

I would be fine with any additional migration option that preserves as much history as possible while de-duplicating sponsor images that make the repo too big.

I regard this as temporary so we don't have to have too many old events offline for any amount of time. I think real migration/de-duplication/binary-delete of a given event's extraneous logos would still be ideal.

**Comment by mattstratton** [comment]
This will be handled by the redirect setup from #854

**Comment by mattstratton** [comment]
This should be resolved; there may be some DNS cache issues for the next few days, but all the legacy stuff shoudl be displaying properly now.
