### ISSUE TITLE
redesign how sponsors are displayed

### ISSUE THREAD

**Issue by bridgetkromhout** [devopsdays/devopsdays-web#295]
We have a number of open issues around the sponsor logos. This meta-issue will help us plan that work. I just read through all the sponsor-related issues, and there's one obvious choice that helps almost every issue.

I assert that the sponsors belong at the bottom of each page, not on the right-hand side. This would allow a lot more flexibility in the responsiveness of the pages without constraining us to make room for a column. I'm picturing something pretty much exactly like what Velocity does: http://conferences.oreilly.com/velocity/devops-web-performance-ca (scroll down).

Here are all the issues around how we display sponsors:

https://github.com/devopsdays/devopsdays-web/issues/227 - consider allowing different sizes of sponsor images
https://github.com/devopsdays/devopsdays-web/issues/216 - consider supporting sponsor links with no image
https://github.com/devopsdays/devopsdays-web/issues/197 - Make sponsor border links optional
https://github.com/devopsdays/devopsdays-web/issues/195 - Add ability to disable sponsor sidebar
https://github.com/devopsdays/devopsdays-web/issues/108 - Sponsor logos are two wide instead of three
https://github.com/devopsdays/devopsdays-web/issues/87 - Sponsor sidebar looks weird on iOS
https://github.com/devopsdays/devopsdays-web/issues/93 - Ability to control "Become a <level> sponsor" links
https://github.com/devopsdays/devopsdays-web/issues/26 - add an enhancement to show "become the FIRST x sponsor"
 
Discussion welcome.

**Comment by mattstratton** [comment]
Bear in mind with a responsive design the sponsors could display "stacked" (not a sidebar) on narrower view ports and at a really wide viewport they could be on the right as usual.

**Comment by mattstratton** [comment]
That being said, putting the sponsors at the bottom makes for a slightly easier bit of front end coding :)

**Comment by WhatsChrisDoing** [comment]
I think we need to move ahead with this. The sponsor logos are wrapping to the bottom of the page on most mobile devices in any case.

**Comment by mattstratton** [comment]
I'm leery about jumping into "redesign"efforts piecemeal. There needs to be an overall approach. Which we should be working towards as soon as possible.

**Comment by WhatsChrisDoing** [comment]
I am too but the status quo where the logos move around is creating too many "where's my logo" questions. Can we do this incrementally? Should be engaging a designer and a front-end dev to give the site a modern makeover now that it's on a more manageable platform? I ask this being neither a designer and a front-end dev so I'm not sure how I can help.

**Comment by mattstratton** [comment]
I am in the process of getting s designer for the redesign. If this is causing a massive issue and is breaking the site then we as a group should discuss it. 

Apologies if it was not clear from other tickets/comments, but we ARE getting a designer to reboot the look and feel of the overall site. It won't be something done in within the next 24 hours or anything though.

**Comment by WhatsChrisDoing** [comment]
Great. I haven't been tracking all of the issues.

The logos wrapping to the bottom of the page on any narrow display (issue #87 is the closest). World ending no. People asking questions yes. Mostly because they know they saw them once and then didn't see them later. They don't consider the device or window size change.

**Comment by bridgetkromhout** [comment]
A lot of detail in https://github.com/devopsdays/devopsdays-web/pull/355, which I'm closing for now (unmerged).

**Comment by mattstratton** [comment]
I believe this has been resolved with the recent responsive merge.

**Comment by bridgetkromhout** [comment]
> I believe this has been resolved with the recent responsive merge.

Agreed. Thanks!
