### ISSUE TITLE
Need a new design for list of past and current events

### ISSUE THREAD

**Issue by mattstratton** [devopsdays/devopsdays-web#33]
The current large footer is not going to scale well once we have another year :)

Also, it's tricky to update

**Comment by m1keil** [comment]
Ah.. one of these good issues to have :-)

I would love seeing a dynamic list over there:
Showing all future events, X amount of past events and everything else hidden as "Show More" link. Clicking "Show More" should expend that box to fit all past events.
Alternative - just point to All Events page (new page).

BTW, there one annoying thing there, all past events contains the year. So it goes:
```
2015
-------
XYZ 2015
QWE 2015
ZXC 2015
.... 2015...
```

**Comment by m1keil** [comment]
what about something like this:
![localhost 1313 2015-12-04 22-52-14](https://cloud.githubusercontent.com/assets/1589008/11601120/ba26776a-9ad9-11e5-9109-3f0ad5f0becc.png)

not perfect yet (need to work on the padding and maybe alternate colours), but from the perspective of the data layout, might be good

**Comment by m1keil** [comment]
Another possibility is just showing X number of last events (ordered by date) without splitting to column per year.

**Comment by mattstratton** [comment]
Looking for feedback from @bridgetkromhout on whether this is something we should be tackling prior to the cutover or if we just lump it into redesign, since it seems to be working okay now?

**Comment by bridgetkromhout** [comment]
While the footer definitely needs redesign, I don't think footer redesign is blocking the cutover. In my mind, it's a future enhancement.

**Comment by mattstratton** [comment]
Fixed in #421
