### ISSUE TITLE
add event location address as a short code

### ISSUE THREAD

**Issue by digitaldrummerj** [devopsdays/devopsdays-web#3350]
the location_address is stored in the yml data file for an event but there is not a corresponding short code for it.

**Comment by mattstratton** [comment]
Can you open an issue for this on [devopsdays/devopsdays-theme](https://github.com/devopsdays/devopsdays-theme)? That's where changes to the theme should be :)

**Comment by digitaldrummerj** [comment]
opened https://github.com/devopsdays/devopsdays-theme/issues/599
