### ISSUE TITLE
improve speakers page

### ISSUE THREAD

**Issue by mattstratton** [devopsdays/devopsdays-web#338]
This should be a page that works for any event that will list the bios of any speakers found in `/data/speakers/yyyy/city` for that event.

**Comment by bridgetkromhout** [comment]
I merged in a hackish solution for this. Do feel free to make it suck less!

**Comment by bridgetkromhout** [comment]
Currently doesn't distinguish between Ignite and Talks and Keynotes - that would be a useful feature.

**Comment by bridgetkromhout** [comment]
Current issues with the speakers include https://github.com/devopsdays/devopsdays-web/issues/365.

**Comment by bridgetkromhout** [comment]
> Currently doesn't distinguish between Ignite and Talks and Keynotes - that would be a useful feature.

Note to @yvovandoorn - I only built a layout for "talk" so far, not "workshop" or "ignite".

**Comment by mattstratton** [comment]
This is a feature of [devopsdays-theme](https://github.com/devopsdays/devopsdays-theme) so we can close this one out.
