### ISSUE TITLE
Need a way to delimit event names in main header with pipes

### ISSUE THREAD

**Issue by mattstratton** [devopsdays/devopsdays-web#34]
Have to figure out how to filter through the range of current events to determine the last one in the range, so it won't output the pipe

**Comment by m1keil** [comment]
sorry, not sure I understood this one.
Are we talking about "Warsaw - Kiel -" this?

**Comment by m1keil** [comment]
OK, I assume it is. I've looked into it. 
It seems like hugo right now really likes to work with lists but having a really bad time with maps.
In case of the data directory, everything is being read into map[filename][content]. 
Sadly hugo's `where` function only works with arrays right now, and I cannot quickly filter out the "current" events into a list, then use the same approach that they use [here](http://gohugo.io/templates/functions/#advanced:904d9cf85d985550c869e6d9741448cc) (basically working with array's length). We can convert events to a single event.yaml to solve this but I don't like it...

Need to chat with them, maybe there's another creative solution with this.

**Comment by m1keil** [comment]
See this branch for very ugly workaround

**Comment by mattstratton** [comment]
I agree about not making the events data munged into one giant file - that causes all sorts of merge hell possibility, not to mention that the data file itself will become unwieldy. Looking at the code in https://github.com/devopsdays/devopsdays-web/tree/issue-34, it seems like a workable fix (perfection is the enemy of good, and using Scratch seems to be a common workaround in Hugo).

**Comment by mattstratton** [comment]
Created #54 for refactor work in future enhancements, but this works for now, IMHO.

**Comment by m1keil** [comment]
Agreed. I will check if there's cleaner way to handle it, since similar issues probably will arise.
