### ISSUE TITLE
add support for videos to talk pages

### ISSUE THREAD

**Issue by mattstratton** [devopsdays/devopsdays-web#361]
This will keep things consistent. Should support both YouTube and Vimeo

**Comment by bridgetkromhout** [comment]
Why do we want this? I ask because currently I just copypasta the embed stuff that youtube/vimeo/whatever provides. Seems like this would make more work for the exhausted organizers, not less...?

**Comment by mattstratton** [comment]
Because we can wrap it with cleaner html that is responsive :)

The copy-pasta thing potentially causes consistency of look issues. This probably should be pushed to 3.0 when we will talk about how videos can look responsive and consistent in the UX.

**Comment by mattstratton** [comment]
OK, so first of all, we don't need to make this shortcode, since they already exist in hugo. Neat.

That being said, it might be useful to add some frontmatter to the talks pages that includes an optional youtube ID, which would then display if it is set. That makes it easier to update. 

Additionally, we need to create an archetype for the "talks" page type because then it can prepopulate with stuff.

I'm renaming this issue because it's changed in what it does.

**Comment by mattstratton** [comment]
Ok I looked into this some more - nobody is using `hugo new` to create the talks, because they use the script. So instead of updating an archetype, we can modify the example talk to have an empty video parameter, so you can just add it later when you have it. We just need to add it to the `utilities/examples/speaker-full-name.md` file

**Comment by mattstratton** [comment]
This is a feature of the new [devopsdays-theme](https://github.com/devopsdays/devopsdays-theme)
