### ISSUE TITLE
fix default speaker image

### ISSUE THREAD

**Issue by bridgetkromhout** [devopsdays/devopsdays-web#365]
Right now, the speaker image here:

 https://github.com/devopsdays/devopsdays-web/blob/master/themes/devopsdays-legacy/layouts/speakers/single.html#L16 

and here: 

 https://github.com/devopsdays/devopsdays-web/blob/master/themes/devopsdays-legacy/layouts/talk/single.html#L25 

is a broken link if it doesn't exist. I worked around that with a 1px by 1px blank image for the Minneapolis speakers with no picture at the time: https://github.com/devopsdays/devopsdays-web/blob/8c0ceb4b3d39173ab81af86dfa84cc8ac30f07e7/static/events/2016-minneapolis/speakers/allan-espinosa.png

@yvovandoorn will need to use the same workaround for Amsterdam for now, but we should fix this. (I just didn't take the time to figure out how to add a conditional/default there.)

**Comment by mattstratton** [comment]
Just commenting on a way to fix this:

- [ ] Create a default speaker image (if there isn't one provided). Ideally this could be just using font-awesome's [user](http://fontawesome.io/icon/user/) icon
- [ ] Put in some logic when it's displaying the user image to use that icon if the file doesn't exist.

**Comment by bridgetkromhout** [comment]
My fix for now is having the speaker addition script add a 1px by 1px image for any new speakers. Your suggestion is better, though.

**Comment by bridgetkromhout** [comment]
Given the lack of info on https://discuss.gohugo.io/t/check-if-a-file-exists/1838 and the messiness of https://discuss.gohugo.io/t/how-to-check-whether-a-file-exists-in-the-folder/3325 and the jankiness of https://gohugo.io/extras/localfiles/, I have zero inclination to build a "does a file exist" checker; unless we want to set a image-exists attribute in the speaker yaml, this seems non-trivial.

I consider my workaround in https://github.com/devopsdays/devopsdays-web/blob/master/utilities/add_speakers.sh#L58 to be less annoying than working on this. Willing to entertain counter-arguments.

**Comment by mattstratton** [comment]
Totally fine with that, but I'd prefer a "shadow user" image of the proper size of a speaker headshot vs a blank image. 

Although I just realized that means a ton of duplicated images. Sigh. Never mind.

**Comment by mattstratton** [comment]
Although the image will be replaced...

**Comment by mattstratton** [comment]
If I wanted to be super clever, we could have that still be the small pixel image but redirect it at the server side, so we don't need a copy of every shadow user image, etc.

**Comment by bridgetkromhout** [comment]
It's hard for shadow images to look ungendered unless they're non-human-looking (like Twitter's egg - but let's avoid that, due to negative connotations). I'm not super convinced we need something less pleasing-looking that emptiness, unless it were to serve a specific purpose like being clickable.

Basically at this point I think we'd need design input to make it look better than font-awesome's generic user. (Also, is this still a bug? Maybe, if someone doesn't use the script and doesn't realize they need to set the default.)

**Comment by mattstratton** [comment]
I think this can be closed, due to the script and stuff.
