### ISSUE TITLE
Program links not clickable on Mobile Safari

### ISSUE THREAD

**Issue by yvovandoorn** [devopsdays/devopsdays-web#369]
I just tried on MSP 2016 and AMS 2016 and the program URLs are not clickable from Mobile Safari (iOS 9.3.1). 

Reproduce steps:
1. Open up http://www.devopsdays.org/events/2016-minneapolis/program/ on your iPhone
2. Try your hardest to select the link.

**Comment by mattstratton** [comment]
Well that sure isn't delightful. I'll see what I can do. 

Also this is why I want to kill all the existing CSS mess. It's as mush job

**Comment by bridgetkromhout** [comment]
Maddening. Thanks for the catch. This is one we'll definitely have to fix asap.

**Comment by mattstratton** [comment]
I will fix this tonight unless someone gets to it first :)

**Comment by bridgetkromhout** [comment]
I'm at OSCON so have almost no bandwidth to learn the first thing about CSS. :)

**Comment by mattstratton** [comment]
OK, so I hacked on this for quite some time. I think the issue has to do with mixing bootstrap stuff with regular `<span>` hacks.

The responsive fixes will make this better. My hope is to have the responsive work (with the existing design) done by Saturday, so it might be better to spend the time on that then fixing this one.

**Comment by bridgetkromhout** [comment]
The problem also manifests in Chrome on the desktop if it's narrow enough, and the responsive redesign fixes that.

**Comment by mattstratton** [comment]
This is fixed
