### ISSUE TITLE
hugoserver.sh

### ISSUE THREAD

**Issue by joshmccall221** [devopsdays/devopsdays-web#3839]
Running in vm or another server causes errors `<machine-ip>:1313`: 
```
GET http://localhost:1313/css/site.css net::ERR_CONNECTION_REFUSED
(index):27 GET http://localhost:1313/css/googlemaps.css net::ERR_CONNECTION_REFUSED
(index):59 GET http://localhost:1313/img/devopsdays-brain.png net::ERR_CONNECTION_REFUSED
```
Only works on `localhost:1313` or `127.0.0.1:1313`.

**Comment by joshmccall221** [comment]
@dragon788

**Comment by bridgetkromhout** [comment]
Hi, @joshmccall221 - yes, as you can see on https://github.com/devopsdays/devopsdays-web/blob/master/hugoserver.sh#L12 this has a port number on localhost hardcoded into this convenience script. We'd be happy to review a pull request if you or @dragon788 had interest in generalizing that script.

**Comment by mattstratton** [comment]
I agree with @bridgetkromhout - we can take a PR but I’m not going to be able to prioritize a fix myself right now.
