### ISSUE TITLE
Archive old stuff since last year

### ISSUE THREAD

**Issue by martinliu** [devopsdays/devopsdays-web#3892]
Summary: Old stuff should not be carry over to new year, too much page takes long time to build.
Exception: Exclude everything from last year. Only build and test pages created within this year.

Here is one of my build testing locally:

```
martin@mbp:source/devopsdays-web ‹add-shanghai-shenzhen›$ hugo server
Started building sites ...

Built site for language en:
0 draft content
0 future content
0 expired content
2193 regular pages created
10 other pages created
45 non-page files copied
3 paginator pages created
total in 30259 ms
Watching for changes in /Users/martin/source/devopsdays-web/{data,content,static,themes}
Serving pages from memory
Web Server is available at http://localhost:1313/ (bind address 127.0.0.1)
Press Ctrl+C to stop

```
I have new Mac Book Pro with 16GB RAM.

It took **_30259_** ms ; it ok for me; but more then 10 times longer compare to  my own Hugo site(I do have 1/10 pages).

Any way, do you guys think we can optimize build time here?

Best Regards,
Martin Liu

**Comment by bridgetkromhout** [comment]
Hi, @martinliu - @mattstratton has done some work with this (moving previous years to be static). We've found there is a tradeoff because quite often, it takes cities a while to get their videos posted, etc. He can add more thoughts on this. Thanks!

**Comment by mattstratton** [comment]
What Bridget said - we try to move sites after the current year because events keep updating.
