### ISSUE TITLE
Cairo2018- DevOps

### ISSUE THREAD

**Issue by SherineFaragAllah** [devopsdays/devopsdays-web#4037]
Cairo2018- DevOpsDays ... coming soon

**Comment by SherineFaragAllah** [comment]
Our organization is currently forming a team to organize Cairo2018- DevOpsDays.
More details will be communicated soon.

**Comment by bridgetkromhout** [comment]
Hi - you need to have your kickoff call with the core team before you can send a pull request. Please wait for that to be scheduled first. Thanks!
