### ISSUE TITLE
Change to use common docker image

### ISSUE THREAD

**Issue by mattstratton** [devopsdays/devopsdays-web#4127]
There is an updated docker setup that we won't have to maintain here - https://hub.docker.com/r/jojomi/hugo/

We should update our docs and scripts (and travis build) to use this instead.

**Comment by espoelstra** [comment]
This should probably include updating the CONTRIBUTING.md to recommend Docker instead of installing Hugo directly.

**Comment by mattstratton** [comment]
I don’t recommend that. It’s an option but not the recommended solution. We provide it for people who want it, but frankly I don’t support it myself.
