### ISSUE TITLE
determine content for global footer

### ISSUE THREAD

**Issue by mattstratton** [devopsdays/devopsdays-web#420]
In the new(ish) design, the event list footer is removed and instead a small blue strip footer is in its place. In my current build, it simply says "Copyright 2009-2016 devopsdays". 

What content would be useful in the footer?

Please use this issue to suggest/bikeshed on this content.

**Comment by mattstratton** [comment]
FYI, the change is in #405

**Comment by bridgetkromhout** [comment]
Can we leave aside the bikeshedding over copyright and not have that in the scope of this discussion? I'm trying to keep this simple.

**Comment by mattstratton** [comment]
OK, fair enough. I only brought it up in case the content included was "copyright blah blah blah", which is what i put in that footer since I couldn't think of anything else. I'll remove the copyright bit out of the issue :)

**Comment by bridgetkromhout** [comment]
If the footer is intended for all pages, repeating the general contact info stuff from the top is nice. having a past events choice somewhere is better than putting them in a footer.

**Comment by mattstratton** [comment]
The nav is global as well, so the past events (see #405 for the MVP screenshot) is available on all pages.

I think repeating some of the fancy nav stuff, but in text link format (contact, sponsor, blah blah blah) is a nice thing to possible include.

**Comment by mattstratton** [comment]
Some interesting ideas in this link here https://www.orbitmedia.com/blog/website-footer-design-best-practices/

A lot of them don't apply, and they also show examples of much larger footers than we would use, but I did find it interesting that they recommend putting the social links in the footer instead of the header. Maybe we move the three social links (email, twitter, linkedin) to the footer similar to this:


![](https://www.orbitmedia.com/blog/wp-content/uploads/2015/11/social.png)

**Comment by bridgetkromhout** [comment]
> repeating some of the fancy nav stuff, but in text link format
also more accessible?

**Comment by bridgetkromhout** [comment]
> Maybe we move the three social links (email, twitter, linkedin) to the footer similar to this:

I like that idea. Anything to declutter.

**Comment by bridgetkromhout** [comment]
I don't like the dropdown fwiw. those are hard to use if your trackpad is jittery, you're on mobile, your hands shake, etc. I'd like a nav to past events and have that be a page with sections and scrolling.

**Comment by mattstratton** [comment]
Can we raccoon the dropdown discussion to #405? I'm okay with discussing it and I'm not sold on the dropdown either, but if we're going to talk about what the events page should look like, let's do it there.

**Comment by bridgetkromhout** [comment]
Kk.

**Comment by bridgetkromhout** [comment]
I'm happy with the footer as-is and am fine with this being resolved if @mattstratton agrees.
