### ISSUE TITLE
add social graph data

### ISSUE THREAD

**Issue by mattstratton** [devopsdays/devopsdays-web#422]
If the "description" frontmatter is set on a page, use that for description. Else, use a generic devopsdays description.

Use the title from the frontmatter.

If in an event and the event has a logo, use the logo for the social image, else, use the devopsdays logo.

**Comment by bridgetkromhout** [comment]
This feels like a future enhancement to me. Do we still consider it part of a specific milestone that I feel like we've now passed?

**Comment by mattstratton** [comment]
Yeah it's an enhancement not redesign related.

**Comment by mattstratton** [comment]
I'm going to put this into the Hugo 0.16 milestone as we have to touch that code anyway.

**Comment by mattstratton** [comment]
The first two items actually already work. This is the one that needs fixing:

`If in an event and the event has a logo, use the logo for the social image, else, use the devopsdays logo.`

**Comment by mattstratton** [comment]
I'm taking this out of the `Infrastructure Updates` milestone since it's not related.

**Comment by mattstratton** [comment]
We use [hugo-snippets](https://github.com/nozzle/hugo-snippets) for these partials, so maybe take a look at that to understand where to start...

**Comment by mattstratton** [comment]
And lots of bikeshedding [here](https://discuss.gohugo.io/t/hugo-seo-social-partials/353/36)

**Comment by mattstratton** [comment]
This is being handled in [devopsdays-theme](https://github.com/devopsdays/devopsdays-theme/issues/128) so this issue can be closed.
