### ISSUE TITLE
make a visual break between devopsdays slogan and page title on small viewports

### ISSUE THREAD

**Issue by mattstratton** [devopsdays/devopsdays-web#423]
It looks super weird on a small viewport when the nav menu has been collapsed. Should add something between the slogan and the page title. See screenshot for example. 
<img width="692" alt="bootstrap_101_template" src="https://cloud.githubusercontent.com/assets/1280666/15445925/a22a1d92-1ed2-11e6-9624-cbc5bcbd683c.png">

**Comment by bridgetkromhout** [comment]
This one feels like a future enhancement to me, too. Do we still consider it part of the responsive design milestone?

**Comment by mattstratton** [comment]
It's a nice to have. Make it future enhancement.

**Comment by bridgetkromhout** [comment]
This doesn't actually bug me, but how about solving it with italics or a different font or something for the "conference that brings" tagline? Or just bundle this into the "redesign" wishlist.

**Comment by mattstratton** [comment]
I'd say this can wait for redesign. It's clearly not that important to me or I would have fixed it by now :)

**Comment by mattstratton** [comment]
Closing wontfix because of the whole new design.
