### ISSUE TITLE
update program.md files for responsive design

### ISSUE THREAD

**Issue by mattstratton** [devopsdays/devopsdays-web#424]
The existing `program.md` in the current sites, as well as the example site, need to be refactored to match the layout as specified in the `/content/events/2016-chicago/program.md` file in [mattstratton/redesign](/devopsdays/devopsdays-web/tree/mattstratton/redesign) branch.

**Comment by mattstratton** [comment]
Amsterdam was addressed by 6a2b489426d51b587b6a795bababba9bb895be46

**Comment by bridgetkromhout** [comment]
Make sure these are done: 

- [ ] Istanbul
- [ ] Washington, DC
- [ ] Salt Lake City
- [ ] Silicon Valley
- [ ] Amsterdam
- [ ] Porto Alegre
- [ ] Minneapolis
- [ ] Portland
- [ ] Baltimore
- [ ] Boston
- [ ] Chicago
- [ ] Oslo
- [ ] Dallas
- [ ] New York
- [ ] Raleigh
- [ ] Boise
- [ ] Singapore
- [ ] Detroit
- [ ] Kansas City
- [ ] Philadelphia
- [ ] Ghent
- [ ] Bangalore
- [ ] Nashville
- [ ] Ohio 
- [ ] Cape Town 
- [ ] Madison 
- [ ] New Zealand

**Comment by bridgetkromhout** [comment]
Also: updated sample program: https://github.com/devopsdays/devopsdays-web/commit/2eb89fecd75377651666413573460cf6d3880a56

**Comment by bridgetkromhout** [comment]
Done.
