### ISSUE TITLE
twitter link in footer doesn't actually go to @devopsdays

### ISSUE THREAD

**Issue by mattstratton** [devopsdays/devopsdays-web#436]

**Comment by bridgetkromhout** [comment]
Fixed in https://github.com/devopsdays/devopsdays-web/pull/484.

**Comment by mattstratton** [comment]
Ahhh...see, this is why I did the "fixed in branch" label, because I was keeping the issues open until we merged this branch in. That made sense to me at the time for some reason.

**Comment by bridgetkromhout** [comment]
Ah, okay. I figure we're close enough to merging now. But as you wish!
