### ISSUE TITLE
RD - Welcome page table columns run together

### ISSUE THREAD

**Issue by WhatsChrisDoing** [devopsdays/devopsdays-web#441]
Some events (Toronto, Minneapolis, Boise) use a table on the welcome page. The responsive styling has reduced the white space in the table. The two columns nearly touch and the table rows have lost their vertical spacing. There are no special styling used on the tables.

![welcome-menu](https://cloud.githubusercontent.com/assets/2722194/15476530/7d780e84-20dd-11e6-995b-1db61ca16ce1.png)

**Comment by bridgetkromhout** [comment]
Nice-to-have but not a deal-breaker for the merge.

**Comment by bridgetkromhout** [comment]
Before:
![screen shot 2016-06-04 at 3 30 08 pm](https://cloud.githubusercontent.com/assets/2104453/15801916/664d8cc6-2a69-11e6-9c5b-dd7893f80719.png)


After my proposed correction in https://github.com/devopsdays/devopsdays-web/pull/526:


![screen shot 2016-06-04 at 3 29 55 pm](https://cloud.githubusercontent.com/assets/2104453/15801915/5fd69b44-2a69-11e6-8d11-b4bc9e67bf59.png)

**Comment by bridgetkromhout** [comment]
If @mattstratton thinks this is a good approach, I can change it everywhere else it's an issue including the sample event.

**Comment by mattstratton** [comment]
👍

**Comment by bridgetkromhout** [comment]
Updated for every current event but AMS in https://github.com/devopsdays/devopsdays-web/pull/532.
