### ISSUE TITLE
add search bar to main nav

### ISSUE THREAD

**Issue by mattstratton** [devopsdays/devopsdays-web#444]
Sure would be nice to have a search...will use google site search or whatever.

**Comment by bridgetkromhout** [comment]
Ooooh... [Swiftype](https://swiftype.com/) is super good.

**Comment by mattstratton** [comment]
Also [super spendy](https://swiftype.com/pricing)

**Comment by bridgetkromhout** [comment]
> Also super spendy

If we decided to try it, pretty sure that as a 2015 devopsdays MSP speaker, @look would be willing to discuss friends-pricing. :)

**Comment by mattstratton** [comment]
Adding this feature in [devopsdays-theme](https://github.com/devopsdays/devopsdays-theme)
