### ISSUE TITLE
devopsdays Paris 2015 "site" looks like it's been reset

### ISSUE THREAD

**Issue by jooooooon** [devopsdays/devopsdays-web#449]
Hi,

I needed to look something up about our last event, and headed to http://www.devopsdays.org/events/2015-paris/. There's nothing there anymore except the default content. We had a bunch of things (sponsors and a program, for example).

The only commit I can even see on this repo is bd20d7c9e7f8627225593bdf2d7cc3744c2a59d9, which I'm guessing is what's broken it.

I'd love to debug it, but it's way past my bedtime and my Ruby-foo is really not great. This is the best I can do right now :)

Jon

**Comment by bridgetkromhout** [comment]
Okay, this should be fixed (when built) with https://github.com/devopsdays/devopsdays-web/pull/454 & https://github.com/devopsdays/devopsdays-web/pull/456. I think what happened was we didn't migrate any that someone already completed, and this got stubbed out but not completed.

**Comment by jooooooon** [comment]
Yay! That worked like a charm - everything is back :)

Thanks a lot, @bridgetkromhout !

**Comment by jooooooon** [comment]
Hey,

Just checked back and it's broken again... but differently. Same bug or different one?

:(

Jon

**Comment by mattstratton** [comment]
@bridgetkromhout this seems like a bunch of the old events are broken - I will take a look at it tomorrow night when I have a few hours to hack on it. See also http://www.devopsdays.org/events/2014-siliconvalley/welcome/

**Comment by bridgetkromhout** [comment]
Different bug, and yeah, needs investigating. Maybe related to other CSS weirdness?

**Comment by jooooooon** [comment]
Hi again! Sorry to nag, but are there any updates on this? The devopsdays Paris-2015 page is still pretty messed up, and we're trying to organise the next edition at the moment, which means a lot of folk going to check it out to see "how last year was". Any kind of fix, even just displaying the pages the way they used to be as static HTML, would be great.

**Comment by jooooooon** [comment]
Also please let me know if I can help in any way. (I don't speak Ruby, though, unfortunately)

**Comment by mattstratton** [comment]
I know right now @bridgetkromhout is in the middle of Velocity and I am in the middle of moving house. I will try to carve off a few hours this evening to resolve this.

**Comment by jooooooon** [comment]
Thank you very much, @mattstratton! Do let me know if I can help.

**Comment by mattstratton** [comment]
#854 will handle this

**Comment by mattstratton** [comment]
depending on DNS cache for you, you should now see paris displaying properly.

**Comment by jooooooon** [comment]
Just checked and - yes, it is looking just like before. Thank you very much!
