### ISSUE TITLE
Organizing instructions page could be more modular

### ISSUE THREAD

**Issue by mattstratton** [devopsdays/devopsdays-web#48]
On the legacy site, this is made of up many submodules which probably makes for an easier documentation update. In the initial release, we will just have one content page for the whole organizing guide, and attack breaking it up into submodules later.

**Comment by mattstratton** [comment]
Does this matter? It actually might make things more confusing, instead of one big markdown file like it is now?

It doesn't seem to have bothered anyone yet...

**Comment by bridgetkromhout** [comment]
One large file is fine. I've made what I think are the necessary content cleanup changes.
