### ISSUE TITLE
Move static images for legacy from theme to global

### ISSUE THREAD

**Issue by mattstratton** [devopsdays/devopsdays-web#485]
See 2016 Atlanta talk page for example.

**Comment by bridgetkromhout** [comment]
This is the one blocker left for the release of the responsive site, from my POV. If we can get this in tomorrow I'd be in favor of getting the responsive design branch merged in.

**Comment by bridgetkromhout** [comment]
For posterity, this is what the issue looks like:

![screen shot 2016-06-04 at 9 51 28 am](https://cloud.githubusercontent.com/assets/2104453/15800264/2e2b5d2a-2a3a-11e6-9739-0a1b0753a6e3.png)

And after correction:

![screen shot 2016-06-04 at 9 49 23 am](https://cloud.githubusercontent.com/assets/2104453/15800267/338f8c96-2a3a-11e6-805a-c79049b3ac4f.png)

**Comment by mattstratton** [comment]
Fixed by https://github.com/devopsdays/devopsdays-web/commit/71dc15d1d011f3341ec091831f670fe6b8db62a1
