### ISSUE TITLE
consider moving /static/events directory to a submodule

### ISSUE THREAD

**Issue by mattstratton** [devopsdays/devopsdays-web#499]
The theory is that we could make `/static/events` a submodule, and we’d have to make a few small changes for the events that actually use the real code and aren’t just a bunch of generated html. instead of storing the `logo.png` for each event in `/static/events/YYYY-CITY`, it would be stored in `/static/img/YYYY-CITY`. And you could, in theory, do the same thing with `/static/content/YYYY-CITY` for non-image files (prospectus, etc), although we are wanting to discourage the hosting of those files there.

Currently, `/static/events` is about 125MB, so if we could pull that out of the main repo, that would cut this repo in half. That's pretty useful.

it would mean when you build it locally, if you don’t pull in the submodules, the links to the “old” events would be broken, but unless you’re hacking directly on old stuff, that shouldn’t matter.

Before converting to the submodule, we would need to move the logo.png stuff into `/static/img/YYYY-CITY`. For non-logo files (prospectuses, etc) for current events we would need to move them to the `/static/content/YYYY-CITY` directories, and fix the links to them. The downside of this is that if folks have shared direct links to those prospectuses they would break. We can leave them in the submodule as well, but if there is a change to the prospectus file, the event would have to update it in the submodule.

With regard to the prospectus files, I think we can probably handle it on a case-by-case basis. Various events are using the directory in different ways, and again, it probably just means that if you (as an event) want to use the `/static/events` directory, it means you need to make a PR to the submodule instead, for the time being?

**Comment by mattstratton** [comment]
Alternatively, we could create a massive amount of submodules (one for every "static" old site) and let people still use the `/static/events` directory as is...just that the old stuff would be each its own submodule. Since GH doesn't charge us per-repo,it's not like it's the end of the world to have 40+ more repos under this team :)

**Comment by mattstratton** [comment]
(This also will fix the whole "too many open files" nonsense)

**Comment by bridgetkromhout** [comment]
I'm not ignoring this - I just want us to focus on the responsive design stuff before taking on this project. (I have many concerns around introducing unneeded complexity, but let's paint one bikeshed at a time.) =)

**Comment by mattstratton** [comment]
So my new theory on this one is that we don't do it with a submodule, because ick.

Instead, I'm thinking something like this:

We serve up a webby-generated version of the site (with only 2015 and earlier events) at a URL such as `legacy.devopsdays.org` (I'm open to suggestions on what to call this URL). Then, we have a redirect rule that all traffic to `www.devopsdays.org` with a path of `/events/2015/*`, `/events/2014/*`, etc, redirect to `legacy.devopsdays.org/events/2015/*` with the path intact, etc. The old URL's would all still work then (might have to do a small amount of webby tweaking so that main nav links like `home` and `contact` point to `www` instead of `legacy`), and then we could whack all of the old, non-delightful events from this repo.

This would solve #641, #449, and #292.

NOTE: We will will need the basic skeleton of the past events (the data files are all we need I think) in the main repo so the generated lists of past events still work. 

Thoughts?

**Comment by phrawzty** [comment]
« You have a problem, so you think, "I know, I'll use sub-modules!" Now you have two problems. » 😉 

I like the idea of "legacy" site that is functionally independent from the main site, since it allows us to work with the old and busted as a separate management cycle from the new hotness. I've maintained fairly large sites with lots of URL redirect rules (see: www.mozilla.org), and while it sort of makes your eyes hurt to look at, the configuration is manageable.

In terms of the "webby tweaking", would this be a case of search and replace across the code base, or a config change, or...?

**Comment by mattstratton** [comment]
I haven't tried it yet, but I suspect the config change to webby should be fairly minimal (like a config file change). I could be quite wrong. :)

**Comment by mattstratton** [comment]
Or even better - handle things like `/contact` as redirects on legacy back to www so no changes needed to the html :)

**Comment by mattstratton** [comment]
This redirect idea depends on #157 and moving to Netlify instead of GH Pages.

**Comment by mattstratton** [comment]
Closing this issue as it'll be tracked in #854
