### ISSUE TITLE
Create events calendar page

### ISSUE THREAD

**Issue by mattstratton** [devopsdays/devopsdays-web#51]
http://www.devopsdays.org/events/calendar/

**Comment by bridgetkromhout** [comment]
I'm on the fence about this. I don't know how necessary it is, now that devopsconferences.org exists.

**Comment by mattstratton** [comment]
I'm totally okay with dropping this :)

**Comment by mattstratton** [comment]
It was easy to add it - it looks weird because of the tweetstream thingy, but we can fix that later if someone cares.
