### ISSUE TITLE
make AMS colors more readable for Security track

### ISSUE THREAD

**Issue by bridgetkromhout** [devopsdays/devopsdays-web#513]
The blue text on dark green used to be easier to read in the original color scheme on the left and is harder to read in the responsive design (on the right).

![screen shot 2016-06-03 at 11 52 54 pm](https://cloud.githubusercontent.com/assets/2104453/15797688/537664d4-29e6-11e6-9b0f-0eb6f5298a7d.png)

**Comment by bridgetkromhout** [comment]
I'm going with this for now, after chatting with @mattstratton. We agree that @yvovandoorn can change it to whatever he prefers (that's readable).

![screen shot 2016-06-04 at 9 04 49 am](https://cloud.githubusercontent.com/assets/2104453/15799983/ba0c2de4-2a33-11e6-82b9-9561974450dd.png)

**Comment by bridgetkromhout** [comment]
@yvovandoorn - we're going to get the redesign branch merged in the next day or so. After that, PRs accepted or you can close this if you're happy with how it looks.

**Comment by yvovandoorn** [comment]
This looks fine to me for now. We can change post mega merge.

On Saturday, 4 June 2016, Bridget Kromhout <notifications@github.com> wrote:

> @yvovandoorn <https://github.com/yvovandoorn> - we're going to get the
> redesign branch merged in the next day or so. After that, PRs accepted or
> you can close this if you're happy with how it looks.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/devopsdays/devopsdays-web/issues/513#issuecomment-223757879>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ACkd_3_8EW0V92LPWJWZRVQdvblXhs-uks5qIYg6gaJpZM4IuDT2>
> .
>


-- 

*Yvo van Doorn* — Manager, Technical Services (EMEA)

+31 6 38 74 07 46 <+316740746> – yvo@chef.io – *my: *Linkedin
<http://www.linkedin.com/in/yvovandoorn/>  Twitter
<https://twitter.com/yvov>

CHEF

CHEF.IO <http://www.chef.io/>

TM

*chef.io <http://www.chef.io/>*   Blog <http://www.chef.io/blog/>   Facebook
<https://www.facebook.com/getchefdotcom>   Twitter
<https://twitter.com/chef>   Youtube <https://www.youtube.com/getchef>

**Comment by bridgetkromhout** [comment]
Question, @yvovandoorn - would you like this open as a task for you? If not, feel free to close. :)

**Comment by bridgetkromhout** [comment]
Perfect! Thanks.
