### ISSUE TITLE
change AMS welcome page to use divs instead of table

### ISSUE THREAD

**Issue by bridgetkromhout** [devopsdays/devopsdays-web#533]
Since @yvovandoorn is actively updating the AMS site at this moment, I left `content/events/2016-amsterdam/welcome.md` out of the update I just did in https://github.com/devopsdays/devopsdays-web/pull/532. @yvovandoorn, if you want to implement that, you'll find what you want here: https://raw.githubusercontent.com/devopsdays/devopsdays-web/master/content/events/sample-event/welcome.md 

My motivation was that the table made sites look not so great, per https://github.com/devopsdays/devopsdays-web/issues/441.

**Comment by yvovandoorn** [comment]
Fixed in #536
