### ISSUE TITLE
figure out a solution for non-square sponsor logos

### ISSUE THREAD

**Issue by mattstratton** [devopsdays/devopsdays-web#545]
A lot of sponsor logos don't really adjust well to the 1:1 dimensions. Bikeshed away as to what we can do about this...

(note: the reason we currently constrain in the CSS to 100px x 100 px and request a 200px square image is to make with fancy Retina magic. If we were to opt out of this, there would have to be some type of solution to make them better in a responsive way...I believe that in order to get the high res you have to constrain both H and W, but not sure - @jyee?)

**Comment by jyee** [comment]
We don't necessarily have to constrain them, but it's the easiest way to balance std + retina without having to futz with generating multiple images and doing image-set css or srcset html5.

I guess one of the other things we could do is build out the front-end pipeline (since we've already got LESS) and have it handle the image sizing and such for us.

**Comment by mattstratton** [comment]
I already started thinking about building out the pipeline, mostly because I wanted to get `html-minify` in there (although the scads of invalid HTML in the old generated webby stuff is making it break terribly).

The trick is figuring out how to have the pipeline do this stuff but have a minimum of things people need to do locally. That is to say, I don't want people to have to use `grunt` or `gulp` just to submit changes.

**Comment by mattstratton** [comment]
Hmm. [This grunt plugin](https://github.com/JrSchild/grunt-retinafy) seems like it would work. The thing that would be nice would be to only have to do this when building to publish, not locally. 

I think this would work, because when working locally, you'll just have `chef-2016.png` or whatever, and the CSS is going to say "okay, no retina image here, just use this one". But then when it's run through grunt, it will make the `chef-2016@2x` image.

Also, pasting this link to keep track of it for later: https://imulus.github.io/retinajs/

**Comment by bridgetkromhout** [comment]
Does https://github.com/devopsdays/devopsdays-web/blob/master/utilities/resize_sponsor_logo.sh handle any/all of this? (I've not tried/vetted it at all.)

**Comment by mattstratton** [comment]
Not really. This sorta became a image processing pipeline bikeshed, and what we really need to do is figure out how to not "cheat" to get retina by constraining them to certain ratios.

**Comment by mattstratton** [comment]
The retina-fication is handled in the pipeline of [devopsdays-theme](https://github.com/devopsdays/devopsdays-theme) so this issue can be closed in this repo.
