### ISSUE TITLE
Maps need to be updated to add label instead of mouseover

### ISSUE THREAD

**Issue by mattstratton** [devopsdays/devopsdays-web#55]

**Comment by jyee** [comment]
This appears to be fixed, although dates are showing as "YYYY-MM-DD" vs. the existing site showing "mmm DD". Is that something we want to change to match the old site?

**Comment by mattstratton** [comment]
IMHO, it's a minor difference and actually probably more effort than it is worth. I'll close this ticket and we can use #137 for the date display issue.
