### ISSUE TITLE
Events With Single Dates Are Displayed Poorly Now

### ISSUE THREAD

**Issue by robscott** [devopsdays/devopsdays-web#5565]
Sometime relatively recently, our event (https://www.devopsdays.org/events/2018-chattanooga) went from displaying "November 13, 2018" as the date to "November 13-13, 2018". Not sure if this is the right place for this, and happy to try to fix the issue here.

**Comment by bridgetkromhout** [comment]
Thanks. We'll fix it in https://github.com/devopsdays/devopsdays-theme/issues/663.
