### ISSUE TITLE
fix event start date display

### ISSUE THREAD

**Issue by bridgetkromhout** [devopsdays/devopsdays-web#569]
When compiled locally, http://localhost:1313/events/2016-minneapolis/welcome/ appears like this:

![screen shot 2016-06-11 at 3 44 09 pm](https://cloud.githubusercontent.com/assets/2104453/15987373/681e47de-2feb-11e6-97c3-71f6c9b6bfdb.png)

and the source says this:

<meta property="og:description" content="Wednesday, Jul 20, 2016 - Thursday, Jul 21, 2016 devopsdays is returning to Minneapolis!

When compiled by wercker for display on gh pages, http://www.devopsdays.org/events/2016-minneapolis/welcome/ appears like this:

![screen shot 2016-06-11 at 1 28 44 pm](https://cloud.githubusercontent.com/assets/2104453/15987363/246da2dc-2feb-11e6-8a36-6cb5dcde4a85.png)

and the source says this:

<meta itemprop="description" content="#} - Thursday, Jul 21, 2016 

Because I can't duplicate it locally I'm not sure when this started happening, but I don't think it was happening a week or two ago when I last looked (pretty sure I would have noticed).

The offending line appears to be coming out of https://github.com/devopsdays/devopsdays-web/blob/master/layouts/partials/head/seo/schema.html#L3 and as that hasn't changed lately, I think the change might be the June 9th when @mattstratton said "Looks like our build change updated to Hugo 0.16. " on Slack.

We're outside what I'm confident in changing, so, @mattstratton?

**Comment by mattstratton** [comment]
Yep, this is something that only occurs on hugo 0.16. I have fixed it so that production builds using 0.15 in #575

**Comment by mattstratton** [comment]
That being said, this does need to be fixed. This is a sub-issue of #543

**Comment by mattstratton** [comment]
This was fixed in #768
