### ISSUE TITLE
Convert frontpage banner to logo + text instead

### ISSUE THREAD

**Issue by m1keil** [devopsdays/devopsdays-web#57]
This is very old style of doing websites. I think the top banner should be converted to CSS/HTML.

**Comment by mattstratton** [comment]
+1

**Comment by mattstratton** [comment]
Not directly related, but I have been using the `content` label for issues/tasks that are unrelated to code/design. We should add a `design` label for ones relates to design/UX.

**Comment by bridgetkromhout** [comment]
Hi, @m1keil - 

Great idea! now that we're migrated over, we would be happy to get this going. Do you want to submit a PR when you get a chance? Thanks.
