### ISSUE TITLE
Add "staging" area where PRs and non-master branches can be viewed live

### ISSUE THREAD

**Issue by m1keil** [devopsdays/devopsdays-web#63]
This will help previewing changes without the need for running Hugo. WYSIWYG style.

The general idea is:
* master branch would be build and copied into the main location - `http://devopsdays.github.io`
* any non master branch or PR should be build and copied into staging area -`http://devopsdays.github.io/<branch/PR_name>`

So it would be possible to review the changes not only by the content, but by how it actually looks live in your web browser.

**Comment by mattstratton** [comment]
I don't know how well hugo will handle having the subdirectories; I feel like once we go live, @jedi4ever is probably going to want this hosted on s3 instead of GH pages, so we can flip wercker to only build a dev branch to gh pages perhaps. That still doesn't quite solve for your suggestion however.

**Comment by mattstratton** [comment]
Additionally, since Hugo's local server is so good, you should be able to just pull down the proposed branch and run it locally.

**Comment by bridgetkromhout** [comment]
> hosted on s3 instead of GH pages

Is there a good reason for that? I like GH pages, personally.

**Comment by mattstratton** [comment]
Maybe helpful - http://devcenter.wercker.com/learn/workflows/introduction.html

**Comment by phrawzty** [comment]
>  > hosted on s3 instead of GH pages
> Is there a good reason for that? I like GH pages, personally.

Brass tacks, what's more reliable: GH pages or S3? Honest question!

**Comment by m1keil** [comment]
probably S3, but does it really matters for relatively low traffic level
site such as DOD?
(What's the worse that can happen if GH is down for an hour once every 6
months?)

**Comment by mattstratton** [comment]
We kind of bikeshed this somewhere else (in the migration ticket whose number I misremember) and settled that GH Pages are fine :)

**Comment by bridgetkromhout** [comment]
If someone is using hugo already, it's trivial to pull down someone else's branch and look at it locally. A potential use case for a shared staging environment is if a stakeholder who can't use github and hugo wants to see an in-progress site. 

It's probably worth revisiting this after we revisit the build tools in https://github.com/devopsdays/devopsdays-web/issues/157.

**Comment by mattstratton** [comment]
Thanks to @jfrazelle, we now have this functionality! When you are looking at a PR, click on "show all checks", and then the "Details" for the Netlify check to see a live preview of the PR!
