### ISSUE TITLE
Consideration for having a https version of devopsdays?

### ISSUE THREAD

**Issue by yvovandoorn** [devopsdays/devopsdays-web#642]
Currently https://devopsdays.org and https://www.devopsdays.org either timeout or show an invalid cert while querying Github.

Long term, would it be a good idea/enhancement to have a SSL certificate in place for both?

**Comment by bridgetkromhout** [comment]
We'd very much like to. As I understand it, we'd need to move off github pages, so this would require some work.

**Comment by phrawzty** [comment]
> As I understand it, we'd need to move off github pages

Could we not set up an SSL-enabled CDN which uses the GH page as its origin? Cloudfare appears to be a popular choice for this [exact use case](https://www.google.com/search?q=cloudfare+github+pages) (it's also free, apparently?).

**Comment by mattstratton** [comment]
Actually we do not need to move off of GH pages. I do this currently with the identical setup on ADO, but it's because I use Cloudflare.

We would need to move from fastly to cloudflare to do this.

**Comment by mattstratton** [comment]
@jedi4ever thoughts on moving DNS to cloudflare so we can use the free SSL?

**Comment by mattstratton** [comment]
@yvovandoorn - the https URL is working now, but as noted in #899 there's a mixed-mode issue. Grr.

**Comment by mattstratton** [comment]
Now that https mixed-mode issue on #899 has been resolved, I have flipped the trigger to enforce HTTPS on all the url's. Please let me know if anything blows up.
