### ISSUE TITLE
events disappearing from front page before enddate is over

### ISSUE THREAD

**Issue by bridgetkromhout** [devopsdays/devopsdays-web#6537]
Possible logic flaw in the way we're handling enddate? For whatever reason I thought it was behaving as desired (keeping an event on the front page until its end date was over, probably with the flaw of assuming UTC). However, this morning we very clearly had events that are on "day two" today, and those two events (Portland and Berlin) had disappeared off the front page.

I believe the behavior we _want_ is "all the way through until 23:59pm on the enddate, ideally local time but that's a different matter, we want an event to remain displayed on the front page".

I wouldn't have been surprised at an event disappearing from the front page at 23:59pm UTC on the enddate. It _appears_ it may instead have been disappearing from the front page at 00:01 on the enddate? Definitely not as desired, and I am surprised by it. (I feel like Minneapolis _did not_ have this occur? Maybe?)

See https://github.com/devopsdays/devopsdays-web/pull/5399 for the hotfix. I'll submit that as a PR to this repo and we can iterate to improve it.

attn: @mattstratton & @tgross

**Comment by bridgetkromhout** [comment]
This is the data fix which sets correct datetimes for all 2019 events: https://github.com/devopsdays/devopsdays-web/pull/6591

**Comment by bridgetkromhout** [comment]
This is the theme fix which should resolve this correctly. It checks the full datetime stamps to ensure events are on the page for their correct times, and makes it unnecessary to artificially extend events' tenure on the page for an extra day: https://github.com/devopsdays/devopsdays-web/pull/6595

**Comment by MikeRosTX** [comment]
Was this time formatting intentional or accidental meant to be used in the Program section as well of the city's yml?  Just curious. It caught my eyes because I've never seen it before.

![image](https://user-images.githubusercontent.com/11631454/66086274-2c431080-e539-11e9-9c73-6bb415c7f09b.png)

**Comment by tgross** [comment]
@MikeRosTX this is [RFC3339 format including TZ offset](https://tools.ietf.org/html/rfc3339), which Hugo (which is written in golang) turns into a [`time.Time`](https://golang.org/pkg/time/) struct and handles appropriately.
