### ISSUE TITLE
[Bug] Speaking Page - Manually sorting dates combines ascending and descending orders

### ISSUE THREAD

**Issue by crayzeigh** [devopsdays/devopsdays-web#6544]
Not sure how else to title that more clearly..

### Expected behavior

When clicking on the column headers "CFP Closes" or "Event Starts" it is expected the dates would sort in order, from next date to the furthest (with arrow pointing down) . A Second click would sort (Arrow up) from furthest date, to closest.

Criteria for sort would be expected to evaluate as Year > Month > Day in the same order.

### Actual behavior

Clicking a header sorts in a mix of ascending and descending that appears to link to the Day being sorted opposite of the rest of the criteria. Therefore, descending order lists the nearest Year, Month, and then the Furthest date of that month, to the nearest before continuing to the next month. So descends year, descends month, then ascends date.

Criteria appears to be Year > Month > Day (opposite order)

### Reproduction Steps

Open /speaking and click the heading for "CFP Closes" or "Event Starts"

### Operating System and Version

Mac OS Sierra 10.12.4

### Web Browser and Version
Confirmed on: 
* Chrome  Version 57.0.2987.133 (64-bit)
* Safari  Version 10.1 (12603.1.30.0.34)
* Opera Version 44.0.2510.1449

**Comment by mattstratton** [comment]
Fixed in #8218 

If this hasn't been fixed to your satisfaction, feel free to re-open the issue with details :)
