### ISSUE TITLE
Change speaking page sort order

### ISSUE THREAD

**Issue by bridgetkromhout** [devopsdays/devopsdays-web#6548]
The sort order for the page introduced in https://github.com/devopsdays/devopsdays-theme/issues/117 defaults to column 3 - in order of when the conference is being held. That seems like it's not the most useful default, since someone coming to this page might reasonably expect the CFP closing soonest to be atop the list (which would mean sorting by column 2).

**Comment by mattstratton** [comment]
#8218 might be the fix for this - with this change, the CFP page is sorted by CFP date by default now. @bridgetkromhout 	if this is satisfactory to you, we can close this issue.

**Comment by mattstratton** [comment]
I am pretty sure @bridgetkromhout 	told me in Slack this was able to be closed. If not, feel free to re-open :)
