### ISSUE TITLE
investigate speaking page issue

### ISSUE THREAD

**Issue by bridgetkromhout** [devopsdays/devopsdays-web#6625]
I'm not sure why this started happening.

<em>
Bridgets-MacBook:devopsdays-web bridget$ hugo --theme=devopsdays-theme --buildDrafts=false --baseURL="https://www.devopsdays.org/"
Total in 84512 ms
Error: Error building site: failed to render pages: render of "page" failed: execute of template failed: template: speaking/single.html:9:4: executing "main" at <partial "speaking.ht...>: error calling partial: "/Users/bridget/github/devopsdays/devopsdays-web/themes/devopsdays-theme/layouts/partials/speaking.html:12:34": execute of template failed: template: partials/speaking.html:12:34: executing "partials/speaking.html" at <dateFormat "2006-01-...>: error calling dateFormat: unable to cast <nil> of type <nil> to Time
</em>
<p>

There is probably a data problem in some CFP dates. But then, I'm unsure why it didn't start happening when I put all the full datetime strings in. It started happening with a build that didn't touch that, afaict.  I wonder if I broke it when I added datetimes and then we were operating off cache or something like that?

I put a temporary patch in (https://github.com/devopsdays/devopsdays-web/pull/6624) to alleviate the symptoms (which consisted of "site builds would fail with the above error"). I can duplicate the error locally, so it's debuggable. This patch allows the site to build, so our production builds are fine. (The CFP listing just doesn't appear on the speaking page until we solve this.)

**Comment by jakubjakubik** [comment]
https://github.com/devopsdays/devopsdays-web/blob/master/data/events/2019-montevideo.yml#L9

the start date is NIL, but 

https://github.com/devopsdays/devopsdays-web/blob/master/data/events/2019-montevideo.yml#L14

cfp_date_end is defined - thus iterating over events that have the cfp_date_end defined tries to format a nil startdate

**Comment by bridgetkromhout** [comment]
Thanks, @jakubjakubik! In this case, this is behaving as desired (because we do not want to list a CFP when the event dates are unknown). We just hadn't had time to figure out where the problem was. In this case, it was bad data, which I am reverting in https://github.com/devopsdays/devopsdays-web/pull/6639.

**Comment by bridgetkromhout** [comment]
Upon further review, as this will allow CFP dates without event dates only on an event's own pages, and will not allow the event to appear on the `/speaking` page, I think it's wiser not to break the build (even if it allows events to list their CFPs before their event dates, which we do not want). So I have merged the fix. Thanks!

**Comment by andresantoniuk** [comment]
I'm guilty.

I noted something was not ok (https://github.com/devopsdays/devopsdays-web/pull/6608/commits/c1b2d56a876af32319977254146eb32734c5d1ff) and let @MikeRosTX to know but did not investigate further.

sorry again.

**Comment by bridgetkromhout** [comment]
Hi @andresantoniuk - don't worry about it! It is fixed now. And because this happened, @jakubjakubik submitted a fix that will make the site more reliable in the future. So everything is okay.
