### ISSUE TITLE
consider replacing appveyor

### ISSUE THREAD

**Issue by bridgetkromhout** [devopsdays/devopsdays-web#6662]
I've noticed a lot of spurious appveyor errors lately. Today's is funny:

Build started
git clone -q https://github.com/devopsdays/devopsdays-web.git C:\projects\devopsdays-web
git fetch -q origin +refs/pull/6659/merge:
fatal: unable to access 'https://github.com/devopsdays/devopsdays-web.git/': Could not resolve host: github.com
Command exited with code 128

I can only conclude that they're running on instances with inconsistent DNS resolution, which seems pretty unreliable. Do we have good alternatives?

**Comment by mattstratton** [comment]
I don’t know if any other solution - maybe azure devops offers Windows build agents?

Likewise, it’s oissible that we don’t need to test for Windows anymore since we removed the “path issue” that used to bite us?

**Comment by bridgetkromhout** [comment]
> we removed the “path issue” 

I am not clear on the details here.

**Comment by mattstratton** [comment]
We used to have a different string for file paths if it was windows vs non-windows. I’m his was resolved maybe two years ago in Hugo?

**Comment by bridgetkromhout** [comment]
Ah, okay! I only vaguely remember that. If you think we can live without a somewhat flakey check, I'm cool with removing it.

**Comment by mattstratton** [comment]
I think we removed appveyor a while ago, so I'm going to close this. Feel free to re-open if i'm incorrect :)
