### ISSUE TITLE
evaluate removing front-page map

### ISSUE THREAD

**Issue by bridgetkromhout** [devopsdays/devopsdays-web#6918]
Looks like Google now [requires an API key to use Google maps](https://developers.google.com/maps/documentation/geocoding/get-api-key), and charges money [if you go over a limit](https://oneilinteractive.com/blog/2018/07/why-is-your-google-map-broken/).

> That $200 of free use for your account each month means you can load 28,500 maps for free.

Given that this has been broken for about nine months and nobody has noticed or complained, I think I'd rather just remove it from the front page, rather than add mandatory billing info and then hope we don't go over $200 usage per month. Interested in your thoughts, @mattstratton - thanks.

**Comment by bridgetkromhout** [comment]
> this has been broken for about nine months

Correction: I note that there are some API keys in the code, so maybe the current broken state is related to some other issue?

**Comment by bridgetkromhout** [comment]
I note that the API keys have been in there since 2017, so they probably weren't added for this purpose.

**Comment by bridgetkromhout** [comment]
Before removal:
<img width="1030" alt="Screen Shot 2019-04-14 at 11 01 29 AM" src="https://user-images.githubusercontent.com/2104453/56095673-d3a58b80-5ea4-11e9-9f3d-fd2360d20dc3.png">

After removal:

<img width="1037" alt="Screen Shot 2019-04-14 at 11 01 49 AM" src="https://user-images.githubusercontent.com/2104453/56095675-d607e580-5ea4-11e9-95d5-f44d826ff46e.png">

**Comment by jedi4ever** [comment]
iirc , we can create a key because we have a  paying google devopsdays domain?

**Comment by purpleidea** [comment]
Openstreetmaps?

**Comment by bridgetkromhout** [comment]
I think we have no need for a map on the front page, and since it's been gone for months with no negative effects, I'm going to resolve this.
