### ISSUE TITLE
twitter sharing image not working

### ISSUE THREAD

**Issue by mattstratton** [devopsdays/devopsdays-web#6967]
Twitter requires a FQDN; we had removed this for build reasons. Not quite sure how to solve for this. We could theoretically hardcode it to www.devopsdays.org (the problem with using baseurl is that it makes every build longer)

**Comment by bridgetkromhout** [comment]
I doubt anyone would regard "the sharing image uses www.devopsdays.org" as a blocker for the vast majority of their testing.

**Comment by mattstratton** [comment]
Yeah, I think that this is a reasonable fix :)
