### ISSUE TITLE
add support for multi-speaker talks

### ISSUE THREAD

**Issue by bridgetkromhout** [devopsdays/devopsdays-web#708]
As seen in https://github.com/devopsdays/devopsdays-web/pull/707, the three-speaker talk is filed (by necessity) under one person's name. We should add support for program elements with a non-person-specific name and an arbitrary number of speaker bios at the end. /cc @jyee

**Comment by jyee** [comment]
I think maybe the way to change it would to orient it around the talks, not the speaker. Then to use the speakers almost like a taxonomy. So e.g. in Minneapolis, the file would go from `aj-bowen.md` -> `your-meetings-are-unbearable.md`

And the header would become:
```
+++
City = "Minneapolis"
Year = "2016"
date = "2016-03-06T21:28:07-06:00"
title = "Your Meetings Are Unbearable: Cheat Codes From Occupy"
speakers = ["aj-bowen", "jerome petazzoni"]
type = "talk"
+++
```

**Comment by bridgetkromhout** [comment]
I'm trying to avoid having the talk title be part of it. The reason is that it used to be that way, and then people would change their titles and that would cause the links to need to change. That, and people put all sorts of punctuation in talk titles.

**Comment by bridgetkromhout** [comment]
We do have better ability to do aliasing now, but another issue is that sometimes an invited speaker is confirmed without their talk being named.

**Comment by mattstratton** [comment]
You could still use the `title` frontmatter, but think of a filename more appropriate? I think even if you name the file/talk after the "primary" speaker, you can still use the speaker frontmatter as well maybe?

**Comment by bridgetkromhout** [comment]
This is of interest to @DefSol currently.

**Comment by mattstratton** [comment]
yeah, the thing is something has to be the ID, right? If it's the speaker, you really have to make it be about the primary and have some extra stuff for other speakers on that talk. 

If it's that talk, then the *file* cannot be directly named after the talk title, because a) they change and b) they might not have a title right away. 

So maybe the pure file is named like "2016-msp-talk-1.md" and you throw aliasing on it later if you want to have a nice URL with the name in it. It's less than amazing but it's probably the best taxonomy you can get with the constraints we have in our events and the real world.

**Comment by bridgetkromhout** [comment]
Since in most cases the speaker name, maybe the simplest solution is "map to speaker name as we have been, unless you override that with some frontmatter in the talk file. in this case, name the file however you like; the frontmatter will be what pulls in the right bios."

**Comment by DefSol** [comment]
I'm just trying to work out the relationship model - is there any pretty pictures that may exist to model the relationships? Am I right in thinking the model is like 

Program <==> Talk <==> Speaker(s) <==> Program

I remember the fun checking out on my windows box when the key for the talk was the title...
I'm guessing the constraint here is for a relatively meaningful & discernable uri?

Sorry, silly Q but when we say speaker frontmatter, what does this mean? Sorry my Hugo skills are low

**Comment by bridgetkromhout** [comment]
No worries. This discussion isn't really intended for you to be able to implement it right this second. When Matt and I come to an agreement about how to do this and get it working, we'll tell you/document exactly what to do. (This is annoyingly tricky with how we have things set up right now.)

If you're trying to build your program right this second, put it under one of the speakers.

**Comment by bridgetkromhout** [comment]
A couple of things here:
* I have repeated code between https://github.com/devopsdays/devopsdays-web/blob/master/themes/devopsdays-responsive/layouts/speakers/single.html and https://github.com/devopsdays/devopsdays-web/blob/master/themes/devopsdays-responsive/layouts/talk/single.html - am I correct in thinking that a "partial" is the right way to collapse that into a single location?
* I think what I'm going to do here is add an optional piece of frontmatter to these files such that we can list all the speaker-bios that should be included in the file.

This also relates to https://github.com/devopsdays/devopsdays-web/issues/338 and https://github.com/devopsdays/devopsdays-web/issues/636 but should be possible to implement without going that far. When putting the title and speakers in as data, it will be a lot easier to generate a data-driven program.

**Comment by bridgetkromhout** [comment]
> am I correct in thinking that a "partial" is the right way to collapse that into a single location?

Yep, a partial is definitely what I want. Looking at how to pass further info to a partial (https://discuss.gohugo.io/t/templates-multiple-parameters/600/2) so I can remove the redundant code to produce a speaker bio (but move the looping outside the singular "produce a bio").

**Comment by bridgetkromhout** [comment]
Something to add before resolving this issue: support for multiple speakers in https://github.com/devopsdays/devopsdays-web/blob/master/utilities/add_speakers.sh.

**Comment by mattstratton** [comment]
This is a feature in [devopsdays-theme](https://github.com/devopsdays/devopsdays-theme) so we can close this on this repo.
