### ISSUE TITLE
Need a repo to hold supporting files

### ISSUE THREAD

**Issue by mattstratton** [devopsdays/devopsdays-web#725]
There are a few files (such as high-res, print files of the brain logo) that we need to keep somewhere, but I want to keep them out of this main repo.

We should create a repo under `devopsdays` to hold this type of artifact. What should we call this repo?

**Comment by phrawzty** [comment]
`devopsdays-assets` ?

**Comment by mattstratton** [comment]
Well that's hardly creative :)

Kidding...I think that `devopsdays-assets` seems logical. I primarily want to make sure it's crystal clear that things in this repo are NOT served up by the website, and I think that referring to them as `assets` probably accomplishes this.

**Comment by phrawzty** [comment]
> make sure it's crystal clear that things in this repo are NOT served up by the website

As long as the repo has the following README.md, we should be fine:

```
# THINGS IN THIS REPO ARE NOT SERVED UP BY THE WEBSITE.

## IF YOU'RE NOT SURE, ASK BEFORE COMMITTING.
```

😄

**Comment by bridgetkromhout** [comment]
> THINGS IN THIS REPO ARE NOT SERVED UP BY THE WEBSITE

That wording is so confusing to me because um yes they can be linked to and served by the site and that's kinda the point. ;)

**Comment by mattstratton** [comment]
Maybe "items in this repo are only accessible via github urls and not devopsdays.org urls"

**Comment by phrawzty** [comment]
Maybe "things in this repo are not built into the devopsdays site, but can
be linked to directly via GitHub"?

**Comment by mattstratton** [comment]
Repo created at https://github.com/devopsdays/devopsdays-assets
