### ISSUE TITLE
Add support for SlidesLive videos to talk pages

### ISSUE THREAD

**Issue by skryukova** [devopsdays/devopsdays-web#7291]
SlidesLive provides an easy way to embed their videos into a page. It would be great, if in addition to `youtube` and `vimeo` fields, the talk pages supported `slideslive` property. The property should be an unique numeric identifier of the presentation on the SlidesLive.com page (e.g. `38915149`). To embed the video on the page the following snippet needs to be added:

```
<div id="presentation-embed-38915149"></div>
<script src='https://slideslive.com/embed_presentation.js'></script>
<script>
    embed = new SlidesLiveEmbed('presentation-embed-38915149', {
        presentationId: '38915149',
        autoPlay: false // change to true to autoplay the embedded presentation
    });
</script>
```

Houston 2019 currently embedded all its presentations via explicit use of the above script in each of the individual talk .md files. When this feature is implemented or needs to be tested, I am happy to be the guinea pig and switch them all to the use of the new property.

**Comment by bridgetkromhout** [comment]
Hi, @skryukova - we've implemented this feature. Go ahead and try it as shown in https://github.com/devopsdays/devopsdays-web/pull/8096 if desired.
