### ISSUE TITLE
Account for single day events

### ISSUE THREAD

**Issue by mattstratton** [devopsdays/devopsdays-web#74]
See Istanbul for an example

**Comment by bridgetkromhout** [comment]
Istanbul isn't single-day anymore, but the principal still holds.

**Comment by bridgetkromhout** [comment]
People have been working around this by setting the same start and end date. I'm not really sure it's worth trying to create a one-day special case; that's been working fine afaict.

**Comment by phrawzty** [comment]
At this point it's a cosmetic issue. Individual events don't need to use
the start/end macro, so the only place this comes up consistently is the
global event listing.

tl;Dr this is still an issue, but I'd consider it very low priority.

**Comment by mattstratton** [comment]
Closing this issue as it's being taken care of in https://github.com/devopsdays/devopsdays-theme/issues/135
