### ISSUE TITLE
Support adding more info for organizers

### ISSUE THREAD

**Issue by mattstratton** [devopsdays/devopsdays-web#75]
Organizers should be able to add twitter handles, employer, and email address (all optional)

See DC for an example

**Comment by bridgetkromhout** [comment]
I would prefer if we don't encourage email addresses. I don't want people emailing a specific organizer instead of the group list. That leads to dropped threads. (Especially if that organizer is me!)

**Comment by mattstratton** [comment]
Yup. To be fair, I wrote this issue at 2 AM. I agree that the use of email addresses should be dropped from this feature :)

**Comment by bridgetkromhout** [comment]
This is done, as far as I can tell.
