### ISSUE TITLE
[Bug] Replacing "a" with "an" before sponsorship level

### ISSUE THREAD

**Issue by aameen79** [devopsdays/devopsdays-web#7524]
![image](https://user-images.githubusercontent.com/37726435/60139289-a717c500-97ad-11e9-9861-4a9b23933618.png)

**Comment by MikeRosTX** [comment]
Assigning to @mattstratton, since he merged this change in #7468.

**Comment by bridgetkromhout** [comment]
Instead of complex parsing, I propose something like "$sponsorshipname signup".

**Comment by bridgetkromhout** [comment]
Fixed in https://github.com/devopsdays/devopsdays-web/pull/8086.
