### ISSUE TITLE
Update global sponsor page w/2018 or 2019 stats

### ISSUE THREAD

**Issue by ThePVD** [devopsdays/devopsdays-web#7644]
"Devopsdays is a community-organized not-for-profit conference series for practitioners. It began in Ghent, Belgium with one conference in 2009, and has grown to more than 40 events worldwide in 2016."

[content/page/sponsor.md](https://github.com/devopsdays/devopsdays-web/blob/master/content/page/sponsor.md)

I contemplated trying to PR this myself from website data but I wasn't sure if there was a more official source.

**Comment by bridgetkromhout** [comment]
We don't have it being dynamically created; feel free to PR! Thanks.

**Comment by bridgetkromhout** [comment]
I've adjusted this page and credited you in the PR - thanks for the suggestion.

**Comment by ThePVD** [comment]
Thanks @bridgetkromhout !  I'm slow on my GSD streak this week :)
