### ISSUE TITLE
Create setup script for new events

### ISSUE THREAD

**Issue by mattstratton** [devopsdays/devopsdays-web#8]
This is a low priority, but once we have the format down, we should create a pair of shell (and Powershell) scripts that can be used to generate a new event, taking in just the year and city name, etc.

In psuedocode, something like this (taking $YEAR and $CITY as arguments or something)

```
hugo new events/$YEAR-$CITY/welcome.md --kind event
hugo new events/$YEAR-$CITY/program.md --kind event
hugo new events/$YEAR-$CITY/contact.md --kind event
hugo new events/$YEAR-$CITY/conduct.md --kind event
.
.
.
cp data/events/TEMPLATE.yml data/events/$YEAR-$CITY.yml
```

**Comment by bridgetkromhout** [comment]
Closing this, as I've done it.
