### ISSUE TITLE
Add embedded support for Google Forms on main pages

### ISSUE THREAD

**Issue by jazimmerman** [devopsdays/devopsdays-web#80]
As discussed on Slack, let's add support to the website redesign to embed a Google Form into the main page of a DevOps Days event.

These forms would be intended primarily for people to add themselves to a list of people interested in a future event to get updates on things such as CFPs, sponsorship and tickets going on sale.

Matt's suggestion in Slack was to set this up so there'd simply be an attribute to which you can supply a url to a Google Form.

**Comment by bridgetkromhout** [comment]
I see an iframe embed added by @jazimmerman here: https://github.com/devopsdays/devopsdays-web/commit/e36104a90cb9a41fd3963d3ec6d4c11894742758 - is there something specific we need to do to the hugo code that's different from "just embed the iframe"? Not sure if this is the sort of thing it makes sense to drive from the yaml.

**Comment by jazimmerman** [comment]
Ah. Sorry, the problem with referencing conversation in Slack in a GitHub issue. Somebody else was asking for ways to gauge interest/getting a list of people who wanted updates on tickets/CFP/sponsorship. I had mentioned that this was what we were using an iframe linking out to a Google Form.

Matt's response was that it would be cool to possibly provide this down the line as a data element in Hugo so that somebody could just put the link into the yaml and it'd be handled in a nice, standard and easy way and asked me to submit an issue.

That being said, it is easy enough to add in an iframe to the welcome.md that tribal knowledge in the Slack may be good enough to help people who are interested in doing this for their event. Doesn't much matter to me. :)

**Comment by mattstratton** [comment]
To add some clarity - the idea that was discussed in slack (or at least as I see this) is not that something will be set in yaml, etc, but rather we'll create a new shortcode that basically just takes the form URL or whatever as its parameter (shortcodes are useful).

**Comment by bridgetkromhout** [comment]
Much like with the videos, I question how this is easier or more useful than the normal "embed all the stuff they give ya".

**Comment by mattstratton** [comment]
Basically because IIRC, you can't mix markdown and HTML on a page. So since we prefer the content pages in markdown....

**Comment by mattstratton** [comment]
Closing in favor of tracking it here - https://github.com/devopsdays/devopsdays-theme/issues/230
