### ISSUE TITLE
automate the aliasing of a "current" url

### ISSUE THREAD

**Issue by bridgetkromhout** [devopsdays/devopsdays-web#8195]
A number of cities use a shortlink that just takes people to their current year, and then sometimes forget to update it for the next year. Let's look into adding an alias for the most recent year that's been published, so:

devopsdays.org/minneapolis goes to https://devopsdays.org/events/2019-minneapolis/welcome/
devopsdays.org/seattle goes to https://devopsdays.org/events/2020-seattle/welcome/
devopsdays.org/helsinki goes to http://devopsdays.org/events/2014-helsinki/

**Comment by mattstratton** [comment]
This would be handled most likely in the redirects file; automating might be sketchy since we manually make changes to that file too. 

But `sed` might come to the rescue

**Comment by mattstratton** [comment]
I'm thinking that what we could do is this:

Start by manually creating all the aliases in `static/_redirects`. An example would look like this:
```
/seattle		/events/2020-seattle
```
Update the `utilities/add_new_event.sh` script to check for a line that matches to `$DOD_CITY`. If it matches, then replace the line with:
```
/$DOD_CITY    /events/$DOD_YEAR/$DOD_CITY
```
If it doesn't find a line for `$DOD_CITY` then it should create it.

The only tricky thing is that right now `mention-bot` is configured to request a review from @mattstratton if `static/_redirects` is touched. We likely would want to edit the `.mention-bot` file to remove this, as I don't want to get tagged in a review on every single new event :)

**Comment by mattstratton** [comment]
My bash-fu isn't as good as @bridgetkromhout 	so I am going to suggest this seems like a thing she could do :)

**Comment by bridgetkromhout** [comment]
I'll take a look. It would be better if we could include a different file in `static/_redirects` but that doesn't look feasible. Maybe using the toml file instead is a better option.

**Comment by mattstratton** [comment]
What we *could* do is move the existing redirects to the netlify config file, so that `_redirects` is only used for this purpose.

The main reason I wanted to be notified on it was to make sure nobody breaks any existing redirects. Frankly, as long as PR merge folks are watching the changes in that file it's Probably Fine.

**Comment by mattstratton** [comment]
FWIW, making changes to `netlify.toml` is WAY scarier for things getting messed up that `_redirects`, as the latter only does one thing. So I really don't want a process or PR's to touch the `netlify.toml` file :)

**Comment by mattstratton** [comment]
I also realized just now that `netlify.toml` isn't in `.mention-bot` so I'm going to fix that :)

**Comment by bridgetkromhout** [comment]
Okay, the first pass at this is usable. Note that we have to use a city slug based on the event group if the event moves around like in Australia.

**Comment by bridgetkromhout** [comment]
I didn't move any of the existing "legacy" aliases, either. #probablyfine
