### ISSUE TITLE
improve speaker sharing image

### ISSUE THREAD

**Issue by bridgetkromhout** [devopsdays/devopsdays-web#8196]
Right now, when a speaker/talk page is linked, we get a generic sharing image for all of devopsdays. But we have items like the speaker's name or talk title available, as well as their picture, so we could generate something that looks better for embeds.

Current program item detail page:

![image](https://user-images.githubusercontent.com/2104453/64482614-83cdb500-d1f5-11e9-94eb-32cd0393621a.png)

Current speaker detail page:

![image](https://user-images.githubusercontent.com/2104453/64482616-95af5800-d1f5-11e9-897e-900f51c5d17f.png)

Example image we made manually...

![image](https://user-images.githubusercontent.com/2104453/64482660-7e249f00-d1f6-11e9-9a56-1372f10cecdf.png)

... to tweet about the talk: https://twitter.com/devopsdaysmsp/status/1138201836656238595

(Yes, I know we have a link to ticket buying, not the page, but we'll want the page itself.)

**Comment by bridgetkromhout** [comment]
We may also need to fix a bug that prevents images from showing up: https://github.com/devopsdays/devopsdays-web/issues/6538

**Comment by mattstratton** [comment]
There are two pr’s in right now that help with this!

**Comment by mattstratton** [comment]
Just to clarify - are you wanting these images to be generated by the build, or rather support the ability to have them exist? Creating image files is something that we *could* do, but we would need to write a bunch of janky javascript to run in the build pipeline. I think that the fix that allows folks to make their own and then attach them to the file is the right way to go.

**Comment by bridgetkromhout** [comment]
While auto-generation would be _nice_ I'm fine with starting at "support cards generated by something outside our build".

**Comment by mattstratton** [comment]
To capture what we just talked about, I don't want something that runs automatically in the build to do this, but I think it might be feasible to construct a gulp/npm task (or something) that you could run against your event that would auto-generated the files for you as a starting point.

**Comment by adrianmoisey** [comment]
> but I think it might be feasible to construct a gulp/npm task (or something) that you could run against your event that would auto-generated the files for you as a starting point.

Wow, that would be amazing!

**Comment by mattstratton** [comment]
I'm thinking we solved this by adding the ability to specify a specific image for social sharing per page (so you can add frontmatter to point to a "manually" created card for the speaker/talk). 

I really think that the "magic autogeneration of cards" is super out of our ability, so I propose closing this issue. @bridgetkromhout ?

**Comment by mattstratton** [comment]
Closing this issue - if we want to investigate the "magic autogeneration of social cards" we should create a new issue 

(Btw this is ... possible and there are new tech options to do this!)
