### ISSUE TITLE
Resize speaker and organizer images

### ISSUE THREAD

**Issue by nathenharvey** [devopsdays/devopsdays-web#8198]
Commit daeeb1e updated the site to use css to resize images.

This may have had some unintended consequences for images that are larger than the space allowed.

Some images become very tall but not very wide:

<img width="922" alt="Baron_Schwartz_-_devopsdays_Chicago_2019" src="https://user-images.githubusercontent.com/16093/64483328-3bd57f00-d243-11e9-8a9f-7cf06bc98926.png">

Was this the intent?

**Comment by nathenharvey** [comment]
The attached patch should update the scss properly but I've not been able to get from updated scss to updated css.

[0001-Changes-size-of-speaker-and-organizer-images.txt](https://github.com/devopsdays/devopsdays-web/files/3587285/0001-Changes-size-of-speaker-and-organizer-images.txt)

**Comment by nathenharvey** [comment]
@mattstratton can you take a look at this?

**Comment by bridgetkromhout** [comment]
Thank you, @nathenharvey! Definitely @mattstratton's wheelhouse.

**Comment by mattstratton** [comment]
The good news is that I have a PR in that will let non-Matt people build fixes to SCSS :)

**Comment by mattstratton** [comment]
OK, I just tested this patch and the images are too small.

![image](https://user-images.githubusercontent.com/1280666/64497825-c5527480-d276-11e9-952c-1603ff5f5d84.png)

![image](https://user-images.githubusercontent.com/1280666/64497835-d26f6380-d276-11e9-8d88-f1687e1b79e8.png)

I'll do some more experimenting, but this particular fix isn't quite there.

**Comment by nathenharvey** [comment]
Sounds good.  lmk if I can help!

**Comment by bridgetkromhout** [comment]
@mattstratton even if the images are slightly too small, I think that's preferable to weirdly cropped. Can we have that as an incremental improvement?

**Comment by mattstratton** [comment]
I'll work on it today. I am not sure why @nathenharvey 	added the change to organizer images, as they seem to be working without crops today.

**Comment by nathenharvey** [comment]
It looks to me like the page is limiting the organizer photos to 298px wide.  It's probably fine to leave the css alone for those though.

<img width="1680" alt="298" src="https://user-images.githubusercontent.com/16093/64968889-e9164b80-d870-11e9-8294-4d6231d2a6c0.png">

**Comment by mattstratton** [comment]
Yep, it seems to work at all breakpoints (the image fills the card)

**Comment by mattstratton** [comment]
![image](https://user-images.githubusercontent.com/1280666/64970251-0a743900-d86b-11e9-832b-d725e60e7ac8.png)

**Comment by mattstratton** [comment]
Ideally I want to find an example where the source image isn't the proper size and test with that (for speakers especially)

**Comment by mattstratton** [comment]
Specifically, we want to find one where the image is not square :)

**Comment by bridgetkromhout** [comment]
Here's your test case image: https://devopsdays.org/events/2019-porto-alegre/speakers/andreza-rocha/ - https://github.com/devopsdays/devopsdays-web/blob/master/static/events/2019-porto-alegre/speakers/deza.jpg

**Comment by mattstratton** [comment]
Perfect. Thank you for the detective work, @bridgetkromhout 	!

**Comment by mattstratton** [comment]
Note to self - https://themetry.com/css-image-cropping/

**Comment by mattstratton** [comment]
I think I might have fixed it, and I'm not sure why I had to make the change I did (I mean, I know why making this change fixed it, but not sure why the thing I am undoing was done - and since it was done by me, I have nobody to blame but myself)
