### ISSUE TITLE
weird issue with blog listing in footer

### ISSUE THREAD

**Issue by mattstratton** [devopsdays/devopsdays-web#8219]
It seems like the footer is trying to load the blog section itself as a page, so this happens:

![Screen Shot 2019-09-08 at 7 47 12 PM](https://user-images.githubusercontent.com/1280666/64497214-c503aa80-d271-11e9-8e09-f4dd5f1aba74.png)

**Comment by mattstratton** [comment]
The solution is probably going to be moving the template code for the `/blog` out of `sections` and into its own template; see mattstratton/castanet for examples. We also will need to make sure the `/blog` page is called `_index.md` (this is a known hugo thing that changed several versions ago, and I had to solve for it in castanet)

**Comment by bridgetkromhout** [comment]
I looked at this, and although I wasn't clear on what "sections" is, I did see a number of possible cosmetic improvements to how we display everything around blogs, so I submitted those in https://github.com/devopsdays/devopsdays-web/pull/9209.
