### ISSUE TITLE
Performance of uncached local builds of the site

### ISSUE THREAD

**Issue by don-code** [devopsdays/devopsdays-web#8305]
Building the DevOpsDays site on my laptop, when plugged in, kicks up the fan and takes over five minutes:
```
                   |  EN   
+------------------+------+
  Pages            | 7228  
  Paginator pages  |    2  
  Non-page files   |   74  
  Static files     | 8592  
  Processed images |    0  
  Aliases          |  489  
  Sitemaps         |    1  
  Cleaned          |    0  

Total in 311477 ms
```

Today I built it on a train ride, for which I kept the laptop in power save mode to conserve battery, which took 24 minutes:
```
                   |  EN   
+------------------+------+
  Pages            | 7228  
  Paginator pages  |    2  
  Non-page files   |   74  
  Static files     | 8592  
  Processed images |    0  
  Aliases          |  489  
  Sitemaps         |    1  
  Cleaned          |    0  

Total in 1441323 ms
```

By removing events from 2018 and prior, the five minutes becomes just north of one:
```
                   |  EN   
+------------------+------+
  Pages            | 2903  
  Paginator pages  |    2  
  Non-page files   |   38  
  Static files     | 8592  
  Processed images |    0  
  Aliases          |  216  
  Sitemaps         |    1  
  Cleaned          |    0  

Total in 76134 ms
```

That said, one possible solution would be to prerender old events which would no longer change, and serve them as static assets rather than dynamically-generated content. Is there any interest in that solution? I'd be happy to build a tool that does it, and PR in the result of running it for 2018 and prior.

**Comment by bridgetkromhout** [comment]
> one possible solution would be to prerender old events which would no longer change, and serve them as static assets rather than dynamically-generated content.

This is something @mattstratton has done periodically in the past, and it's likely time to do it again.

**Comment by mattstratton** [comment]
The being said, if @don-code wants to write a script or tooling to automate it I’m good with that too :)

**Comment by mattstratton** [comment]
You can’t remove the data files for old events btw because the /events page uses them to build the list of past events :)

**Comment by mattstratton** [comment]
Here’s an example of an event that has been moved to `static`

https://github.com/devopsdays/devopsdays-web/tree/master/static/events/2016-chicago

**Comment by bridgetkromhout** [comment]
Here's a PR to archive 2017 and some of 2018 (the ones that have run again in 2019): https://github.com/devopsdays/devopsdays-web/pull/8332

**Comment by bridgetkromhout** [comment]
Hi, @don-code - I think you'll find that your build times are significantly improved if you rebase from upstream master. Thanks.

**Comment by don-code** [comment]
Thank you for #8332! Our event is coming up in four days, so I'll likely action this issue with some automation for future years once I get some time back afterwards.

**Comment by bridgetkromhout** [comment]
I additionally archived late 2018 in https://github.com/devopsdays/devopsdays-web/pull/8983.

This is a pretty trivial process, but in doing so, we've noticed that we could improve the process to ensure we don't end up with broken links from updated sponsors and missing links to newer events: https://github.com/devopsdays/devopsdays-web/pull/8983#issuecomment-571371180

**Comment by bridgetkromhout** [comment]
Is there additional work in the scope of performance improvements, @mattstratton? If not, I suspect this issue is as solved as it's going to get.

**Comment by mattstratton** [comment]
Given that we are tracking overall performance things in #7949, I think we can close this one.
