### ISSUE TITLE
Builds on legacy.devopsdays.org not working properly

### ISSUE THREAD

**Issue by bridgetkromhout** [devopsdays/devopsdays-web#8363]
Leaving aside the "do we really need a different repo for that stuff at this point? Can't we just put it with the other static stuff now?" question, I have a build failure (https://app.netlify.com/sites/devopsdays-legacy/deploys/5d8648280373a30008790102) from trying to fix links (https://github.com/devopsdays/devopsdays-legacy/pull/5).

**Comment by bridgetkromhout** [comment]
Okay, looking at https://github.com/devopsdays/devopsdays-web/issues/8195 and at the current redirect contents, I _do_ want to re-open the question of migrating this content (in static form) back to the main repo. @mattstratton, your thoughts are welcome.

**Comment by mattstratton** [comment]
If we add all those static files the deploy previews will be even slower since it will have to upload all them on every deploy preview. Just a thought.

**Comment by bridgetkromhout** [comment]
> If we add all those static files the deploy previews will be even slower since it will have to upload all them on every deploy preview. Just a thought.

True facts. Minimal difference, though - marginal change from what we have now.

**Comment by mattstratton** [comment]
How many files will it be adding?

**Comment by bridgetkromhout** [comment]
Just noticed https://legacy.devopsdays.org/events/2009-ghent/ is giving me "too many redirects", so maybe my attempt at a build broke something?

**Comment by mattstratton** [comment]
Can you post a link to the build that you’re referencing?

**Comment by bridgetkromhout** [comment]
The build I thought might have broken something apparently did not - https://legacy.devopsdays.org/events/2009-ghent/ is working today. When I said "build" I was talking about this: "I have a build failure (https://app.netlify.com/sites/devopsdays-legacy/deploys/5d8648280373a30008790102) from trying to fix links (devopsdays/devopsdays-legacy#5)."

**Comment by bridgetkromhout** [comment]
@mattstratton ping because I think the legacy pages may not be building at all, and I'm not sure how that's set up.

**Comment by mattstratton** [comment]
They don’t “build”; they’re just static files. Netlify has to have a “build” command but i think it basically just serves up the static files.

**Comment by mattstratton** [comment]
I suspect that the way I used to do this doesn’t work on Netlify anymore since it hasn’t deployed since 2017.

**Comment by bridgetkromhout** [comment]
When we fix this, I'd like to ensure this change is properly visible: https://github.com/devopsdays/devopsdays-legacy/pull/5

**Comment by mattstratton** [comment]
I believe this is fixed; the last build I did for legacy (which succeded) shows the following two changed files uploaded:

```
events/2010-sydney/index.html
events/2011-melbourne/index.html
```

If that's the ones that hadn't been built, then I think we are good. When @bridgetkromhout gets a chance to eyeball them to make sure the change went through, this issue can be closed.

**Comment by bridgetkromhout** [comment]
Yes, this is working correctly. Thanks, @mattstratton!
