### ISSUE TITLE
preventing confusion of global vs local when contacting organizers

### ISSUE THREAD

**Issue by bridgetkromhout** [devopsdays/devopsdays-web#84]
Most of the mistaken emails to info@devopsdays.org come because people want these things:

1) To contact a specific event whose page they were viewing (I think they click "Contact" at the top - every sub-site should have an obvious "contact the local team" that supercedes "contact the global team.)

2) To create a sponsorship or attendee deal across multiple events (I think it needs to be way more obvious they can't - maybe start them with a contact form instead, and explain it there.)

**Comment by mattstratton** [comment]
I think that including capability for contact forms is totally do-able...mailgun provides 10,000 free emails/month for api-driven calls (it's what we are using on the CFP for chicago site). Adding in some default contact forms for the various page templates would be useful too I think.

**Comment by bridgetkromhout** [comment]
I do not want us to be in the business of running mailgun or anything else for people. Contact forms can be embedded in an iframe (discussed in https://github.com/devopsdays/devopsdays-web/issues/80) as desired. What I was intending with this issue was more content-driven.

I've rewritten http://www.devopsdays.org/sponsor/ which is now a single source of truth for the second point. To do: rewrite http://www.devopsdays.org/contact/ to make it more obvious who would be contacted.

**Comment by bridgetkromhout** [comment]
> rewrite http://www.devopsdays.org/contact/ to make it more obvious who would be contacted.

Done. While this could be optimized a lot more, I'm happy with it as-is and don't think we need a form right now.
