### ISSUE TITLE
fix event_map shortcode default

### ISSUE THREAD

**Issue by bridgetkromhout** [devopsdays/devopsdays-web#8458]
If no lat/long coordinates are set, event_map doesn't use location_address as one might expect. Instead, it defaults to the middle of the map. Which is hilariously in the ocean and makes no sense.

Test case:
```
coordinates: "" # The coordinates of your city. Get Latitude and Longitude of a Point: http://itouchmap.com/latlong.html
location: "Ed. Metropolitan Tower" # Defaults to city, but you can make it the venue name.
location_address: "Rua dos Mundurucus, 3100, Cremação, Belém, PA" 
```
<img width="567" alt="Screen Shot 2019-10-01 at 2 16 44 PM" src="https://user-images.githubusercontent.com/2104453/65995555-63db8b00-e45b-11e9-8d72-422e235e4fc2.png">

It would be better to try mapping the location_address instead.

**Comment by mattstratton** [comment]
I suspect this is more logic than a shortcode can do (we can’t call API’s and stuff)

**Comment by mattstratton** [comment]
Maybe the shortcode can check to make sure the coordinates are set, and if not...well, what should happen? Nothing? That's the best case I can think of, but the person using it won't know why?

**Comment by mattstratton** [comment]
I think that is the best solution at this time - if the coordinates aren't set, then the shortcode doesn't return anything. 

The only other option would be to have it instead return a big red NO COORDINATES message on the page, but what happens if someone doesn't set the coordinates and doesn't test it, so nobody notices? :)

**Comment by mattstratton** [comment]
well this is fun; I guess I forgot about this when we removed all the google maps stuff. so it's even more broken but the defaul location.md template includes it (commented out) so I should fix it!
