### ISSUE TITLE
more clarity around sponsorship guidelines

### ISSUE THREAD

**Issue by bridgetkromhout** [devopsdays/devopsdays-web#85]
Right now we have some info on the template sponsor page and some on the organizing guidelines, and none of it is aimed directly at the "So you want to sponsor... here's what you should know" market. I'd like to fix that at the top-level (not city or year specific).

Ideal result: a single URL to give to potential sponsors and/or existing sponsors who don't understand how sponsoring a devopsdays works (usually around lead-gen).

**Comment by mattstratton** [comment]
Something like devopsdays.org/sponsorship as the url, and it would be a page that has the sponsor guidelines. Probably also really good for SEO for people looking to spend money on devopsdays :)

**Comment by phrawzty** [comment]
Might also be worth noting up front that sponsorship *doesn't* entitle the sponsor to data harvesting in the form of attendee lists (etc).

**Comment by bridgetkromhout** [comment]
Resolved in https://github.com/devopsdays/devopsdays-web/issues/201.
