### ISSUE TITLE
Migrate hosting to Netlify

### ISSUE THREAD

**Issue by mattstratton** [devopsdays/devopsdays-web#854]
This is to track the migration of web hosting from GH Pages to Netlify.

The work needed is as follows:

- [x] Create `devopsdays/devopsdays-legacy` GitHub repo for the static content of the older webby-driven stuff.
- [x] Set up `legacy.devopsdays.org` Netlify build/hosting for older, webby-driven content (from the `devopsdays/devopsdays-legacy` repo)
- [x] Add proper redirects to `www.devopsdays.org/*` for all site-level links on `legacy.devopsdays.org`
- [x] Create `legacy.devopsdays.org` in Cloudflare, pointing to appropriate cname for Netlify.
- [x] Write redirect rules on existing Netlify build system for `devopsdays-web` for the older events, redirecting to `legacy.devopsdays.org`
- [x] Update Cloudlfare to point to Netlify for `devopsdays.org` and `www.devopsdays.org`
- [x] Remove wercker hooks
- [x] Delete all of the stuff in `/static/events` for the legacy sites
- [x] Have @yvovandoorn do his magic history-rewriting to remove those static directories

**Comment by mattstratton** [comment]
I started writing the redirect rules, and they seem to be working okay. 

If you visit http://devopsdays-legacy.netlify.com/events/2009-ghent/ and click on `Home`, it will take you to `www.devopsdays.org`.

One thing I noticed is that the event pages have the blue nav bar at the bottom, which lists other events, and it's of course going to keep being out of date (since we don't keep building it):

![devopsdays_ghent_2009](https://cloud.githubusercontent.com/assets/1280666/17704326/5f3af71a-639a-11e6-87f9-a2cc29c784f6.png)

I'm thinking we should just whack the bottom blue nav from `legacy` URL's; mostly because there is no way we can keep it up to date. We lose a bit of the traffic to upcoming events that way, but I don't really see a way around it. Thoughts?

**Comment by bridgetkromhout** [comment]
> I'm thinking we should just whack the bottom blue nav from legacy URL's

Yes. I created that particular attempt at nav in mid-2015 or so. It's not necessary to keep it.

**Comment by mattstratton** [comment]
I've removed the blue bar from legacy :)

**Comment by yvovandoorn** [comment]
I'm all about the magic 👍

**Comment by mattstratton** [comment]
DNS has been updated. I do not want to remove the legacy code for a few days while DNS updates (DNS has to be updated for the legacy redirects to function)

**Comment by mattstratton** [comment]
This PR is in place to remove the static files for legacy:

https://github.com/devopsdays/devopsdays-web/pull/971

**Comment by mattstratton** [comment]
The wercker build application has been removed. We just need to removew the `wercker.yml` file for hygiene.

**Comment by yvovandoorn** [comment]
The repo has been rewritten with `/static/events` cleaned up out of history.

**Comment by mattstratton** [comment]
And with that...this is resolved!
