### ISSUE TITLE
make contact shortcodes display in a prettier manner

### ISSUE THREAD

**Issue by mattstratton** [devopsdays/devopsdays-web#856]
Right now, the `list_core.html` and `list_organizers.html` shortcode templates are using some less than delightful unstyled elements to display. We need to do the following:
- [ ] Design the UX for the contact page (or at least those two elements)
- [ ] Update the shortcodes to use this styling

**Comment by bridgetkromhout** [comment]
The main thing I want is to visually allow for the local team to have twitter handles, employers, etc (so they need to be in a list/table/something), while I want to keep the core team from taking up a ton of vertical space (which is why it's just comma-delimited in the two groups).

**Comment by mattstratton** [comment]
I pushed this to 3.0 because it will be a factor in overall UX of the redesign.

**Comment by mattstratton** [comment]
Closing to track it in the theme development - https://github.com/devopsdays/devopsdays-theme/issues/231
