### ISSUE TITLE
Remove LinkedIn and Google group from footer

### ISSUE THREAD

**Issue by mattstratton** [devopsdays/devopsdays-web#859]
Because they are inactive. Thoughts on the Google group link?

**Comment by bridgetkromhout** [comment]
I'd remove them all and link in the footer to more useful stuff about the site itself.

**Comment by mattstratton** [comment]
@bridgetkromhout do you have any suggestions as to what those "more useful stuff about the site itself" might be?

Some ideas:

- replicate top nav (this is fairly common practice in a footer; it might look a little silly on the homepage, because it's such a "short" page, but for longer pages, when you scroll all the way down, having text links to nav is helpful)
- copyright information (kind of tough to do, since "devopsdays" isn't really an organization that can have copyright, erm, maybe it can?)
- link to privacy policy (we actually kind of need one since we use google analytics; it's pretty easy to generate one and it's a good practice these days)
- rss icon next to the twitter one for the blog feed (assuming people besides Bridget start posting blog articles

**Comment by bridgetkromhout** [comment]
> replicate top nav

Eh. I kinda think we decided against this because clutter?

> copyright information

nope nope nope (way too local-specific)

> link to privacy policy 

hmm, okay. also code of conduct for the overall org?

> rss icon next to the twitter one for the blog feed 

let's start with this (to go with the twitter one)

I could also see value to an email icon going to the contact page, especially if we also populated the contact page with clickies to currently active events?

**Comment by jedi4ever** [comment]
fwiw - the google group used to be a way to:
- announce new events via email
- have people announce their intent of new events
- have attendees get in touch
- doing a blast email

so it might make more sense to have a kinda mailchip like subscription model where you are informed on new events

**Comment by mattstratton** [comment]
I'm going to suggest that for this iteration, we revamp the footer to only have the twitter link, change the email icon to link to the `contact` page, and add the RSS link, removing LinkedIn and Google Group.

Here are some issues I opened to refer to some specific tasks around this discussion:

#876 - discuss adding a mailchimp announce list to replace google group
#875 - add link to code of conduct in the footer
#874 - create privacy policy and add link in footer
