### ISSUE TITLE
update make_new_event.sh to support dashes in city names

### ISSUE THREAD

**Issue by mattstratton** [devopsdays/devopsdays-web#860]
We prefer to have the city names (for the slug, not the value of `city`) use dashes if there are spaces in the city name (i.e., "Salt Lake City" should be `2016-salt-lake-city`.

The script needs the following:

- [ ] Prompt the user to enter their city name with dashes if it has spaces
- [ ] Add the ability to set a specify city name (which will be inserted as `displayname` in the data file). Have the default for this (if the user hits "enter") be what was set before in the city name prompt. This should prompt that they only need to do this if the city has spaces or special characters.
- [ ] Update to use `$cityabbr` instead of `$city` when setting paths/data file names

**Comment by bridgetkromhout** [comment]
This is complete for the creation of new cities (in the new event script). We'll need to deal with in-flight cities on a case by case basis.

I solved this by allowing "city" to have special characters, and by urlizing "name".

**Comment by bridgetkromhout** [comment]
Fixed in https://github.com/devopsdays/devopsdays-web/pull/912.
