### ISSUE TITLE
reconcile code that references "displayname" parameter

### ISSUE THREAD

**Issue by mattstratton** [devopsdays/devopsdays-web#861]
When trying to solve for cities with special characters, there was some work intending to create a `displayname` parameter for events. 

This seems to have turned out to not be needed, as we handled it by allowing `city` to have special characters and spaces, etc. However, there are several places in the codebase the still refer to this. It's not breaking anything, but it's going to get confusing.

Here are the places I found:

https://github.com/devopsdays/devopsdays-web/blob/master/themes/devopsdays-responsive/layouts/partials/event_header.html#L14

https://github.com/devopsdays/devopsdays-web/blob/master/themes/devopsdays-responsive/layouts/partials/past.html#L33

https://github.com/devopsdays/devopsdays-web/blob/master/themes/devopsdays-responsive/layouts/partials/future.html#L29

https://github.com/devopsdays/devopsdays-web/blob/master/themes/devopsdays-responsive/layouts/partials/upcoming_headline.html#L8

https://github.com/devopsdays/devopsdays-web/blob/master/README.md

Since the value `displayname` doesn't exist in any of the data files, including cities with special characters, this doesn't seem to be needed after all.

**Comment by mattstratton** [comment]
Actually, we might want to keep this, as the intention of this would (I think) solve for #858 properly. We just need to fix the two events that were created "incorrectly" (Zurich and Brasilia).

**Comment by mattstratton** [comment]
Let's discuss it some more, but I think that the right answer is to keep the `displayname` code, and retro-fix the two events (Brasilia and Zurich) that are using it incorrectly.

We do need to fix the `make_new_event.sh` script to use this properly.

**Comment by bridgetkromhout** [comment]
I'm solving this by getting rid of displayname and no longer parsing "city" (it's just for display).

**Comment by bridgetkromhout** [comment]
Fixed in https://github.com/devopsdays/devopsdays-web/pull/912.
