### ISSUE TITLE
modify event page menu to use bootstrap elements

### ISSUE THREAD

**Issue by mattstratton** [devopsdays/devopsdays-web#862]
This was introduced in #834, but we need to discuss it and determine what the UX should be like.

Screenshot: https://github.com/adrianovieira/devopsdays-web/wiki/redesign_event_header_menu_themes_devopsdays

I'm closing the PR for now, but let's use this issue to discuss the use of bootstrap elements on the event menu.

**Comment by bridgetkromhout** [comment]
I'm interested in knowing what problem we're trying to solve. The proposed change led to some less-than-appealing visual artifacts.

**Comment by mattstratton** [comment]
This probably goes in the 3.0 milestone. I'm also really pretty sure that we are abusing HTML tags in these current menus, which can give us some weird behavior. 

I'd rather let this go until redesign and make sure that the new UX is built using proper framework structure, irrelevant of what the designer mocks up (it should not LOOK like bootstrap but can use bootstrappy things)

**Comment by mattstratton** [comment]
This is basically a feature of [devopsdays-theme](https://github.com/devopsdays/devopsdays-theme) so I'm closing this one out.
