### ISSUE TITLE
Put the map back 

### ISSUE THREAD

**Issue by mattstratton** [devopsdays/devopsdays-web#8639]
Folks have asked me at the organizer summit if we could add the map back. @toshywoshy and I discussed it :)

**Comment by bridgetkromhout** [comment]
I recall problems with both the automation not being that automagic and google adding rate limiting. Plus slow loading and looking janky. I’m willing to dig into it but I don’t want it to look/feel like the Web 1.0 style thing it did.

**Comment by MikeRosTX** [comment]
What about using Mapbox which is what [GitLab](**https://about.gitlab.com/company/team/**) uses?
https://www.mapbox.com

**Comment by bridgetkromhout** [comment]
@mattstratton would know for sure, but I think https://www.mapbox.com/pricing/ would put us in the "contact sales" bucket, same problem we have with google maps.

To be clear, I do not think we should have a map. But if others decide we should, then I do not want to spend money on it. :)

**Comment by mattstratton** [comment]
given the way pricing works etc now, i think it would be not great to use the old map. closing this one.
