### ISSUE TITLE
Sharing images are not working

### ISSUE THREAD

**Issue by mattstratton** [devopsdays/devopsdays-web#8659]
Looking at https://devopsdays.org/events/2019-chicago/welcome/, you can see that even though a sharing image exists in the directory, it is setting the default devopsdays sharing image.

I also see that Facebook sees this

```
og:image:alt | Devopsdays Des Moines
```

**Comment by mattstratton** [comment]
OK, here's why sharing images aren't working:

```
{{- if (where (readDir ($.Scratch.Get "contentdir")) "Name" "sharing.jpg") -}}
```

Sharing images are located in the `sharing` subdirectory of an event now.

**Comment by mattstratton** [comment]
I think that if we fix where the `contentdir` variable is, like this, it will fix it:

```
{{- $.Scratch.Set "contentdir" (printf "static/events/%s/sharing/" ($.Scratch.Get "subdir")) -}}
```

**Comment by mattstratton** [comment]
I'm not sure what in the page is looking for the old path to sharing images though...

![Screen Shot 2019-11-01 at 10 48 49 AM](https://user-images.githubusercontent.com/1280666/68037361-8d274b00-fc95-11e9-8a21-a9735151792d.png)

**Comment by bridgetkromhout** [comment]
> I also see that Facebook sees this
> og:image:alt | Devopsdays Des Moines

As far as I can tell, no Chicago assets on the site would have that as their alt text. Is it possible FB is saving the alt from last time it saw that specific image, which would be kinda terribad?

```
$ grep -r "Devopsdays Des Moines" *
content/events/2020-des-moines/location.md:Devopsdays Des Moines will be returning to the Community Choice Credit Union Convention Center (http://www.iowaeventscenter.com/convention-center) for our 2020 event.
content/events/2019-des-moines/location.md:Devopsdays Des Moines will be returning to the Community Choice Credit Union Convention Center (http://www.iowaeventscenter.com/convention-center) for our 2019 event.
data/events/2020-des-moines.yml:description: "Devopsdays Des Moines is returning for 2020!" # Edit this to suit your preferences
static/events/2018-des-moines/welcome/index.html:<meta property="og:title" content="Devopsdays Des Moines 2018" />
Bridgets-MacBook:devopsdays-web bridget$ 

```

**Comment by mattstratton** [comment]
Yeah, I think the right thing to do is to explicitly set the `og:image:alt` tag, since FB is trying to infer it somehow.

**Comment by bridgetkromhout** [comment]
I am concerned that changing the base contentdir will affect more than this specific case we're trying to fix. I would suggest we leave this as-is:

`{{- $.Scratch.Set "contentdir" (printf "static/events/%s/" $e.name) -}}`

Then change this:

`{{- if (where (readDir ($.Scratch.Get "contentdir")) "Name" "sharing.jpg") -}}`

to 

`{{- if (where (readDir ($.Scratch.Get "contentdir")) "Name" "sharing/sharing.jpg") -}}`

**Comment by mattstratton** [comment]
In that file, the `contentdir` variable is used only for locating where the sharing images are. 

I don't know that your example works that way; I can test it, but looking at other code I've written, I've had to play games with strings to create the path. the "Name" parameter only takes a filename (otherwise we wouldn't be using `contendir` at all)

**Comment by mattstratton** [comment]
I am okay with maybe renaming the variable from `contentdir` to `sharingdir` to make it clear what it's used for, though.

**Comment by bridgetkromhout** [comment]
Ah okay, if it's not going to be used for "anything in that directory" and is only used for "anything in the sharing directory", then a more specific name would be less confusing.

**Comment by adrianmoisey** [comment]
> Yeah, I think the right thing to do is to explicitly set the `og:image:alt` tag, since FB is trying to infer it somehow.

Seems like a good thing to do.

> I am okay with maybe renaming the variable from `contentdir` to `sharingdir` to make it clear what it's used for, though.

I agree with this.

**Comment by adrianmoisey** [comment]
> I think that if we fix where the `contentdir` variable is (in `partials/head/seo.html`), like this, it will fix it:
> 
> ```
>   {{- $.Scratch.Set "contentdir" (printf "static/events/%s/sharing/" $e.name) -}}
> ```

I tried that, it doesn't seem to work:
> ERROR 2019/11/05 09:40:42 render of "page" failed: execute of template failed: template: event/single.html:4:8: executing "event/single.html" at <partial "head.html" .>: error calling partial: "/src/themes/devopsdays-theme/layouts/partials/head.html:36:19": execute of template failed: template: partials/head.html:2:4: executing "partials/head.html" at <partial "head/seo.html" .>: error calling partial: "/src/themes/devopsdays-theme/layouts/partials/head/seo.html:36:19": execute of template failed: template: partials/head/seo.html:36:19: executing "partials/head/seo.html" at <readDir ($.Scratch.Get "sharingdir")>: error calling readDir: failed to read directory "static/events/2020-tokyo/sharing/": open /src/static/events/2020-tokyo/sharing: no such file or directory


Alternatively, doing this also doesn't seem to work:
`{{- if (where (readDir ($.Scratch.Get "contentdir")) "Name" "sharing/sharing.jpg") -}}`

**Comment by mattstratton** [comment]
Aha. Yes; we need to check if the directory exists first. I don’t recall offhand exactly how, but we do something vaguely similar in the homepage template. I’ll look when I’m not on mobile :)

**Comment by mattstratton** [comment]
I'm doing a little bit more thinking on how to make this work better - there's a way that might work better, but it introduces a breaking change.

Right now, the theory is that the overall sharing image for an event is set by just putting a file with the right name in a directory. Specific pages can override this by specifying a specific file for that page in its frontmatter.

Here's a different implementation:

- if you want a event-wide sharing image, you put it in the `sharing` directory of your static folder. Then you set a new parameter in the datafile with the name of that sharing image to use. This is pretty good because then you can use either PNG or JPG, and name it whatever you want.
- If you want a page-specific sharing image (i.e., for a talk/speaker's specific page, etc) you put it in the `sharing` directory and specify the filename in the frontmatter

So the logic for the sharing url goes like this:

1. Is a frontmatter parameter specified? If yes, then use that
1. If no frontmatter specified, is there a filename in the datafile? if yes, use that
1. if no datafile field set, then use the default.

The only downside is that previous events that used the "just put it in the folder for the overall event sharing image" will break. It probably won't be terribly hard to figure out how many events have set this, and also it's likely only a "fix forward" issue; that is, I don't really care if the social sharing custom image for devopsdays chicago 2019 is wrong.

Thoughts? @bridgetkromhout @adrianmoisey ?

**Comment by mattstratton** [comment]
I did a search; these are the only events using a custom sharing file (bear in mind anything prior to 2019 has been moved to the static archive so we wouldn't touch them anyway):

```
./2020-poznan/sharing/sharing.jpg
./2018-boise/sharing/sharing.jpg
./2018-galway/sharing/sharing.jpg
./2017-chicago/sharing/sharing.jpg
./2020-boise/sharing/sharing.jpg
./2018-copenhagen/sharing/sharing.jpg
./2020-houston/sharing/sharing.jpg
./2017-singapore/sharing/sharing.jpg
./2019-boise/sharing/sharing.jpg
./2018-london/sharing/sharing.jpg
./2017-galway/sharing/sharing.jpg
./2017-kansascity/sharing/sharing.jpg
./2019-galway/sharing/sharing.jpg
./2019-poznan/sharing/sharing.jpg
./2018-hartford/sharing/sharing.jpg
./2019-hartford/sharing/sharing.jpg
./2017-cape-town/sharing/sharing.jpg
./2019-chicago/sharing/sharing.jpg
./2017-oslo/sharing/sharing.jpg
./2019-london/sharing/sharing.jpg
./2018-singapore/sharing/sharing.jpg
./2019-houston/sharing/sharing.jpg
./2020-baltimore/sharing/sharing.jpg
./2018-chicago/sharing/sharing.jpg
```

So...if I made this breaking change, I would just have to manually fix about 11 events to update to the new format (I wouldn't do it for 2018 and prior). I think the blast radius is pretty reasonable for this breaking change.

**Comment by mattstratton** [comment]
Note to myself - if this change is introduced, the docs at https://github.com/devopsdays/devopsdays-web/blob/master/utilities/README.md#social-sharing-image need to be updated too

**Comment by adrianmoisey** [comment]
> Thoughts? @bridgetkromhout @adrianmoisey ?

I like your idea. I think it works well. Having the parameter in the datafile makes more sense (to me at least) than just dropping a file into a directory.

**Comment by mattstratton** [comment]
OK, so I put in a PR that seems to fix all of this (it also sets the `og:image:alt` tag now too, which was a minor annoyance.

One thing I did was that the sharing images/URLs are no longer relative; we turned this off because we thought it was going to help with builds, but I don't think it turned out to matter (the point is that every single page in a deploy preview has to be uploaded; but I think we figured out that happened anyway). I'll see how this PR deploy builds to make sure.

**Comment by mattstratton** [comment]
Note: the build/deploy of a deploy preview is the same with this PR as with other PRs; note that the first production deploy when this gets merged will be longer than usual. We will want to watch for the next production deploy after the merge to see if it is impactful.
