### ISSUE TITLE
verify required ruby version

### ISSUE THREAD

**Issue by bridgetkromhout** [devopsdays/devopsdays-web#8715]
In running a manual build to attempt a date re-order (https://app.netlify.com/sites/devopsdays-web/deploys/5dc84abf95ff5f3ca847727f) I noticed a message about ruby that I don't remember us discussing yet:

```
11:38:04 AM: Now using node v9.4.0 (npm v5.6.0)
11:38:04 AM: Attempting ruby version 2.3.6, read from environment
11:38:05 AM: 
11:38:05 AM: ** WARNING **
11:38:05 AM: Using custom ruby version 2.3.6, this will slow down the build.
11:38:05 AM: To ensure fast builds, set the RUBY_VERSION environment variable, or .ruby-version file, to an included ruby version.
11:38:05 AM: Included versions: 2.6.2
11:38:05 AM: 
11:38:05 AM: Required ruby-2.3.6 is not installed - installing.
11:38:06 AM: Searching for binary rubies, this might take some time.
```

Is this the version we need? Do we want to try to speed things up by moving to a recommended version?

**Comment by mattstratton** [comment]
We don’t use ruby at all, so I think that’s just a general Netlify message? I’ll look at some other Netlify sites i have to see if it’s a red herring.

**Comment by mattstratton** [comment]
Looking at another Hugo/Netlify site, i see this:

```
6:11:14 AM: Attempting ruby version 2.3.6, read from environment
6:11:16 AM: Using ruby version 2.3.6
6:11:16 AM: Using PHP version 5.6
```

Point is the Netlify build container image just has all those runtimes; we don’t use them. And we don’t set anything about them.

**Comment by mattstratton** [comment]
Although that bit about the ruby version looks new. I’d be more interested in finding out from Netlify why this is happening since we don’t do anything with ruby.

**Comment by bridgetkromhout** [comment]
Yeah, the "this will slow down the build" warning is why it interested me.

**Comment by mattstratton** [comment]
It’s not doing that anymore so i think we can close this :)
