### ISSUE TITLE
create privacy policy and add link in footer

### ISSUE THREAD

**Issue by mattstratton** [devopsdays/devopsdays-web#874]
A privacy policy page needs to be created (based upon the services used by the site, which at this point I think is only Google Analytics).

Then we need to add a link to it in the footer; it should be a text link and NOT an icon link, and ideally towards the right (we can 🚲  🏠  over the placement of it in this thread).

**Comment by bridgetkromhout** [comment]
@mattstratton, will you please you draft the text for this privacy policy, since you have the most context for whatever we're doing with GA? Thanks.
