### ISSUE TITLE
add link to code of conduct in the footer

### ISSUE THREAD

**Issue by mattstratton** [devopsdays/devopsdays-web#875]
In #859, @bridgetkromhout suggested:

```also code of conduct for the overall org```

as an item to link to in the footer.

We need to determine if there is already a page that has this code of conduct (I don't think there is), and if not, create the page. And then provide a text link to it in the footer.

**Comment by bridgetkromhout** [comment]
>  a text link

Do we want to move away from the icon links? (I'm not sure if there's a good icon for CoC but presumably a hover-over would have text anyhow?)

**Comment by mattstratton** [comment]
I don't like moving away from the icon links, but I think with standard things like CoC or privacy policies, the web standard is to use text for them?
