### ISSUE TITLE
discuss adding a mailchimp announce list to replace google group

### ISSUE THREAD

**Issue by mattstratton** [devopsdays/devopsdays-web#876]
In #859, @jedi4ever suggested replacing the functionality of the somewhat-abandoned Google Groups with a Mailchimp (or mailchimp-like) announce mailing list for announcing new events, etc.

Here are a few things that need to be done:

- [ ]  Determine if we want to do this at all
- [ ] Decide upon the tool to be used (Mailchimp has been suggested and is the preferred option by me, but this is the time for anyone to bring up any issues with using Mailchimp)
- [ ] Set up a Mailchimp account with the owner being `info@devopsdays.org`
- [ ] Determine ownership of sending campaigns (I am suggesting this is the webteam)
- [ ] Determine the frequency/standards of the campaigns (they should not be totally ad-hoc; it's much preferred to send them on a somewhat standard frequency to not overload people)
- [ ] Create a policy/standards document for use for the campaigns, including the manner in which events can request inclusion of information (i.e., new event, registration goes live, CFP open, etc) to the campaign.

Based upon my experience with doing this for Arrested DevOps, creating as much simple automation around this as possible increases the likelihood of actually using it.

**Comment by mattstratton** [comment]
The first item in the list ("Determine if we want to do this at all") is the most critical right now. 

Here are the pros as I see them:

- For folks who prefer to be informed of stuff via email (which isn't organizer types weighing in on this, so we have to watch our bias), it gives them a channel to get updated other than remembering to check the website (which doesn't have a good way of finding out updating stuff currently)
- It might (keyword "might") cut down on some of the emails we get related to "is there X event happening", etc?

Here are a few cons:

- Adds work to the team (someone has to manage this)
- Potential for abuse (granted, we have the gatekeeper of the team to determine what gets sent to the list, but see "adds work to the team" above)
- Affects the decentralized notion of the core
- Adds additional privacy overhead concerns since we are adding a service that uses PII

**Comment by bridgetkromhout** [comment]
If people want announcement of new events via email, I think our best path is making it possible to subscribe to a feed of the changes on http://www.devopsdays.org/events/.

I am 100% against the core team operating a centralized mailing list, for all the "cons" reasons above.

**Comment by mattstratton** [comment]
I think that if there was a way to add a widget for "open CFP's", or "open registration", etc, type stuff to make it really visible to know that kind of thing, it would handle a lot of what someone would want from a mailing list. 

It's pretty dang hard to puzzle out what's open right now (I know this because we try to generate a list of that stuff for ADO related tasks).

**Comment by bridgetkromhout** [comment]
Working on "open CFPs" in https://github.com/devopsdays/devopsdays-web/issues/880.

**Comment by bridgetkromhout** [comment]
I think "open registration dates" would be a lot trickier because we don't have sites put that in their yaml. Since the CFP dates are in the yaml we can parse them out of a consistent place.

**Comment by mattstratton** [comment]
I think adding registration dates into the YAML would be a nice feature. Would allow for a more data-driven registration link too (could add logic that only displays registration if a date is set and it is `ge` now). Not a high priority feature, but not a bad one.

**Comment by mattstratton** [comment]
Since it seems that most folks are against this, I'm going to close it. There are a few features we might want to add to bubble up visibility of events, which we will handle in [3.0](https://github.com/devopsdays/devopsdays-web/milestone/6).
