### ISSUE TITLE
consider adding CONTRIBUTING.md file to repo

### ISSUE THREAD

**Issue by mattstratton** [devopsdays/devopsdays-web#879]
It may be a duplication of some of the content in the README, but I think having a `CONTRIBUTING.md` file that explains some of the nuance of contributions to the site (especially for shared code/design related items) would be beneficial. 

This is pretty standard for a lot of projects.

**Comment by bridgetkromhout** [comment]
Fine by me but let's avoid two sources of truth. Let's _move_ the contributing guidelines, not allow them to drift from each other in two places.

**Comment by mattstratton** [comment]
Good call. We can just link to the file in the README under "Contributing". The README is getting large anyway :)

**Comment by phrawzty** [comment]
Note that fully one third of the major headers in the README contain the string `Contribut`. 😄  I guess the "easiest" thing would be to just move those sections into CONTRIBUTE, but at first blush I'm not seeing the value add there. 

Perhaps I'm thinking about this the wrong way. If you'll indulge me, let's ask the most basic of all questions: What problem are we trying to solve❓

**Comment by mattstratton** [comment]
Two things:

1) It's pretty standard on a project to have a file called CONTRIBUTING, which is where I look to learn how to follow the process of contributing. The README is for users of the software, etc.

2) The README is getting really big, and contains a lot of details that aren't necessary for someone who just wants to "use" the software, (i.e., update it with their events). When we make the thing a giant "wall of text", then nobody reads anything.

**Comment by bridgetkromhout** [comment]
Renamed (https://github.com/devopsdays/devopsdays-web/pull/896) and I think this is now complete.

**Comment by mattstratton** [comment]
Fixed by #890
