### ISSUE TITLE
investigate gulp-rename upgrade

### ISSUE THREAD

**Issue by bridgetkromhout** [devopsdays/devopsdays-web#8872]
Greenkeeper opened a PR https://github.com/devopsdays/devopsdays-web/pull/8844. I don't want to leave it open indefinitely, so I'm closing it for now and making a note here so we can investigate it at some point.

**Comment by mattstratton** [comment]
Given that this isn't getting flagged as a security impact, there's really no reason to upgrade other than there is a new version. I'm saying close this and we'll deal with it if dependabot flags it for security reasons.
