### ISSUE TITLE
Update default Code of Conduct template

### ISSUE THREAD

**Issue by mattstratton** [devopsdays/devopsdays-web#8951]
When creating a new event via the script, there is a default Code of Conduct template that generates the CoC page. This template has been unchanged for many years, and it could likely stand with some modernization/updating. This issue is for tracking any feedback organizers (or other relevant parties) may have on this template, and working on updating it.

The template file is located at https://github.com/devopsdays/devopsdays-web/blob/master/utilities/examples/content/events/yyyy-city/conduct.md

**Comment by lizthegrey** [comment]
Suggest hiring outside experts to evaluate it, but in short term would suggest that we remove the obligation by victims to report misconduct to event organizers.

**Comment by somatorio** [comment]
I remember someone (@mattstratton?) sending this one at #general some time ago https://2019.jsconf.eu/code-of-conduct/ and i really like it :)

**Comment by MikeRosTX** [comment]
> I remember someone (@mattstratton?) sending this one at #general some time ago https://2019.jsconf.eu/code-of-conduct/ and i really like it :)

I **_really like A LOT_** jsconf.eu CoC. The **_ONLY part_** that I personally do not like or agree with, is the **_Anonymous Reporting_** for several reasons (again this my sole personal opinion):

1. If things escalated out of proportion to the extreme that lawyers need to get involved (have not seen it happen yet, but it can potentially happen) according to the United States Constitution Sixth Amendment, it guarantees the rights of criminal defendant (in this case the CoC violator) the right to know who their accusers are, the nature of the charges, and evidence against them. Outside the United States, the **_Anonymous Reporting_** could very well be accepted just fine.

2. If a person is filing an **_Anonymous Report_**, how will the filer (offended person) know if we, as the organizers fully investigated the report, and took whatever action was necessary to prevent a recurrence if we can’t guarantee following up with them directly on the anonymous report? How will they even know if actions were taken or the anonymous report simple dismiss and filed away? Talking to the CoC violator without corroborating evidence could potentially be interpreted as defamation of character if we present them with the anonymous report and not the offended person who filed the report.

**Comment by jjasghar** [comment]
If we are focusing on
> IV. If I am offended or harassed, I will inform people around me who make me feel safe and the event organizers. If I feel safe, at my discretion, I will inform those giving offense of the specific actions with the hope that the other party is well-intentioned and ignorant, but I am under no obligation to do so.

Maybe we should suggest "easily identifiable" people who can act right then and there? I forget what we called these humans at ChefConf, but i know @smurawski was one, and i remember the bright "orangy" shirt he wore. Someone mentioned in the channel that we should act right then and there, and I agree with this, if you don't act then the chance of something actually happening after the event is less them optimal.

Also If you are there by yourself, you might not know who could be safe to talk to, so having these humans as people you know are there to help without any question can be advantageous.

**Comment by bridgetkromhout** [comment]
The default template was an improvement over _literally nothing_ (the state of the art in 2014!) but today should be closer to https://confcodeofconduct.com/. I'll take this as an action item.

**Comment by bridgetkromhout** [comment]
The original template was partially based on https://confcodeofconduct.com/ and also included first-person statements. I've updated it to cover the additional cases in the current confcodeofconduct template and I've removed the first-person statements which contained unnecessary assumptions and assertions, per the discussion in this issue.

**Comment by bridgetkromhout** [comment]
The changes can be most easily seen in this rich diff: https://github.com/devopsdays/devopsdays-web/pull/8978/files?short_path=bc65d0f#diff-bc65d0ffa7a118dfa59033a917f0868e

**Comment by mattstratton** [comment]
I think that PR is a great improvement for the template.

It might be helpful if I update this issue title/description to also include the additional effort we have discussed, which is to add some content to the organizing guide to make suggestions about CoC process, etc.

**Comment by bridgetkromhout** [comment]
@mattstratton I made a minimal change to the organizing guide in that PR. I think any other updates to the organizing guide are out of scope for this immediate wording update.

**Comment by mattstratton** [comment]
I agree. Upon reflection, there should be a separate GH issue created for tracking the organizing guide update work.
