### ISSUE TITLE
Create data file format for event

### ISSUE THREAD

**Issue by mattstratton** [devopsdays/devopsdays-web#9]
File should live in `data/events` and be named YEAR-CITY.yml

Should contain various items such as sponsors, twitter, etc, that will drive lower level pages

**Comment by mattstratton** [comment]
After fighting a bit with date comparison in hugo, and combined with #30, I think that another field needs to be added called `status` which can be set to "past" or "current".

Suggestions welcome as to what the values should be...

**Comment by mattstratton** [comment]
I'm also still bikeshedding with myself about TOML vs YAML and have gone back and forth at least twice in implementation on this :)

**Comment by m1keil** [comment]
from what I've stumbled (and saw you did as well), it's YEARCITY.yml as `-` or `_` are forbidden to use.

Regarding #30, can events without dates be in past?

**Comment by mattstratton** [comment]
Per @bridgetkromhout, events can be posted before dates are set. So events without dates will be future, not past. 

Since Hugo doesn't like dates without times, etc, I've been using the "status" key in the event YAML file to determine past or current/future. This gives a bit more flexibility as to when events should be archived, etc.

**Comment by m1keil** [comment]
In that case, maybe instead of  `status: [past | current]` we should switch it to `future: [true | false]` ?
My general logic is that you can figure out if events are past or future by event end date. And `future` keyword is a marker to handle special case of events without dates set yet.

I might over thinking it as well.

**Comment by mattstratton** [comment]
The problem with using the date to decide if it's a current or past event is that hugo doesn't like dates without times, and that's adding overhead to the person creating the file to add some faked up timestamp. But we might be able to code around it. 

I think that you could also just assume if there is not date, it's a future event. Let's put it this way - if we can handle the datetime issue in datafiles from hugo, then this becomes a solved problem.

Reference: https://discuss.gohugo.io/t/trying-to-filter-data-files-based-upon-a-date-field/2114

**Comment by m1keil** [comment]
Great, I'll check that reference.

**Comment by mattstratton** [comment]
I think this is basically resolved. Discussion can continue in #133
