### ISSUE TITLE
Email button no longer working

### ISSUE THREAD

**Issue by adrianmoisey** [devopsdays/devopsdays-web#9009]
The email button (The @ in the image below) no longer works:
![image](https://user-images.githubusercontent.com/736329/72096405-d1346d00-3322-11ea-908d-6091132b1548.png)

The link points at:
```
mailto:?subject=devopsdays%20Chicago%20-%202020&body=https%3A%2F%2Fdevopsdays.org%2Fevents%2F2020-chicago%2Fwelcome%2F
```

It looks to me like the email address after `mailto:` is missing.

**Comment by adrianmoisey** [comment]
I searched the codebase, but couldn't find where this is configured.
I got a feeling it's in javascript somewhere.

**Comment by adrianmoisey** [comment]
> I got a feeling it's in javascript somewhere.

I also have a feeling that this is wrong too.

**Comment by adrianmoisey** [comment]
Ah, seems to be related to https://github.com/devopsdays/devopsdays-web/blob/434ee3c05be02f349bdbb1525c8318396d796761/themes/devopsdays-theme/layouts/partials/footer_scripts.html#L48 somehow

**Comment by mattstratton** [comment]
yep, that's coming from a jquery plugin I think. we use a plugin called "js socials".

**Comment by mattstratton** [comment]
oh that's not supposed to have an email address! it's not to email the team - it's to share the page via email.

**Comment by mattstratton** [comment]
Anyway, it's working as designed :)
