### ISSUE TITLE
consider removing twitter stream widget

### ISSUE THREAD

**Issue by bridgetkromhout** [devopsdays/devopsdays-web#91]
I see that in https://github.com/devopsdays/devopsdays-web/issues/22 we added this; I'm proposing we remove it. We get a fair amount of irrelevant spam (for example, https://twitter.com/G2G3/status/716675632105701377) and imo there's no reason we should be featuring on our site any unvetted thing that chooses to use a hashtag. Thoughts?

**Comment by mattstratton** [comment]
I'm totally fine with removing it. This does bring up the question of who needs to weigh in on design decisions. I'll open a new issue to discuss THAT.

**Comment by mattstratton** [comment]
See #94 for discussion of the discussion.

**Comment by bridgetkromhout** [comment]
Possible solution: https://github.com/jedi4ever/devopsdays-webby/pull/2699

**Comment by bridgetkromhout** [comment]
We solved this in https://github.com/devopsdays/devopsdays-web/pull/144.
