### ISSUE TITLE
New footer looks weird on small viewports 

### ISSUE THREAD

**Issue by mattstratton** [devopsdays/devopsdays-web#911]
![image](https://cloud.githubusercontent.com/assets/1280666/17834709/582c0394-6712-11e6-99e0-fe04a1a7f447.jpeg)

**Comment by bridgetkromhout** [comment]
I saw that too and thought it was (unintentionally) hilarious. :)

**Comment by mattstratton** [comment]
He's like peeking over the top!

**Comment by mattstratton** [comment]
fwiw, I feel like we just need to use something responsive in here (maybe each icon gets wrapped in a `div` for the breakpoints)

**Comment by mattstratton** [comment]
OK, it wasn't that simple, because the footer height is hard-coded, probably to get it to push down :)

**Comment by mattstratton** [comment]
Since the footer is being redesigned in devopsdays/devopsdays-theme, this doesn't apply anymore
