### ISSUE TITLE
jojomi/hugo:0.62.1 not found

### ISSUE THREAD

**Issue by dpnl87** [devopsdays/devopsdays-web#9151]
After the merge of #9007 I get the following error when I try to run `./hugoserver.sh`

`docker: Error response from daemon: manifest for jojomi/hugo:0.62.1 not found: manifest unknown: manifest unknown.`

When I revert to version 0.62.0 there is no issue starting the server.

**Comment by glasnt** [comment]
It looks like 0.62.1 was removed from Docker Hub, but 0.62.2 is a tag that currently exists on both GitHub and Docker for hugo.

@mattstratton @adrianmoisey Before we bump to 0.62.2 it may need a look over from one/both of you, as the [0.62.2 update is non-trivial](https://github.com/gohugoio/hugo/releases/tag/v0.62.2)

**Comment by adrianmoisey** [comment]
Whoops, sorry about that.

I've created https://github.com/devopsdays/devopsdays-web/pull/9157 to revert that back to 0.62.0.

**Comment by glasnt** [comment]
Thanks @adrianmoisey 
@dpnl87 thanks for the report! This has now been fixed.
