### ISSUE TITLE
Events misordered on sidebar on live site

### ISSUE THREAD

**Issue by glasnt** [devopsdays/devopsdays-web#9179]
The ALL EVENTS order on the live devopsdays site is... strange. 

The order on / is broken, but the order on /events is fine. The order logic for both _seems_ the same (although duplicated, not sure why.)

The order doesn't seem to have any logic to it to me (it's not ordered by alphabetic month or any regular failure modes)

---

The devopsdays.org page
<img width="540" alt="devopsdays.org" src="https://user-images.githubusercontent.com/813732/72968340-63566e00-3e17-11ea-875f-0852aafa905e.png">

---

A Netlify PR in the last 6 hours rendered fine. 

<img width="550" alt="netlify PR 9178" src="https://user-images.githubusercontent.com/813732/72968349-65b8c800-3e17-11ea-9631-2c701ba5979a.png">

---

And my local fork that's in sync with master is also fine. 
<img width="542" alt="Screen Shot 2020-01-23 at 7 34 15 pm" src="https://user-images.githubusercontent.com/813732/72968360-68b3b880-3e17-11ea-9ab9-218df1d3a89a.png">

**Comment by mattstratton** [comment]
Yeah, this is a known issue that we have been trying to puzzle through for some time. 

https://github.com/devopsdays/devopsdays-web/issues/6539

We have a workaround which is when it happens, if we manually kick off a new build it usually fixes it. If you discover it, ping us in the #website channel on Slack and we can react to it!

**Comment by glasnt** [comment]
Thanks! From what I saw on web.archive.org it appeared to have only recently 'regressed'. This is a really interesting bug.

**Comment by mattstratton** [comment]
@glasnt yeah it’s inconsistent and happens sometimes :)
