### ISSUE TITLE
Where should non-image static files, like a sponsorship prospectus, for an event live?

### ISSUE THREAD

**Issue by WhatsChrisDoing** [devopsdays/devopsdays-web#92]
It wasn't clear where to a prospectus PDF in the repo. One possibility would be to create a pdf tree mirroring the img tree.

**Comment by mattstratton** [comment]
Actually, this is easily solved by changing the structure of the `/static` directory.

Right now, it is set up like this: `/static/img/events/yyyy-city`.

The proposed change would be to make it `/static/events/yyyy-city`. 

We can either have the `logo.png` (which is used by the code) dropped in the root of the `/static/events/yyyy-city` (resulting in `http://www.devopsdays.org/events/2016-ponyville/logo.png`) or have people create a `img` directory in there for their logo. I prefer to not have the overhead needed for the logo to be in a `img` directory as people have to remember to do so. You can create as many subdirectories as needed if you want to put OTHER images in `img` directory for your own purposes.

Changing this will be NBD right now as only `2016-atlanta`, `2016-chicago`, and `2016-minneapolis` have added logos so far, so I can do it manually.

If I get a :+1: on this, I'll make the change. It's easy.

**Comment by bridgetkromhout** [comment]
Removing the extraneous "img" entirely sounds like the best bet. 👍
