### ISSUE TITLE
Ability to control "Become a <level> sponsor" links 

### ISSUE THREAD

**Issue by WhatsChrisDoing** [devopsdays/devopsdays-web#93]
Extend the sponsor_levels array to include the number of sponsor slots at each level so that the "Become a <level> sponsor" can be automatically excluded for levels that are full.

**Comment by bridgetkromhout** [comment]
Thanks for working on this, @yvovandoorn. I think this might be best configured like this:

sponsor_levels:
    - id: platinum
      label: Platinum
      max: 3 # since Minneapolis already has 3, this would automatically remove the "become a..."
    - id: gold
      label: Gold
      max: 12
    - id: silver
      label: Silver
      number:   # left blank which makes the number unlimited

And here's an optional but related possibility:

    - id: host
      label: Host
      number: 1 # If one host sponsor is allowed, change "Host Sponsors" to instead display as "Host Sponsor".

Your option for turning off all "become a sponsor" messages on a city-wide basis is fine, but I suspect that the main uses of that would be "before the prospectus is done" and "when the conference is almost happening". So, an event-wide override like this might work:

sponsors_accepted: "yes"

I think it's fine for it to be a required field and could default to "no". Then people could turn it on when they're ready.

**Comment by bridgetkromhout** [comment]
Moving the discussion from https://github.com/devopsdays/devopsdays-web/pull/294#issuecomment-217731362, @yvovandoorn says:

> The biggest challenge I've been having with Hugo (and thus my limits) is how the logic around how to compare sponsor.level vs sponsor_levels.max works.

> Given this is my 4th day with Hugo (or Go in general) so far I've come this far:
```
      {{ else if ge var .max }}
         <div class = "sponsor-cta">
          <br>
       </div>
```

> My struggles:

> Is how to properly add up the levels set under sponsors.level against sponsor_levels.max.

> Example

> I have 4 sponsors:
```
 sponsors:
  - id: solvinity
    level: gold
  - id: stackstate
    level: gold
  - id: thoughtworks-products
    level: gold
 sponsor_levels:
  - id: gold
    label: Gold
    max: 2
```

> How do I count up the id 'gold' being used 3x under sponsors to fire off against (greater than or equal to) under sponsor_levels.max:2. Feels like there is a loop in involved and the sysadmin in me to use unix commands to determine the comparison. Obviously not appropriate here.

**Comment by bridgetkromhout** [comment]
@pmoosh and @ksatirli are also probably interested in this.

**Comment by bridgetkromhout** [comment]
Solved by @jyee in https://github.com/devopsdays/devopsdays-web/pull/737. Thanks, Jason!
