### ISSUE TITLE
update README to explain large files repo

### ISSUE THREAD

**Issue by bridgetkromhout** [devopsdays/devopsdays-web#941]
https://github.com/devopsdays/devopsdays-web#binary-files doesn't go into detail about https://github.com/devopsdays/devopsdays-assets and probably could have more guidance there. @mattstratton, can you resolve this or find the right person to do so? Thanks!

**Comment by mattstratton** [comment]
I'll add some color to that. I also am going to configure netlify to present a site at https://assets.devopsdays.org for all the files in the `devopsdays-assets` repo, to make linking to them easier.
