### ISSUE TITLE
Determine cut-off for read-only sites

### ISSUE THREAD

**Issue by mattstratton** [devopsdays/devopsdays-web#95]
Need to determine what the "cut off" is for sites to be migrated in a "read-only" state.

**Comment by mattstratton** [comment]
Duped in #97

**Comment by bridgetkromhout** [comment]
Is okay to have an issue for this! What I think we need to figure out: the date, and the process. The process might be messy - @mattstratton thinks sed & awk might be involved due to footers/headers.

**Comment by mattstratton** [comment]
See also #29 (existing issue) for discussion. Or we can close that issue and discuss it here.

**Comment by bridgetkromhout** [comment]
We determined the cut-off would be April 16th, per the timeline here: https://github.com/devopsdays/devopsdays-web/issues/96#issuecomment-208533653.
