### ISSUE TITLE
Feature request: Microformats2 markup for events

### ISSUE THREAD

**Issue by jamietanna** [devopsdays/devopsdays-web#9505]
[Microformats2](https://microformats.io/) is a standard that allows marking up HTML with machine-readable information, which allows better interoperability with various tools, as well as improving Search Engine Optimisation - https://www.seroundtable.com/google-support-microformats-28872.html (also https://www.jvt.me/posts/2020/03/02/google-microformats-support/)

I would be happy to raise a PR with changes to the theme to support the h-event markup, so folks can automagically determine event information from the site.

I noticed that we had added schema.org data - which is awesome - and I think that supporting another metadata format should be OK.

**Comment by bridgetkromhout** [comment]
Thanks for the suggestion. We'll need to hear from @mattstratton on the tradeoffs and his call for this. Appreciated.

**Comment by mattstratton** [comment]
Hm. I thought that we had some stuff in there to support rich cards in Google...maybe this isn't the same? 

This is the code for Rich Cards (if I recall the right term from google)

https://github.com/devopsdays/devopsdays-web/blob/master/themes/devopsdays-theme/layouts/partials/events/event_metadata.html#L21-L46

**Comment by mattstratton** [comment]
That said, if you want to look into where we would add this, it would definitely be in that partial linked above. I'd be happy to take a look at a proposed change .

**Comment by bridgetkromhout** [comment]
@mattstratton Looks like @jamietanna put this PR in, which is great! I glanced over it and it doesn't look like it's introducing new variables we'd need to document for event creators. I haven't done any testing, but if you/others want to follow up, I have no particular objection.

**Comment by mattstratton** [comment]
Oh yeah, I already approved the PR; I should just merge it now :)
