### ISSUE TITLE
Behavior not consistent with "sharing_image"

### ISSUE THREAD

**Issue by MikeRosTX** [devopsdays/devopsdays-web#9522]
Just noticed something, and I'm not sure if there's anything we can do about this or if it's a limitation of LinkedIn's side that we're unable to control.

If I share a link on Slack, the **_sharing_image_** feature works as expected:
![image](https://user-images.githubusercontent.com/11631454/75461226-0edb6c80-5948-11ea-8f65-c8fd22355677.png)

But if I shared the same link on LinkedIn, the image shared is the default one we've always seen in the past:
![image](https://user-images.githubusercontent.com/11631454/75461387-595ce900-5948-11ea-9ac2-5c0c76d54461.png)

**Comment by adrianmoisey** [comment]
I thiiiink it's caching

**Comment by MikeRosTX** [comment]
> I thiiiink it's caching

Wondering if it could very well be related to this article like you mentioned @adrianmoisey:
https://www.linkedin.com/pulse/how-clear-linkedin-link-preview-cache-ananda-kannan-p/

**Comment by MikeRosTX** [comment]
That Post Inspector link from LinkedIn resolves this issue:

We have good news, LinkedIn has launched **_Post Inspector_**. You have to do the following to clear LinkedIn Preview cache:

Step 1: Visit **https://www.linkedin.com/post-inspector/**

Step 2: Enter your URL and click on Inspect, You will see the updated preview image

Step 3: Now try sharing your URL on LinkedIn

![image](https://user-images.githubusercontent.com/11631454/75467730-b4470e00-5951-11ea-8df8-4de842cd2d7a.png)

**Comment by adrianmoisey** [comment]
Thanks for figuring that out!
