### ISSUE TITLE
Create communication with migration information

### ISSUE THREAD

**Issue by mattstratton** [devopsdays/devopsdays-web#96]
This will include the proposed dates of migration, link to documents on how to do the things, as well as the "cut-off" dates for "read-only" status.

Should be sent to 
organisers-2015 and 2016 mailing lists
core organizers

**Comment by mattstratton** [comment]
Duplicated in #97

**Comment by bridgetkromhout** [comment]
Migration Timeline

- Saturday April 16, 11:00 UTC
  - 2015 change freeze (https://github.com/devopsdays/devopsdays-web/issues/95, https://github.com/devopsdays/devopsdays-web/issues/29)
  - try to add your 2016 site to hugo by then (https://github.com/devopsdays/devopsdays-web/issues/107).

- Saturday April 30, 11:00 UTC
  - all 2016 sites mirrored into hugo (https://github.com/devopsdays/devopsdays-web/issues/107).
  - dual writes start (any PRs to the old site will need a PR to the new site too - talk to @mattstratton if you need help with this).

- Thursday May 5 11:00 UTC
  - proposed DNS cutover if @jedi4ever can do it then. That time works for @mattstratton.

**Comment by mattstratton** [comment]
:+1:

**Comment by bridgetkromhout** [comment]
Here's what I sent:
```
Hi, folks -

Thank you for being devopsdays organizers! (This is BCCed to all 2016 devopsdays organizers.)

We're working on changes to devopsdays.org that will make it easier to update. The current planned date for the migration is May 5th. Many thanks to Matt Stratton of devopsdays Chicago, who is leading the migration work.

No action is required, but if you'd like to help or would like more info: https://github.com/devopsdays/devopsdays-web/issues/97 (or join #website on devopsdays.slack.com - email me if you need an invite to Slack).

Note that on Saturday April 16th we'll stop merging changes to sites from 2015 and before, so if you need to update old sites, do that now.

Happy organizing!
```

**Comment by bridgetkromhout** [comment]
@jedi4ever - can you confirm whether May 5, 11:00 UTC works for you for a DNS cutover?

**Comment by bridgetkromhout** [comment]
Since this issue only covers creating the communication, which was done, we'll handle followup separately.
