### ISSUE TITLE
Consider adding option "canceled" field for events

### ISSUE THREAD

**Issue by mattstratton** [devopsdays/devopsdays-web#9681]
Currently, with events being canceled, we are suggesting that they keep the current event in the site, in case people have links to it, but remove the dates.

This will make the event still show up on the sidebar under "TBD".

This also causes some confusion if a new event for the following year shows up.

My proposal is to add an optional field to the `YYYY-CITY.yml` file to reflect that the event was canceled. This would then be used to redact the event from display.

Thoughts?

**Comment by bridgetkromhout** [comment]
I think this is a good idea, but let's think through the implications:
- We want a canceled event to still have a working direct link so people can go to the page
- Probably any previous-existing and now-missing sub-pages like a removed schedule or speaker should go to the main page for that event?
- Remove from sidebar (what about main page and past-events page if people don't remove dates?)

**Comment by xavidop** [comment]
I think it is a good solution to add a canceled field.

**Comment by mattstratton** [comment]
> We want a canceled event to still have a working direct link so people can go to the page

That's the current problem - we are leaving the pages intact. Having the event marked "canceled" would not remove `devopsdays.org/events/2020-ponyville` as a link, but it would make Ponyville not show up in the sidebar.

>Probably any previous-existing and now-missing sub-pages like a removed schedule or speaker should go to the main page for that event?

Oof. This would be a huge effort. Most events are just removing those pages from the event site anyway. I don't know how we could easily do this programmatically in the `_redirects` file.

>Remove from sidebar (what about main page and past-events page if people don't remove dates?)

yeah, we should put the same logic on those templates as well; for the main page I was assuming everyone was removing dates from the datafile of the canceled event, but we should check it there too. For the "other years" of the city pages, that should also be flagged to not show up if the event is "canceled".

**Comment by bridgetkromhout** [comment]
> That's the current problem - we are leaving the pages intact. Having the event marked "canceled" would not remove devopsdays.org/events/2020-ponyville as a link, but it would make Ponyville not show up in the sidebar.

Yes. I understand the problem; I'm being explicit about the intended behavior, for when future-us has forgotten. :)

> Oof. This would be a huge effort. Most events are just removing those pages from the event site anyway. I don't know how we could easily do this programmatically in the _redirects file.

Gotcha. For MSP 2020 I'm handling it with aliases in the canceled-event welcome.md file - we could make that optional but suggest it?

```
 Title = "devopsdays Minneapolis 2020"
 Type = "welcome"
-aliases = ["/events/2020-minneapolis/"]
+aliases = [
+    "/events/2020-minneapolis/",
+    "/events/2020-minneapolis/location/",
+    "/events/2020-minneapolis/propose/",
+    "/events/2020-minneapolis/registration/",
+    "/events/2020-minneapolis/sponsor/"
+]
```

> yeah, we should put the same logic on those templates as well; for the main page I was assuming everyone was removing dates from the datafile of the canceled event, but we should check it there too. For the "other years" of the city pages, that should also be flagged to not show up if the event is "canceled".

(nods)

**Comment by mattstratton** [comment]
Oh! For some reason, I was thinking you wanted the sub-pages of the old, canceled event to go to the new, replacement event. Creating the additional aliases on the `welcome.md` of the canceled event makes sense, and I agree that it is something we should document/suggest but not do automatically.

**Comment by mattstratton** [comment]
thinking out loud, changes will look like this:

_layouts/index.html_

```
{{- if .startdate -}}
	{{- if ne .cancelled "true" -}}
...
	{{- end -}}
{{- end -}}
</div>
```

_layouts/partials/welcome.html_
```
 {{- range sort $.Site.Data.events "startdate" -}}
   {{- if .startdate -}}
	 {{- if ne .cancelled "true" -}}
...
  	{{- end -}}
  {{- end -}}
 {{- end -}}		 
```  

_layouts/partials/future.html_
```
{{- range sort $.Site.Data.events "startdate" -}}
  {{- if .startdate -}}
	{{- if ne .cancelled "true" -}}
...
	{{- end -}}
  {{- end -}}
 {{- end -}}
...
...
...
{{- range $.Site.Data.events -}}
  {{- if not .startdate -}}
	{{- if ne .cancelled "true" -}}
    	<a href = "{{ (printf "/events/%s" .name) }}" class = "left-nav-event">{{ .city }}</a><br />
	{{- end -}}
  {{- end -}}
{{- end -}}
```

This is probably all the changes - the syntax might not be exactly right (I'm doing this in the github issue editor) but I think that's all the places. This assumes that there will be a top-level field added to the datafile with the field name of "canceled", which must take "true" (case sensitive). Like this:

```
startdate: 
enddate: 
canceled: "true"
```

**Comment by mattstratton** [comment]
Looking at Boise, I think that the "previous events" part (in `partials/welcome.html`) already handles this in a way...if there is no `startdate`, it doesn't show it. 

![image](https://user-images.githubusercontent.com/1280666/78562942-cd0fd280-77df-11ea-8bea-e25c57284950.png)

This is also true on `index.html`; in theory a canceled event does not have a startdate, so it won't show up on the main page (non-sidebar).

Basically, now that I think about it, looking at this:

>(what about main page and past-events page if people don't remove dates?)

the only place that events without a startdate show up is in `partials/future.html`. I mean we *could* add the logic to test even for "canceled" if a `startdate` is set, but that seems to be an edge case? Although maybe just to be safe we should (makes it slightly easier to "cancel" an event, because all you have to do is set that flag; if we want to do that, we should also put the check into `partials/speaking.html` so that they don't show up in the open CFP section.

Now that I've typed all this up, I'm thinking it's best to include the check everywhere; that way all someone has to do to cancel an event is set that flag (in theory they should also do the aliases that @bridgetkromhout mentioned, but that's a manual step anyway).

Thinking even more on that...I wonder how hard it would be to throw together some MVB (minimum viable bash) to do the following:

1. Prompt for city and year
1. Add the `canceled: "true"` to `YYYY-CITY.yml` *should test to see if things freak out if it is in there more than once?*
1. Delete common pages from `content/events/YYYY-CITY/` directory (`location.md`, `propose.md`, `sponsor.md`, and `registstration.md`) - *will need to have some exception handling if a file doesn't exist.*
1. Update `welcome.md` with an array of redirects for the root of the event (which will already be there) as well as the four deleted files *the files need to be deleted because the existence of the files will override the aliases*

**Comment by mattstratton** [comment]
#9707 should handle this, I made a couple small tweaks to my proposal:

1. I changed the field to `cancel` since there is inconsistency globally in the spelling of "canceled" :)
1. I also added checks for the footer for open CFP and the speaking page. Again, most of this is caught if dates are removed, but if you set `cancel: "true"` in the event data file, it will generally remove it from everywhere automatically (that said, you want to remove the dates anyway because of the welcome page; this is just a double-check)
