### ISSUE TITLE
move pdf's and stuff to assets.devopsdays.org

### ISSUE THREAD

**Issue by mattstratton** [devopsdays/devopsdays-web#979]
There are a bunch of big PDFs and other files in the repo. We can move to them to `devopsdays/devopsdays-assets`, and then create a redirect on www to send them over to `assets.devopsdays.org`.

We can then rewrite history and clean up the repo.

**Comment by yvovandoorn** [comment]
I'll prepare the history writing apparatuses.

**Comment by bridgetkromhout** [comment]
I'm going to close this for now. We can revisit if we're ever working on this.
