### ISSUE TITLE
Strange commit contents for Ohio 2016 commit

### ISSUE THREAD

**Issue by glennsarti** [devopsdays/devopsdays-web#984]
Whilst review some commits I came across this commit;
https://github.com/devopsdays/devopsdays-web/commit/c7771105690d0a36b4d0e3892e99330095e5c18f

The associated PR (https://github.com/devopsdays/devopsdays-web/pull/976) only had a single commit with a small number of files for Ohio, however the actual commit modified 995 files, apparently adding a whole bunch of image files back into `content/events` and `static/events`

This may be related to the previous commit https://github.com/devopsdays/devopsdays-web/commit/6768de59de8b8ef4c443fe6b6cf78513b61ff4a9

**Comment by bridgetkromhout** [comment]
We had a history cleanup and this might be related. I'm going to ask @yvovandoorn and @mattstratton to weigh in here.

**Comment by mattstratton** [comment]
Yep. I think it's part of the history rewrite. Shouldn't hurt anything?

**Comment by glennsarti** [comment]
Probably won't hurt...but hard to say without doing a before and after build using hugo.  Also I'm not sure if all of those files should be there...

e.g.
https://github.com/devopsdays/devopsdays-web/tree/master/static/events/2015-amsterdam now only has a single logo file in it which was added in that commit

https://github.com/devopsdays/devopsdays-web/commits/master/static/events/2015-amsterdam

It's like that commit was reverting some of the delete's in the previous one.  Seems very suspicious that it's basically all image files.  I thought the legacy redirection would render these files moot?

**Comment by mattstratton** [comment]
Amsterdam wasn't migrated. But @yvovandoorn did detect a bunch of large files. Also there were some old commits that shrank large files, etc. 

The best thing you can do is make sure to rebase/clone the repo rather than trying to merge what's in there now. It's clean green, but piling it onto a local, non-cleaned version is going to cause some issues because of the history rewrite.

**Comment by mattstratton** [comment]
I'm pretty sure that when the rewrite happened, it piled all the "work" of the rewrite onto the most recent commit, which is the ohio one.

**Comment by glennsarti** [comment]
For what it's worth, I was using a fresh clone from this repo (rather than my fork). And referencing github UI.

Fair enough on the rewrite.  Happy to close the issue.  I guess it was more of an FYI incase anyone else sees it too.
