### ISSUE TITLE
Add windows filename check to PR reviews

### ISSUE THREAD

**Issue by glennsarti** [devopsdays/devopsdays-web#988]
Now that https://github.com/devopsdays/devopsdays-web/issues/641 has been resolved, it would be good to have an automated process that checks incoming PRs etc. so that bad filenames won't creep in again.

Previously I wrote a small shell script to run in wercker however now that DoD is hosted on netlify I don't see how to do that anymore.

I see three potential ways to do this:
1. Add a git pre-commit hook to run the same file
   The searching does take a long time so this seems like a bad idea.
2. Somehow add a pre deployment script to Netlify to throw errors for bad filenames
   Unknown how to do this, but may be trivial
3. Add a Windows based PR evaluator
   Appveyor is a common PR webhook tool.  It could easily validate whether something works on windows as it runs 2012 R2 workers.  Easy enough to git checkout and run a hugo build to ensure it works on Windows.

If this issue is accepted, I am happy to submit a PR for point no. 3 and create an appropriate `appveyor.yml` file.  The maintainers of this repo would need to connect up Appveyor to complete the process.

**Comment by mattstratton** [comment]
This actually (probably) cannot happen with Hugo. Almost everything is auto-generated. I think this is worth thinking about, but I am not sure that the corners will hit that cause this to happen. But let's try the appveyor approach, as long as it's free :)

**Comment by glennsarti** [comment]
There is a free tier of Appveyor available to Open Source projects.  Chef and Puppet, amongst other OS projects use it.

**Comment by mattstratton** [comment]
This has been fixed by adding appveyor.
