### ISSUE TITLE
Many shortcode templates are failing due to path seperator failure

### ISSUE THREAD

**Issue by glennsarti** [devopsdays/devopsdays-web#989]
There are many places within the codebase that use a section such as

```
{{ $path := split .Page.Source.File.Path "/" }}
```

Unfortunately in Hugo `File.Path` returns an OS dependent path i.e. `/` on unix style OS and `\` on Windows.  While Go itself is able to handle this easily, Hugo does not seem to expose any standard functions to either detect the path separator (`PathSeparator` in https://golang.org/pkg/os/#FileInfo) or canonicalise a path in a safe way (ala `expand_path` in Ruby)

This means the hardcoded separator code fails in Windows operating systems

My suggestion would be to replace the code above to be similar to something below:

```
{{ $thisPath := replace .Page.Source.File.Path "\\" "/" }}
{{ $path := split $thisPath "/" }}
```

While I hate the use of string replacement here as it is a hack, it should be an ok shortcut to use.   There should be no file or directory names with `\` as it is an illegal filename in Windows.

If you're ok with this solution I'm happy to raise a PR with the relevant changes.

**Comment by mattstratton** [comment]
My concern is that this may fix the existing issues, but there's no guarantee that new code won't have these issues. 

Since this can run using Docker locally as a "mini-VM", having to put in place a requirement to defensively code around Windows for all shared code dev isn't something we can really do.

**Comment by mattstratton** [comment]
I've got an idea for making this easier on Windows, but it will have to wait until after Chicago this week :)

**Comment by glennsarti** [comment]
@mattstratton Ok.....In the mean time, I'll raise a ticket against Hugo to get an "agnostic" relative path or something to help with this situation.

**Comment by glennsarti** [comment]
To be fair, this doesn't appear to be a fault with this project, but how Hugo is handling paths.  Unfortunately this project may need to carry a workaround until Hugo is updated :-(

**Comment by mattstratton** [comment]
Would this help in the meantime? https://discuss.gohugo.io/t/hugo-on-bashonwindows-windows-subsystem-for-linux/3976
