### ISSUE TITLE
figure out how to use google analytics per-event

### ISSUE THREAD

**Issue by bridgetkromhout** [devopsdays/devopsdays-web#997]
Despite merging in https://github.com/devopsdays/devopsdays-web/pull/983, GAnalytics isn't working for Brasília. @mattstratton can look at it after devopsdays Chicago. This is of interest to @adrianovieira.

**Comment by mattstratton** [comment]
I have an unpublished branch with about 90% of the fix...I should be able to resolve this later this week.

**Comment by adrianovieira** [comment]
`prod`

**Comment by mattstratton** [comment]
This feature is being added to the new devopsdays-theme; see the above-mentioned ticket. I'm closing this ticket, but track it at https://github.com/devopsdays/devopsdays-theme/issues/136.
